name = "NOVAS"
version = "3.1"
author = "G. H. Kaplan"
copyright = "Copyright (c) U.S. Naval Observatory"
license = "Public domain"
description = "Naval observatory vector astrometry software"
maintainer = "Jacob Williams"
homepage = "https://github.com/jacobwilliams/NOVAS"

[library]
source-dir = "src"

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

