aberat – NOVAS
aberat Subroutine
27 statements
Source File
public subroutine aberat(pos1, ve, tlight, pos2)
THIS SUBROUTINE CORRECTS POSITION VECTOR FOR ABERRATION OF LIGHT. ALGORITHM INCLUDES RELATIVISTIC TERMS. ADAPTED FROM MURRAY (1981) MON. NOTICES ROYAL AST. SOCIETY 195, 639-648.
 POS1   = POSITION VECTOR OF OBSERVED OBJECT, WITH REESPECT TO
          ORIGIN AT OBSERVER (OR THE GEOCENTER), COMPONENTS
          IN AU (IN)
 VE     = VELOCITY VECTOR OF OBSERVER (OR THE GEOCENTER),
          WITH RESPECT TO ORIGIN AT SOLAR SYSTEM BARYCENTER,
          COMPONENTS IN AU/DAY (IN)
 TLIGHT = LIGHT TIME FROM BODY TO OBSERVER (OR THE GEOCENTER)
          IN DAYS (IN)
          IF TLIGHT = 0.D0, THIS SUBROUTINE WILL COMPUTE
 POS2   = POSITION VECTOR OF OBSERVED OBJECT, WITH RESPECT TO
          ORIGIN AT OBSERVER (OR THE GEOCENTER), CORRECTED
          FOR ABERRATION, COMPONENTS IN AU (OUT)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), dimension(3) :: pos1
real(kind=wp), dimension(3) :: ve
real(kind=wp) :: tlight
real(kind=wp), dimension(3) :: pos2
Calls
Called by
Call graph
aberat calls astcon
place calls aberat
mpstar calls place
places calls place