ANGLES – slsqp
ANGLES Subroutine
16 statements
Source File
subroutine ANGLES(POS, RA, DEC)
Arguments
Type Intent Optional Attributes Name
double precision :: POS
double precision :: RA
double precision :: DEC
Calls
Called by
Contents
None
Call graph
angles calls setvec
gcrseq calls angles
place calls angles
mpstar calls angles, place
places calls place