anmp – NOVAS
anmp Function
7 statements
Source File
public pure elemental function anmp(a) result(w)
Normalize angle into the range -pi <= A < +pi.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: a
Return Value real(kind=wp)
Called by
Contents
Source Code
anmp
Source Code
    pure elemental function anmp ( a ) result(w)
    implicit none
    real(wp),intent(in) :: a
    real(wp) :: w
    w = mod(a,twopi)
    if ( abs(w) >= pi ) w = w - sign(twopi,a)
    end function anmp
Call graph
eect2000 calls anmp
etilt calls eect2000
eqec calls etilt
geopos calls etilt, nutate, sidtim
nutate calls etilt
sidtim calls etilt, nutate, eqxra, ciobas, cioloc
eceq calls etilt
eqxra calls etilt
place calls geopos, nutate, ciobas, cioloc
celter calls nutate, sidtim, ciobas, cioloc
tercel calls nutate, sidtim, ciobas, cioloc
gcrseq calls nutate, ciobas, cioloc
ciobas calls nutate
ciora calls nutate, ciobas, cioloc
eqecl calls eqec
cioloc calls eqxra
zdaz calls tercel
places calls place
mpstar calls place