catran – NOVAS
catran Subroutine
96 statements
Source File
public subroutine catran(it, date1, ra1, dec1, pmra1, pmdec1, parx1, rv1, date2, ra2, dec2, pmra2, pmdec2, parx2, rv2)
THIS SUBROUTINE TRANSFORMS A STAR'S CATALOG QUANTITIES FOR A CHANGE OF EPOCH AND/OR EQUATOR AND EQUINOX. IT CAN ALSO BE USED TO ROTATE CATALOG QUANTITIES ON THE DYNAMICAL EQUATOR AND EQUINOX OF J2000.0 TO THE ICRS OR VICE VERSA.
   IT     = TRANSFORMATION OPTION (IN)
            SET IT=1 TO CHANGE EPOCH (SAME EQUATOR AND EQUINOX)
            SET IT=2 TO CHANGE EQUATOR AND EQUINOX (SAME EPOCH)
            SET IT=3 TO CHANGE EQUATOR AND EQUINOX AND EPOCH
            SET IT=4 TO CHANGE EQUATOR AND EQUINOX OF J2000.0
                     TO ICRS
            SET IT=5 TO CHANGE ICRS TO EQUATOR AND EQUINOX OF
                     J2000.0
   DATE1  = TT JULIAN DATE, OR YEAR, OF ORIGINAL CATALOG
            DATA (THE FOLLOWING SIX ARGUMENTS) (IN)
   RA1    = ORIGINAL MEAN RIGHT ASCENSION IN HOURS (IN)
   DEC1   = ORIGINAL MEAN DECLINATION IN DEGREES (IN)
   PMRA1  = ORIGINAL PROPER MOTION IN RA
            IN MILLIARCSECONDS/YEAR (IN)
   PMDEC1 = ORIGINAL PROPER MOTION IN DEC
            IN MILLIARCSECONDS/YEAR (IN)
   PARX1  = ORIGINAL PARALLAX IN MILLIARCSECONDS (IN)
   RV1    = ORIGINAL RADIAL VELOCITY IN KILOMETERS/SECOND
            (IN)
   DATE2  = TT JULIAN DATE, OR YEAR, FOR TRANSFORMED
            OUTPUT DATA (THE FOLLOWING SIX ARGUMENTS) (IN)
   RA2    = TRANSFORMED MEAN RIGHT ASCENSION IN HOURS (OUT)
   DEC2   = TRANSFORMED MEAN DECLINATION IN DEGREES (OUT)
   PMRA2  = TRANSFORMED PROPER MOTION IN RA
            IN MILLIARCSECONDS/YEAR (OUT)
   PMDEC2 = TRANSFORMED PROPER MOTION IN DEC
            IN MILLIARCSECONDS/YEAR (OUT)
   PARX2  = TRANSFORMED PARALLAX IN MILLIARCSECONDS (OUT)
   RV2    = TRANSFORMED RADIAL VELOCITY IN KILOMETERS/SECOND
            (OUT)
NOTE 1: DATE1 AND DATE2 MAY BE SPECIFIED EITHER AS A JULIAN DATE (E.G., 2433282.5D0) OR A JULIAN YEAR AND FRACTION (E.G., 1950.0D0). VALUES LESS THAN 10000 ARE ASSUMED TO BE YEARS. FOR IT=2 OR IT=3, EITHER DATE1 OR DATE2 MUST BE 2451545.0 OR 2000.0 (J2000.0). FOR IT=4 AND IT=5, DATE1 AND DATE2 ARE IGNORED.
NOTE 2: IT=1 UPDATES THE STAR'S DATA TO ACCOUNT FOR THE STAR'S SPACE MOTION BETWEEN THE FIRST AND SECOND DATES, WITHIN A FIXED REFERENCE SYSTEM. IT=2 APPLIES A ROTATION OF THE REFERENCE SYSTEM CORRESPONDING TO PRECESSION BETWEEN THE FIRST AND SECOND DATES, BUT LEAVES THE STAR FIXED IN SPACE. IT=3 PROVIDES BOTH TRANSFORMATIONS. IT=4 AND IT=5 PROVIDE A A FIXED ROTATION ABOUT VERY SMALL ANGLES (<0.1 ARCSECOND) TO TAKE DATA FROM THE DYNAMICAL SYSTEM OF J2000.0 TO THE ICRS (IT=4) OR VICE VERSA (IT=5).
NOTE 3: FOR IT=1, INPUT DATA CAN BE IN ANY FIXED REFERENCE SYSTEM. FOR IT=2 OR IT=3, THIS SUBROUTINE ASSUMES THE INPUT DATA IS IN THE DYNAMICAL SYSTEM AND PRODUCES OUTPUT IN THE DYNAMICAL SYSTEM. FOR IT=4, THE INPUT DATA MUST BE ON THE DYNAMICAL EQUATOR AND EQUINOX OF J2000.0. FOR IT=5, THE INPUT DATA MUST BE IN THE ICRS.
NOTE 4: THIS SUBROUTINE CANNOT BE PROPERLY USED TO BRING DATA FROM OLD STAR CATALOGS INTO THE MODERN SYSTEM, BECAUSE OLD CATALOGS WERE COMPILED USING A SET OF CONSTANTS THAT ARE INCOMPATIBLE WITH MODERN VALUES. IN PARTICULAR, IT SHOULD NOT BE USED FOR CATALOGS WHOSE POSITIONS AND PROPER MOTIONS WERE DERIVED BY ASSUMING A PRECESSION CONSTANT SIGNIFICANTLY DIFFERENT FROM THE VALUE IMPLICIT IN SUBROUTINE PRECES.
Arguments
Type Intent Optional Attributes Name
integer :: it
double precision :: date1
double precision :: ra1
double precision :: dec1
double precision :: pmra1
double precision :: pmdec1
double precision :: parx1
double precision :: rv1
double precision :: date2
double precision :: ra2
double precision :: dec2
double precision :: pmra2
double precision :: pmdec2
double precision :: parx2
double precision :: rv2
Calls
Called by
Contents
None
Call graph
catran calls astcon, preces, setvec, dasin, frame
gethip calls catran