celter – NOVAS
celter Subroutine
55 statements
Source File
public subroutine celter(tjdh, tjdl, xp, yp, vec1, vec2)
THIS SUBROUTINE ROTATES A VECTOR FROM THE CELESTIAL TO THE TERRESTRIAL SYSTEM. SPECIFICALLY, IT TRANSFORMS A VECTOR IN THE GCRS (A LOCAL SPACE-FIXED SYSTEM) TO THE ITRS (A ROTATING EARTH-FIXED SYSTEM) BY APPLYING ROTATIONS FOR THE GCRS-TO- DYNAMICAL FRAME TIE, PRECESSION, NUTATION, EARTH ROTATION, AND POLAR MOTION.
   TJDH   = UT1 JULIAN DATE, HIGH-ORDER PART (IN)
   TJDL   = UT1 JULIAN DATE, LOW-ORDER PART (IN)
            THE JULIAN DATE MAY BE SPLIT AT ANY POINT, BUT
            FOR HIGHEST PRECISION, SET TJDH TO BE THE INTEGRAL
            PART OF THE JULIAN DATE, AND SET TJDL TO BE THE
            FRACTIONAL PART
   XP     = CONVENTIONALLY-DEFINED X COORDINATE OF CELESTIAL
            INTERMEDIATE POLE WITH RESPECT TO ITRS POLE,
            IN ARCSECONDS (IN)
   YP     = CONVENTIONALLY-DEFINED Y COORDINATE OF CELESTIAL
            INTERMEDIATE POLE WITH RESPECT TO ITRS POLE,
            IN ARCSECONDS (IN)
   VEC1   = POSITION VECTOR, GEOCENTRIC EQUATORIAL RECTANGULAR
            COORDINATES, REFERRED TO GCRS AXES (CELESTIAL
            SYSTEM) (IN)
   VEC2   = POSITION VECTOR, GEOCENTRIC EQUATORIAL RECTANGULAR
            COORDINATES, REFERRED TO ITRS AXES (TERRESTRIAL
            SYSTEM) (OUT)
NOTE 1: SET XP=YP=0.D0 TO ELIMINATE POLAR MOTION ROTATION.
NOTE 2: SEE ALSO SUBROUTINE SETDT TO SET THE VALUE OF DELTA-T (DELTA-T = TT - UT1) TO BE USED HERE.
NOTE 3: BOTH TJDH AND TJDL SHOULD BE NON-NEGATIVE FOR NORMAL USE (TJDL=0.D0 IS OK). A NEGATIVE VALUE OF TJDH IS USED TO INVOKE A SPECIAL OPTION WHERE THE INPUT VECTOR IS ASSUMED TO BE WITH RESPECT TO THE EQUATOR AND EQUINOX OF DATE, AND THE DATE FOR WHICH THE TRANSFORMATION APPLIES IS TAKEN FROM TJDL ONLY. THIS OPTION WORKS ONLY IN 'EQUINOX' MODE.
Arguments
Type Intent Optional Attributes Name
double precision :: tjdh
double precision :: tjdl
double precision :: xp
double precision :: yp
double precision :: vec1
double precision :: vec2
Calls
Contents
None
Call graph
celter calls erot, wobble, times, getdt, preces, sidtim, ciobas, getmod, setvec, nutate, spin, cioloc, frame
sidtim calls erot, times, getdt, preces, ciobas, getmod, nutate, cioloc, frame, etilt, eqxra
ciobas calls preces, nutate, frame
nutate calls etilt
cioloc calls eqxra, ciord
etilt calls preces, getmod, frame, funarg, eect2000, nod
eqxra calls etilt
eect2000 calls anmp
nod calls getmod, nu2000a, nu2000k
nu2000k calls funarg