ciobas – NOVAS
ciobas Subroutine
48 statements
Source File
public subroutine ciobas(tjd, racio, k, x, y, z)
THIS SUBROUTINE RETURNS THE ORTHONORMAL BASIS VECTORS, WITH RESPECT TO THE GCRS (GEOCENTRIC ICRS), OF THE CELESTIAL INTERMEDIATE SYSTEM DEFINED BY THE CELESTIAL INTERMEDIATE POLE (CIP) (IN THE Z DIRECTION) AND THE CELESTIAL INTERMEDIATE ORIGIN (CIO) (IN THE X DIRECTION). A TDB JULIAN DATE AND THE RIGHT ASCENSION OF THE CIO AT THAT DATE IS REQUIRED AS INPUT. THE RIGHT ASCENSION OF THE CIO CAN BE WITH RESPECT TO EITHER THE GCRS ORIGIN OR THE TRUE EQUINOX OF DATE -- DIFFERENT ALGORITHMS ARE USED IN THE TWO CASES.
   TJD    = TDB JULIAN DATE (IN)
   RACIO  = RIGHT ASCENSION OF THE CIO, IN HOURS (IN)
   K      = REFERENCE SYSTEM IN WHICH RIGHT ASCENSION IS
            EXPRESSED (IN)
            SET K=1 FOR GCRS
            SET K=2 FOR TRUE EQUATOR AND EQUINOX OF DATE
   X      = UNIT VECTOR TOWARD THE CIO, EQUATORIAL RECTANGULAR
            COORDINATES, REFERRED TO THE GCRS (OUT)
   Y      = UNIT VECTOR TOWARD THE Y-DIRECTION, EQUATORIAL
            RECTANGULAR COORDINATES, REFERRED TO THE GCRS (OUT)
   Z      = UNIT VECTOR TOWARD NORTH CELESTIAL POLE (CIP),
            EQUATORIAL RECTANGULAR COORDINATES, REFERRED TO
            THE GCRS (OUT)
Arguments
Type Intent Optional Attributes Name
double precision :: tjd
double precision :: racio
integer :: k
double precision :: x
double precision :: y
double precision :: z
Calls
Called by
Contents
None
Call graph
ciobas calls preces, nutate, frame
nutate calls etilt
etilt calls preces, frame, funarg, eect2000, getmod, nod
eect2000 calls anmp
nod calls getmod, nu2000a, nu2000k
nu2000k calls funarg
place calls ciobas, geopos
sidtim calls ciobas
tercel calls ciobas, sidtim
ciora calls ciobas
gcrseq calls ciobas
celter calls ciobas, sidtim
places calls place
zdaz calls tercel
geopos calls sidtim
mpstar calls place