cioloc – NOVAS
cioloc Subroutine
42 statements
Source File
public subroutine cioloc(tjd, racio, k)
THIS SUBROUTINE RETURNS THE LOCATION OF THE CELESTIAL INTERMEDIATE ORIGIN (CIO) FOR A GIVEN JULIAN DATE, AS A RIGHT ASCENSION WITH RESPECT TO EITHER THE GCRS (GEOCENTRIC ICRS) ORIGIN OR THE TRUE EQUINOX OF DATE. THE CIO IS ALWAYS LOCATED ON THE TRUE EQUATOR (=INTERMEDIATE EQUATOR) OF DATE.
   TJD    = TDB JULIAN DATE (IN)
   RACIO  = RIGHT ASCENSION OF THE CIO, IN HOURS (OUT)
   K      = REFERENCE SYSTEM IN WHICH RIGHT ASCENSION IS
            GIVEN (OUT)
            K=1 MEANS GCRS
            K=2 MEANS TRUE EQUATOR AND EQUINOX OF DATE
NOTE: IF AN EXTERNAL FILE OF CIO RIGHT ASCENSIONS IS AVAILABLE, IT WILL BE USED AND K WILL BE SET TO 1. OTHERWISE AN INTERNAL COMPUTATION WILL BE USED AND K WILL BE SET TO 2.
Arguments
Type Intent Optional Attributes Name
double precision :: tjd
double precision :: racio
integer :: k
Calls
Called by
Contents
None
Call graph
cioloc calls eqxra, ciord
eqxra calls etilt
etilt calls nod, eect2000, funarg, frame, preces, getmod
nod calls getmod, nu2000a, nu2000k
eect2000 calls anmp
nu2000k calls funarg
celter calls cioloc, sidtim
place calls cioloc, geopos
gcrseq calls cioloc
ciora calls cioloc
sidtim calls cioloc
tercel calls cioloc, sidtim
geopos calls sidtim
places calls place
mpstar calls place
zdaz calls tercel