ciord – NOVAS
ciord Subroutine
164 statements
Source File
public subroutine ciord(tjd, nvals, tlist, ralist, ierr)
GIVEN AN INPUT TDB JULIAN DATE AND THE NUMBER OF DATA POINTS DESIRED, THIS SUBROUTINE RETURNS A SET OF JULIAN DATES AND CORRESPONDING VALUES OF THE GCRS RIGHT ASCENSION OF THE CELESTIAL INTERMEDIATE ORIGIN (CIO). THE RANGE OF DATES IS CENTERED (AT LEAST APPROXIMATELY) ON THE REQUESTED DATE. THE SUBROUTINE OBTAINS THE DATA FROM AN EXTERNAL DATA FILE.
TJD    = TDB JULIAN DATE (IN)
NVALS  = NUMBER OF JULIAN DATES AND RIGHT ASCENSION VALUES
         REQUESTED (NOT LESS THAN 2 OR MORE THAN 20) (IN)
TLIST  = ARRAY OF TDB JULIAN DATES (OUT)
RALIST = ARRAY OF GCRS RIGHT ASCENSIONS OF THE CIO, FOR THE
         JULIAN DATES IN TLIST, IN ARCSECONDS (OUT)
IERR   = ERROR INDICATOR (OUT)
         IERR=0 MEANS EVERYTHING OK
         IERR=1 MEANS TJD BEFORE FIRST USABLE DATE IN FILE
         IERR=2 MEANS TJD AFTER LAST USABLE DATE IN FILE
         IERR=3 MEANS BAD VALUE OF NVALS
         IERR=4 MEANS EXTERNAL FILE CANNOT BE FOUND
NOTE: TJD=0.D0 WITH NVALS=1 INDICATES A SPECIAL CALL JUST TO DETERMINE IF EXTERNAL FILE EXISTS.
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: tjd
integer :: nvals
real(kind=wp), dimension(nvals) :: tlist
real(kind=wp), dimension(nvals) :: ralist
integer :: ierr
Calls
Called by
Call graph
ciord calls ciofil
cioloc calls ciord
celter calls cioloc, sidtim
ciora calls cioloc
gcrseq calls cioloc
place calls cioloc, geopos
sidtim calls cioloc
tercel calls cioloc, sidtim
geopos calls sidtim
mpstar calls place
places calls place
zdaz calls tercel