ciora – NOVAS
ciora Subroutine
22 statements
Source File
public subroutine ciora(tjd, racio)
THIS SUBROUTINE COMPUTES THE TRUE RIGHT ASCENSION OF THE CELESTIAL INTERMEDIATE ORIGIN (CIO) AT A GIVEN TT JULIAN DATE. THIS IS -(EQUATION OF THE ORIGINS).
 TJD    = TT JULIAN DATE (IN)
 RACIO  = RIGHT ASCENSION OF THE CIO, WITH RESPECT TO THE
          TRUE EQUINOX OF DATE, IN HOURS (+ OR -) (OUT)
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: tjd
real(kind=wp) :: racio
Calls
Call graph
ciora calls ciobas, cioloc, frame, nutate, preces, times
ciobas calls frame, nutate, preces
cioloc calls ciord, eqxra
nutate calls etilt
ciord calls ciofil
eqxra calls etilt
etilt calls frame, preces, celpol, getmod, eect2000, funarg, nod
eect2000 calls anmp
nod calls getmod, nu2000a, nu2000k
nu2000k calls funarg