dlight – NOVAS
dlight Subroutine
15 statements
Source File
public subroutine dlight(pos1, pe, diflt)
THIS SUBROUTINE RETURNS THE DIFFERENCE IN LIGHT-TIME, FOR A STAR, BETWEEN THE BARYCENTER OF THE SOLAR SYSTEM AND THE OBSERVER (OR THE GEOCENTER).
   POS1   = POSITION VECTOR OF STAR, WITH RESPECT TO ORIGIN AT
            SOLAR SYSTEM BARYCENTER (IN)
   PE     = POSITION VECTOR OF OBSERVER (OR THE GEOCENTER),
            WITH RESPECT TO ORIGIN AT SOLAR SYSTEM BARYCENTER,
            COMPONENTS IN AU (IN)
   DIFLT  = DIFFERENCE IN LIGHT TIME, IN THE SENSE STAR TO
            BARYCENTER MINUS STAR TO EARTH, IN DAYS (OUT)
-OR-
THIS SUBROUTINE RETURNS THE LIGHT-TIME FROM THE OBSERVER (OR THE GEOCENTER) TO A POINT ON A LIGHT RAY THAT IS CLOSEST TO A SPECIFIC SOLAR SYSTEM BODY.
   POS1   = POSITION VECTOR TOWARD OBSERVED OBJECT, WITH RESPECT
            TO ORIGIN AT OBSERVER (OR THE GEOCENTER) (IN)
   PE     = POSITION VECTOR OF SOLAR SYSTEM BODY, WITH RESPECT
            TO ORIGIN AT OBSERVER (OR THE GEOCENTER), COMPONENTS
            IN AU (IN)
   DIFLT  = LIGHT TIME TO POINT ON LINE DEFINED BY POS1 THAT IS
            CLOSEST TO SOLAR SYSTEM BODY (POSITIVE IF LIGHT
            PASSES BODY BEFORE HITTING OBSERVER, I.E., IF
            POS1 IS WITHIN 90 DEGREES OF PE)(OUT)
Arguments
Type Intent Optional Attributes Name
double precision :: pos1
double precision :: pe
double precision :: diflt
Calls
Called by
Contents
None
Call graph
dlight calls astcon
place calls dlight, grvdef
grvdef calls dlight
mpstar calls place
places calls place