eqecl – NOVAS
eqecl Subroutine
20 statements
Source File
public subroutine eqecl(tjd, icoord, ra, dec, elon, elat)
THIS SUBROUTINE CONVERTS RIGHT ASCENSION AND DECLINATION TO ECLIPTIC LONGITUDE AND LATITUDE.
   TJD    = TT JULIAN DATE OF EQUATOR, EQUINOX, AND ECLIPTIC
            USED FOR COORDINATES (IN)
   ICOORD = COORDINATE SYSTEM SELECTION (IN)
            SET ICOORD=0 FOR MEAN EQUATOR AND EQUINOX OF DATE
            SET ICOORD=1 FOR TRUE EQUATOR AND EQUINOX OF DATE
            (ECLIPTIC IS ALWAYS THE MEAN PLANE)
   RA     = RIGHT ASCENSION IN HOURS, REFERRED TO SPECIFIED
            EQUATOR AND EQUINOX OF DATE (IN)
   DEC    = DECLINATION IN DEGREES, REFERRED TO SPECIFIED
            EQUATOR AND EQUINOX OF DATE (IN)
   ELON   = ECLIPTIC LONGITUDE IN DEGREES, REFERRED TO SPECIFIED
            ECLIPTIC AND EQUINOX OF DATE (OUT)
   ELAT   = ECLIPTIC LATITUDE IN DEGREES, REFERRED TO SPECIFIED
            ECLIPTIC AND EQUINOX OF DATE (OUT)
NOTE: TO CONVERT ICRS RA AND DEC TO ECLIPTIC COORDINATES (MEAN ECLIPTIC AND EQUINOX OF J2000.0), SET TJD = 0.D0 AND ICOORD = 0. EXCEPT FOR THE INPUT TO THIS CASE, ALL COORDINATES ARE DYNAMICAL.
Arguments
Type Intent Optional Attributes Name
double precision :: tjd
integer :: icoord
double precision :: ra
double precision :: dec
double precision :: elon
double precision :: elat
Calls
Contents
None
Call graph
eqecl calls eqec
eqec calls times, frame, etilt, setvec
etilt calls frame, preces, funarg, eect2000, getmod, nod
eect2000 calls anmp
nod calls getmod, nu2000k, nu2000a
nu2000k calls funarg