eqec – NOVAS
eqec Subroutine
30 statements
Source File
public subroutine eqec(tjd, icoord, pos1, pos2)
THIS SUBROUTINE CONVERTS AN EQUATORIAL POSITION VECTOR TO AN ECLIPTIC POSITION VECTOR.
   TJD    = TT JULIAN DATE OF EQUATOR, EQUINOX, AND ECLIPTIC
            USED FOR COORDINATES (IN)
   ICOORD = COORDINATE SYSTEM SELECTION (IN)
            SET ICOORD=0 FOR MEAN EQUATOR AND EQUINOX OF DATE
            SET ICOORD=1 FOR TRUE EQUATOR AND EQUINOX OF DATE
            (ECLIPTIC IS ALWAYS THE MEAN PLANE)
   POS1   = POSITION VECTOR, REFERRED TO SPECIFIED
            EQUATOR AND EQUINOX OF DATE (IN)
   POS2   = POSITION VECTOR, REFERRED TO SPECIFIED
            ECLIPTIC AND EQUINOX OF DATE (OUT)
NOTE: TO CONVERT ICRS VECTORS TO ECLIPTIC VECTORS (MEAN ECLIPTIC AND EQUINOX OF J2000.0 ONLY), SET TJD = 0.D0 AND ICOORD = 0. EXCEPT FOR THE INPUT TO THIS CASE, ALL VECTORS ARE ASSUMED TO BE WITH RESPECT TO A DYNAMICAL SYSTEM.
Arguments
Type Intent Optional Attributes Name
double precision :: tjd
integer :: icoord
double precision :: pos1
double precision :: pos2
Calls
Called by
Contents
None
Call graph
eqec calls frame, setvec, etilt, times
etilt calls frame, nod, funarg, eect2000, preces, getmod
nod calls getmod, nu2000a, nu2000k
eect2000 calls anmp
nu2000k calls funarg
eqecl calls eqec