eqxra – NOVAS
eqxra Subroutine
18 statements
Source File
public subroutine eqxra(tjd, k, raeq)
THIS SUBROUTINE COMPUTES THE INTERMEDIATE RIGHT ASCENSION OF THE EQUINOX AT JULIAN DATE TJD, USING AN ANALYTICAL EXPRESSION FOR THE ACCUMULATED PRECESSION IN RIGHT ASCENSION. FOR THE TRUE EQUINOX THE RESULT IS THE EQUATION OF THE ORIGINS.
   TJD    = TDB JULIAN DATE (IN)
   K      = EQUINOX SELECTION CODE (IN)
            SET K=0 FOR MEAN EQUINOX
            SET K=1 FOR TRUE EQUINOX (EQUATION OF THE ORIGINS)
   RADIF  = INTERMEDIATE RIGHT ASCENSION OF THE EQUINOX,
            IN HOURS (+ OR -) (OUT)
Arguments
Type Intent Optional Attributes Name
double precision :: tjd
integer :: k
double precision :: raeq
Calls
Called by
Contents
None
Call graph
eqxra calls etilt
etilt calls nod, eect2000, funarg, frame, preces, getmod
nod calls getmod, nu2000a, nu2000k
eect2000 calls anmp
nu2000k calls funarg
cioloc calls eqxra
sidtim calls eqxra, cioloc
celter calls cioloc, sidtim
place calls cioloc, geopos
gcrseq calls cioloc
ciora calls cioloc
geopos calls sidtim
tercel calls cioloc, sidtim
places calls place
mpstar calls place
zdaz calls tercel