erot – NOVAS
erot Subroutine
9 statements
Source File
public subroutine erot(date1, date2, theta)
THIS SUBROUTINE RETURNS THE VALUE OF THE EARTH ROTATION ANGLE (THETA) FOR A GIVEN UT1 JULIAN DATE. THE EXPRESSION USED IS TAKEN FROM THE NOTE TO IAU RESOLUTION B1.8 OF 2000.
  DATE1  = HIGH-ORDER PART OF UT1 JULIAN DATE (IN)
  DATE2  = LOW-ORDER PART OF UT1 JULIAN DATE (IN)
  THETA  = EARTH ROTATION ANGLE IN DEGREES (OUT)
Arguments
Type Intent Optional Attributes Name
double precision :: date1
double precision :: date2
double precision :: theta
Called by
Contents
None
Call graph
sidtim calls erot
tercel calls erot, sidtim
celter calls erot, sidtim
geopos calls sidtim
zdaz calls tercel
place calls geopos
places calls place
mpstar calls place