etilt – NOVAS
etilt Subroutine
57 statements
Source File
public subroutine etilt(tjd, oblm, oblt, eqeq, dpsi, deps)
THIS SUBROUTINE COMPUTES QUANTITIES RELATED TO THE ORIENTATION OF THE EARTH'S ROTATION AXIS AT JULIAN DATE TJD.
   TJD    = TDB JULIAN DATE FOR ORIENTATION PARAMETERS (IN)
   OBLM   = MEAN OBLIQUITY OF THE ECLIPTIC IN DEGREES AT
            DATE TJD (OUT)
   OBLT   = TRUE OBLIQUITY OF THE ECLIPTIC IN DEGREES AT
            DATE TJD (OUT)
   EQEQ   = EQUATION OF THE EQUINOXES IN TIME SECONDS AT
            DATE TJD (OUT)
   DPSI   = NUTATION IN LONGITUDE IN ARCSECONDS AT
            DATE TJD (OUT)
   DEPS   = NUTATION IN OBLIQUITY IN ARCSECONDS AT
            DATE TJD (OUT)
NOTE: THE EQUATION OF THE EQUINOXES INCLUDES THE COMPLEMENTARY TERMS.
Arguments
Type Intent Optional Attributes Name
double precision :: tjd
double precision :: oblm
double precision :: oblt
double precision :: eqeq
double precision :: dpsi
double precision :: deps
Calls
Called by
Contents
None
Call graph
etilt calls nod, eect2000, funarg, frame, preces, getmod
nod calls getmod, nu2000a, nu2000k
eect2000 calls anmp
nu2000k calls funarg
nutate calls etilt
eqec calls etilt
eceq calls etilt
geopos calls etilt, nutate, sidtim
eqxra calls etilt
sidtim calls etilt, nutate, eqxra, cioloc, ciobas
cioloc calls eqxra
celter calls nutate, sidtim, cioloc, ciobas
place calls nutate, geopos, cioloc, ciobas
ciobas calls nutate
gcrseq calls nutate, cioloc, ciobas
ciora calls nutate, cioloc, ciobas
tercel calls nutate, sidtim, cioloc, ciobas
eqecl calls eqec
places calls place
mpstar calls place
zdaz calls tercel