frame – NOVAS
frame Subroutine
33 statements
Source File
public subroutine frame(pos1, k, pos2)
THIS SUBROUTINE TRANSFORMS A VECTOR FROM THE DYNAMICAL REFERENCE SYSTEM TO THE INTERNATIONAL CELESTIAL REFERENCE SYSTEM (ICRS), OR VICE VERSA. THE DYNAMICAL REFERENCE SYSTEM IS BASED ON THE DYNAMICAL MEAN EQUATOR AND EQUINOX OF J2000.0. THE ICRS IS BASED ON THE SPACE-FIXED ICRS AXES DEFINED BY THE RADIO CATALOG POSITIONS OF SEVERAL HUNDRED EXTRAGALACTIC OBJECTS. THE ROTATION MATRIX USED HERE IS EQUIVALENT TO THAT GIVEN BY HILTON AND HOHENKERK (2004), ASTRONOMY AND ASTROPHYSICS 413, 765-770, EQ. (6) AND (8).
   POS1   = POSITION VECTOR, EQUATORIAL RECTANGULAR
            COORDINATES (IN)
   K      = DIRECTION OF ROTATION (IN)
            SET K < 0 FOR DYNAMICAL TO ICRS
            SET K > 0 FOR ICRS TO DYNAMICAL
   POS2   = POSITION VECTOR, EQUATORIAL RECTANGULAR
            COORDINATES (OUT)
NOTE: FOR GEOCENTRIC COORDINATES, THE SAME TRANSFORMATION IS USED BETWEEN THE DYNAMICAL REFERENCE SYSTEM AND THE GCRS.
Arguments
Type Intent Optional Attributes Name
double precision :: pos1
integer :: k
double precision :: pos2
Called by
Contents
None
Call graph
eqec calls frame, etilt
celter calls frame, ciobas, sidtim, nutate, cioloc
place calls frame, ciobas, geopos, nutate, cioloc
ciobas calls frame, nutate
catran calls frame
gcrseq calls frame, ciobas, nutate, cioloc
eceq calls frame, etilt
ciora calls frame, ciobas, nutate, cioloc
geopos calls frame, etilt, sidtim, nutate
etilt calls frame
sidtim calls frame, ciobas, etilt, nutate, eqxra, cioloc
tercel calls frame, ciobas, sidtim, nutate, cioloc
nutate calls etilt
mpstar calls place
places calls place
eqxra calls etilt
gethip calls catran
zdaz calls tercel
eqecl calls eqec
cioloc calls eqxra