funarg – NOVAS
funarg Subroutine
9 statements
Source File
public subroutine funarg(t, el, elp, f, d, omega)
THIS SUBROUTINE COMPUTES FUNDAMENTAL ARGUMENTS (MEAN ELEMENTS) OF THE SUN AND MOON. SEE SIMON ET AL. (1994) ASTRONOMY AND ASTROPHYSICS 282, 663-683, ESPECIALLY SECTIONS 3.4-3.5.
   T      = TDB TIME IN JULIAN CENTURIES SINCE J2000.0 (IN)
   EL     = MEAN ANOMALY OF THE MOON IN RADIANS
            AT DATE TJD (OUT)
   ELP    = MEAN ANOMALY OF THE SUN IN RADIANS
            AT DATE TJD (OUT)
   F      = MEAN LONGITUDE OF THE MOON MINUS MEAN LONGITUDE
            OF THE MOON'S ASCENDING NODE IN RADIANS
            AT DATE TJD (OUT)
   D      = MEAN ELONGATION OF THE MOON FROM THE SUN IN
            RADIANS AT DATE TJD (OUT)
   OMEGA  = MEAN LONGITUDE OF THE MOON'S ASCENDING NODE
               IN RADIANS AT DATE TJD (OUT)
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: t
real(kind=wp) :: el
real(kind=wp) :: elp
real(kind=wp) :: f
real(kind=wp) :: d
real(kind=wp) :: omega
Called by
Contents
None
Call graph
etilt calls funarg, nod
nu2000k calls funarg
geopos calls etilt, nutate, sidtim
eceq calls etilt
nutate calls etilt
nod calls nu2000k
sidtim calls etilt, nutate, eqxra, cioloc, ciobas
eqxra calls etilt
eqec calls etilt
gcrseq calls nutate, cioloc, ciobas
eqecl calls eqec
ciora calls nutate, cioloc, ciobas
cioloc calls eqxra
celter calls nutate, sidtim, cioloc, ciobas
place calls geopos, nutate, cioloc, ciobas
ciobas calls nutate
tercel calls nutate, sidtim, cioloc, ciobas
places calls place
zdaz calls tercel
mpstar calls place