gcrseq – NOVAS
gcrseq Subroutine
33 statements
Source File
public subroutine gcrseq(tjd, icoord, rag, decg, ra, dec)
THIS SUBROUTINE CONVERTS GCRS RIGHT ASCENSION AND DECLINATION TO COORDINATES WITH RESPECT TO THE EQUATOR OF DATE (MEAN OR TRUE). FOR COORDINATES WITH RESPECT TO THE TRUE EQUATOR OF DATE, THE ORIGIN OF RIGHT ASCENSION CAN BE EITHER THE TRUE EQUINOX OR THE CELESTIAL INTERMEDIATE ORIGIN (CIO).
   TJD    = TT JULIAN DATE OF EQUATOR TO BE USED FOR
            OUTPUT COORDINATES (IN)
   ICOORD = COORDINATE SYSTEM SELECTION FOR OUTPUT
            COORDINATES (IN)
            SET ICOORD=0 FOR MEAN EQUATOR AND EQUINOX OF DATE
            SET ICOORD=1 FOR TRUE EQUATOR AND EQUINOX OF DATE
            SET ICOORD=2 FOR TRUE EQUATOR AND CIO OF DATE
   RAG    = GCRS RIGHT ASCENSION IN HOURS (IN)
   DECG   = GCRS DECLINATION IN DEGREES (IN)
   RA     = RIGHT ASCENSION IN HOURS, REFERRED TO SPECIFIED
            EQUATOR AND RIGHT ASCENSION ORIGIN OF DATE (OUT)
   DEC    = DECLINATION IN DEGREES, REFERRED TO SPECIFIED
               EQUATOR OF DATE (OUT)
Arguments
Type Intent Optional Attributes Name
double precision :: tjd
integer :: icoord
double precision :: rag
double precision :: decg
double precision :: ra
double precision :: dec
Calls
Contents
None
Call graph
gcrseq calls nutate, cioloc, times, ciobas, frame, preces, angles
nutate calls etilt
cioloc calls eqxra, ciord
ciobas calls nutate, frame, preces
angles calls setvec
etilt calls frame, preces, nod, eect2000, getmod, funarg
eqxra calls etilt
nod calls getmod, nu2000a, nu2000k
eect2000 calls anmp
nu2000k calls funarg