gethip – NOVAS
gethip Subroutine
5 statements
Source File
public subroutine gethip(rah, dech, pmrah, pmdech, parxh, rvh, ra2, dec2, pmra2, pmdec2, parx2, rv2)
THIS SUBROUTINE CONVERTS HIPPARCOS DATA AT EPOCH J1991.25 TO EPOCH J2000.0. TO BE USED ONLY FOR HIPPARCOS OR TYCHO STARS WITH LINEAR SPACE MOTION. BOTH INPUT AND OUTPUT DATA IS IN THE ICRS.
   RAH    = HIPPARCOS RIGHT ASCENSION IN DEGREES (IN)
   DECH   = HIPPARCOS DECLINATION IN DEGREES (IN)
   PMRAH  = HIPPARCOS PROPER MOTION IN RA
            IN MILLIARCSECONDS/YEAR (IN)
   PMDECH = HIPPARCOS PROPER MOTION IN DEC
            IN MILLIARCSECONDS/YEAR (IN)
   PARXH  = HIPPARCOS PARALLAX IN MILLIARCSECONDS (IN)
   RVH    = RADIAL VELOCITY AT HIPPARCOS EPOCH
            IN KILOMETERS/SECOND (IN)
   RA2    = RIGHT ASCENSION AT J2000.0 IN HOURS (OUT)
   DEC2   = DECLINATION AT J2000.0 IN DEGREES (OUT)
   PMRA2  = PROPER MOTION IN RA AT J2000.0
            IN MILLIARCSECONDS/YEAR (OUT)
   PMDEC2 = PROPER MOTION IN DEC AT J2000.0
            IN MILLIARCSECONDS/YEAR (OUT)
   PARX2  = PARALLAX AT J2000.0 IN MILLIARCSECONDS (OUT)
   RV2    = RADIAL VELOCITY AT J2000.0 IN KILOMETERS/SECOND
            (OUT)
NOTE: INPUT RA IS IN DEGREES, AS PER HIPPARCOS, BUT OUTPUT RA IS IN HOURS.
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: rah
real(kind=wp) :: dech
real(kind=wp) :: pmrah
real(kind=wp) :: pmdech
real(kind=wp) :: parxh
real(kind=wp) :: rvh
real(kind=wp) :: ra2
real(kind=wp) :: dec2
real(kind=wp) :: pmra2
real(kind=wp) :: pmdec2
real(kind=wp) :: parx2
real(kind=wp) :: rv2
Calls
Contents
None
Call graph
gethip calls catran
catran calls frame, dasin, astcon, setvec, preces