grvd – NOVAS
grvd Subroutine
39 statements
Source File
public subroutine grvd(pos1, pobs, pbody, rmass, pos2)
THIS SUBROUTINE CORRECTS POSITION VECTOR FOR THE DEFLECTION OF LIGHT IN THE GRAVITATIONAL FIELD OF AN ARBITRARY BODY. ADAPTED FROM MURRAY (1981) MON. NOTICES ROYAL AST. SOCIETY 195, 639-648. SEE ALSO FORMULAE IN SECTION B OF THE ASTRONOMICAL ALMANAC, OR KAPLAN ET AL. (1989) ASTRONOMICAL JOURNAL 97, 1197-1210, SECTION III F. THIS SUBROUTINE VALID FOR AN OBSERVED BODY WITHIN THE SOLAR SYSTEM AS WELL AS FOR A STAR.
 POS1   = POSITION VECTOR OF OBSERVED OBJECT, WITH RESPECT TO
          ORIGIN AT OBSERVER (OR THE GEOCENTER), COMPONENTS
          IN AU (IN)
 POBS   = POSITION VECTOR OF OBSERVER (OR THE GEOCENTER),
          WITH RESPECT TO ORIGIN AT SOLAR SYSTEM BARYCENTER,
          COMPONENTS IN AU (IN)
 PBODY  = POSITION VECTOR OF GRAVITATING BODY, WITH RESPECT TO
          ORIGIN AT SOLAR SYSTEM BARYCENTER, COMPONENTS
          IN AU (IN)
 RMASS  = RECIPROCAL MASS OF GRAVITATING BODY IN SOLAR MASS
          UNITS, THAT IS, SUN MASS / BODY MASS (IN)
 POS2   = POSITION VECTOR OF OBSERVED OBJECT, WITH RESPECT TO
          ORIGIN AT OBSERVER (OR THE GEOCENTER), CORRECTED FOR
          GRAVITATIONAL DEFLECTION, COMPONENTS IN AU (OUT)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), dimension(3) :: pos1
real(kind=wp), dimension(3) :: pobs
real(kind=wp), dimension(3) :: pbody
real(kind=wp) :: rmass
real(kind=wp), dimension(3) :: pos2
Calls
Called by
Call graph
grvd calls astcon
grvdef calls grvd
place calls grvdef
mpstar calls place
places calls place