grvdef – NOVAS
grvdef Subroutine
39 statements
Source File
public subroutine grvdef(tjd, loc, pos1, pobs, pos2)
THIS SUBROUTINE COMPUTES THE TOTAL GRAVITATIONAL DEFLECTION OF LIGHT FOR THE OBSERVED OBJECT DUE TO THE MAJOR GRAVITATING BODIES IN THE SOLAR SYSTEM. THIS SUBROUTINE VALID FOR AN OBSERVED BODY WITHIN THE SOLAR SYSTEM AS WELL AS FOR A STAR. SEE KLIONER (2003), ASTRONOMICAL JOURNAL 125, 1580-1597, SECTION 6.
   TJD    = TDB JULIAN DATE OF OBSERVATION
   LOC    = CODE FOR LOCATION OF OBSERVER, DETERMINING
            WHETHER THE GRAVITATIONAL DEFLECTION DUE TO THE
            EARTH ITSELF IS APPLIED (IN)
            SET LOC=0 FOR NO EARTH DEFLECTION (NORMALLY MEANS
                      OBSERVER IS AT GEOCENTER)
            SET LOC=1 TO ADD IN EARTH DEFLECTION (NORMALLY
                      MEANS OBSERVER IS ON OR ABOVE SURFACE
                      OF EARTH, INCLUDING EARTH ORBIT)
   POS1   = POSITION VECTOR OF OBSERVED OBJECT, WITH RESPECT TO
            ORIGIN AT OBSERVER (OR THE GEOCENTER), REFERRED
            TO ICRS AXES, COMPONENTS IN AU (IN)
   POBS   = POSITION VECTOR OF OBSERVER (OR THE GEOCENTER),
            WITH RESPECT TO ORIGIN AT SOLAR SYSTEM BARYCENTER,
            REFERRED TO ICRS AXES, COMPONENTS IN AU (IN)
   POS2   = POSITION VECTOR OF OBSERVED OBJECT, WITH RESPECT TO
            ORIGIN AT OBSERVER (OR THE GEOCENTER), REFERRED
            TO ICRS AXES, CORRECTED FOR GRAVITATIONAL
            DEFLECTION, COMPONENTS IN AU (OUT)
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: tjd
integer :: loc
real(kind=wp) :: pos1
real(kind=wp) :: pobs
real(kind=wp) :: pos2
Calls
Called by
Contents
None
Call graph
grvdef calls id, astcon, geocen, dlight, solsys, grvd
geocen calls astcon
dlight calls astcon
solsys calls sun
grvd calls astcon
sun calls x2, x5, x3, x, x4, x1
place calls grvdef
mpstar calls place
places calls place