limang – NOVAS
limang Subroutine
30 statements
Source File
public subroutine limang(pos1, poso, alimb, afrac)
THIS FUNCTION DETERMINES THE ANGLE OF AN OBJECT ABOVE OR BELOW THE EARTH'S LIMB (HORIZON). THE GEOMETRIC LIMB IS COMPUTED, ASSUMING THE EARTH TO BE AN AIRLESS SPHERE (NO REFRACTION OR OBLATENESS IS INCLUDED). THE OBSERVER CAN BE ON OR ABOVE THE EARTH. FOR AN OBSERVER ON THE SURFACE OF THE EARTH, THIS SUBROUTINE RETURNS THE APPROXIMATE UNREFRACTED ALTITUDE.
 POS1   = POSITION VECTOR OF OBSERVED OBJECT, WITH RESPECT TO
          ORIGIN AT GEOCENTER, COMPONENTS IN AU (IN)
 POSO   = POSITION VECTOR OF OBSERVER, WITH RESPECT TO ORIGIN
          AT GEOCENTER, COMPONENTS IN AU (IN)
 ALIMB  = ANGLE OF OBSERVED OBJECT ABOVE (+) OR BELOW (-) LIMB
          IN DEGREES (OUT)
 AFRAC  = NADIR ANGLE OF OBSERVED OBJECT AS A FRACTION OF
          APPARENT RADIUS OF LIMB (OUT)
          AFRAC<1.D0 MEANS BELOW THE LIMB
          AFRAC=1.D0 MEANS ON THE LIMB
          AFRAC>1.D0 MEANS ABOVE THE LIMB
Arguments
Type Intent Optional Attributes Name
real(kind=wp), dimension(3) :: pos1
real(kind=wp), dimension(3) :: poso
real(kind=wp) :: alimb
real(kind=wp) :: afrac
Calls
Called by
Call graph
limang calls dasin, astcon
place calls limang
mpstar calls place
places calls place