littim – NOVAS
littim Subroutine
38 statements
Source File
public subroutine littim(tjd, idbody, pose, tlite, pos, tlight)
THIS SUBROUTINE COMPUTES THE POSITION OF A SOLAR SYSTEM BODY, AS ANTEDATED FOR LIGHT-TIME.
   TJD    = TDB JULIAN DATE OF OBSERVATION (IN)
   IDBODY = ID NUMBER OF BODY, USED IN CALLS TO SOLSYS (IN)
   POSE   = POSITION VECTOR OF OBSERVER (OR THE GEOCENTER),
            WITH RESPECT TO ORIGIN AT SOLAR SYSTEM BARYCENTER,
            REFERRED TO ICRS AXES, COMPONENTS IN AU (IN)
   TLITE  = FIRST APPROXIMATION TO LIGHT-TIME, IN DAYS (IN)
            (CAN BE SET TO 0.D0 IF UNKNOWN)
   POS    = POSITION VECTOR OF BODY, WITH RESPECT TO ORIGIN AT
            OBSERVER (OR THE GEOCENTER), REFERRED TO ICRS AXES,
            COMPONENTS IN AU (OUT)
   TLIGHT = FINAL LIGHT-TIME, IN DAYS (OUT)
Arguments
Type Intent Optional Attributes Name
double precision :: tjd
integer :: idbody
double precision :: pose
double precision :: tlite
double precision :: pos
double precision :: tlight
Calls
Called by
Contents
None
Call graph
littim calls solsys, geocen
solsys calls sun
geocen calls astcon
sun calls x2, x4, x1, x5, x, x3
place calls littim
places calls place
mpstar calls place