mpstar – NOVAS
mpstar Subroutine
46 statements
Source File
public subroutine mpstar(tjd, n, ra, dec, rai, deci)
THIS SUBROUTINE COMPUTES THE ICRS POSITION OF A STAR, GIVEN ITS APPARENT PLACE AT DATE TJD. PROPER MOTION, PARALLAX, AND RADIAL VELOCITY ARE ASSUMED TO BE ZERO.
  TJD    = TT JULIAN DATE OF APPARENT PLACE (IN)
  N      = BODY IDENTIFICATION NUMBER FOR THE EARTH (IN)
           (NO LONGER USED)
  RA     = APPARENT RIGHT ASCENSION IN HOURS, REFERRED TO
           TRUE EQUATOR AND EQUINOX OF DATE (IN)
  DEC    = APPARENT DECLINATION IN DEGREES, REFERRED TO
           TRUE EQUATOR OF DATE (IN)
  RAI    = ICRS RIGHT ASCENSION IN HOURS (OUT)
  DECI   = ICRS DECLINATION IN DEGREES (OUT)
Arguments
Type Intent Optional Attributes Name
double precision :: tjd
integer :: n
double precision :: ra
double precision :: dec
double precision :: rai
double precision :: deci
Calls
Contents
None
Call graph
mpstar calls angles, preces, vectrs, setvec, place
angles calls setvec
vectrs calls astcon
place calls angles, preces, setvec, geopos, frame, nutate, limang, ciobas, times, geocen, propmo, radvl, solsys, astcon, aberat, grvdef, littim, cioloc, dlight
geopos calls preces, frame, nutate, astcon, eqinox, resume, etilt, sidtim, getdt
nutate calls etilt
limang calls astcon, dasin
ciobas calls preces, frame, nutate
geocen calls astcon
radvl calls astcon
solsys calls sun
aberat calls astcon
grvdef calls geocen, solsys, astcon, dlight, grvd, id
littim calls geocen, solsys
cioloc calls eqxra, ciord
dlight calls astcon
eqxra calls etilt
etilt calls preces, frame, funarg, eect2000, getmod, nod
sidtim calls preces, frame, nutate, ciobas, times, cioloc, eqxra, etilt, getdt, erot, getmod
grvd calls astcon
sun calls x4, x2, x5, x1, x, x3
eect2000 calls anmp
nod calls getmod, nu2000k, nu2000a
nu2000k calls funarg