nod – NOVAS
nod Subroutine
16 statements
Source File
public subroutine nod(t, dpsi, deps)
THIS SUBROUTINE RETURNS THE VALUES FOR NUTATION IN LONGITUDE AND NUTATION IN OBLIQUITY FOR A GIVEN TDB JULIAN DATE.
   T     = TDB TIME IN JULIAN CENTURIES SINCE J2000.0 (IN)
   DPSI  = NUTATION IN LONGITUDE IN ARCSECONDS (OUT)
   DEPS  = NUTATION IN OBLIQUITY IN ARCSECONDS (OUT)
Arguments
Type Intent Optional Attributes Name
double precision :: t
double precision :: dpsi
double precision :: deps
Calls
Called by
Contents
Source Code
nod
Source Code
subroutine nod (t,dpsi,deps)
double precision t,dpsi,deps,pi,seccon,t0,t1,dp,de
save
parameter (pi     = 3.14159265358979324d0)
parameter (seccon = 180.d0 * 3600.d0 / pi)
!     T0 = TDB JULIAN DATE OF EPOCH J2000.0 (TT)
data t0 / 2451545.00000000d0 /
!     GET METHOD/ACCURACY MODE
call getmod (mode)
t1 = t * 36525.d0
!     =================================================================
!     EVALUATE NUTATION SERIES
!     RESULTING NUTATION IN LONGITUDE AND OBLIQUITY IN ARCSECONDS
!     CALL SUBROUTINE TO EVALUATE NUTATION SERIES
if (mod (mode, 2) == 0) then
!         HIGH ACCURACY MODE -- IERS SUBROUTINE
    call nu2000a ( t0, t1, dp, de )
else
!         LOW ACCURACY MODE -- MODIFICATION OF IERS SUBROUTINE
    call nu2000k ( t0, t1, dp, de )
end if
dpsi = dp * seccon
deps = de * seccon
end subroutine nod
Call graph
nod calls nu2000a, nu2000k, getmod
nu2000k calls funarg
etilt calls nod
nutate calls etilt
eqec calls etilt
eceq calls etilt
geopos calls etilt, nutate, sidtim
eqxra calls etilt
sidtim calls etilt, nutate, eqxra, cioloc, ciobas
cioloc calls eqxra
celter calls nutate, sidtim, cioloc, ciobas
place calls nutate, geopos, cioloc, ciobas
ciobas calls nutate
gcrseq calls nutate, cioloc, ciobas
ciora calls nutate, cioloc, ciobas
tercel calls nutate, sidtim, cioloc, ciobas
eqecl calls eqec
places calls place
mpstar calls place
zdaz calls tercel