nod – NOVAS
nod Subroutine
15 statements
Source File
public subroutine nod(t, dpsi, deps)
This subroutine returns the values for nutation in longitude and nutation in obliquity for a given TDB Julian date.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: t
tdb time in julian centuries since j2000.0
real(kind=wp), intent(out) :: dpsi
nutation in longitude in arcseconds
real(kind=wp), intent(out) :: deps
nutation in obliquity in arcseconds
Calls
Called by
Contents
Source Code
nod
Source Code
    subroutine nod (t,dpsi,deps)
    real(wp),intent(in) :: t !! tdb time in julian centuries since j2000.0
    real(wp),intent(out) :: dpsi !! nutation in longitude in arcseconds
    real(wp),intent(out) :: deps !! nutation in obliquity in arcseconds
    real(wp) :: t1,dp,de
    ! get method/accuracy mode
    call getmod ( mode )
    t1 = t * 36525.0_wp
    ! evaluate nutation series
    ! resulting nutation in longitude and obliquity in arcseconds
    ! call subroutine to evaluate nutation series
    if ( mod ( mode, 2 ) == 0 ) then
        ! high accuracy mode -- iers subroutine
        call nu2000a ( jd_j2000, t1, dp, de )
    else
        ! low accuracy mode -- modification of iers subroutine
        call nu2000k ( jd_j2000, t1, dp, de )
    end if
    dpsi = dp * seccon
    deps = de * seccon
    end subroutine nod
Call graph
nod calls nu2000a, nu2000k, getmod
nu2000k calls funarg
etilt calls nod
eqec calls etilt
geopos calls etilt, nutate, sidtim
nutate calls etilt
sidtim calls etilt, nutate, eqxra, ciobas, cioloc
eceq calls etilt
eqxra calls etilt
place calls geopos, nutate, ciobas, cioloc
celter calls nutate, sidtim, ciobas, cioloc
tercel calls nutate, sidtim, ciobas, cioloc
gcrseq calls nutate, ciobas, cioloc
ciobas calls nutate
ciora calls nutate, ciobas, cioloc
eqecl calls eqec
cioloc calls eqxra
zdaz calls tercel
places calls place
mpstar calls place