nu2000a – NOVAS
nu2000a Subroutine
346 statements
Source File
public subroutine nu2000a(date1, date2, dpsi, deps)
Nutation, IAU 2000A model (MHB_2000 without FCN).
Annexe to IERS Conventions 2000, Chapter 5
Given: DATE1,DATE2 d TT date (JD = DATE1+DATE2)
Returned: DPSI,DEPS d nutation (luni-solar + planetary, radians)
This revision: 2002 November 25
Arguments
Type Intent Optional Attributes Name
double precision :: date1
double precision :: date2
double precision :: dpsi
double precision :: deps
Called by
Contents
Source Code
nu2000a
Source Code
subroutine nu2000a (date1, date2, dpsi, deps)
implicit none
double precision date1, date2, dpsi, deps
!  Arcseconds to radians
double precision das2r
parameter (das2r = 4.848136811095359935899141d-6)
!  Milliarcseconds to radians
double precision dmas2r
parameter (dmas2r = das2r / 1d3)
!  Arc seconds in a full circle
double precision turnas
parameter (turnas = 1296000d0)
!  2Pi
double precision d2pi
parameter (d2pi = 6.283185307179586476925287d0)
!  Units of 0.1 microarcsecond to radians
double precision u2r
parameter (u2r = das2r/1d7)
!  Reference epoch (J2000), JD
double precision dj0
parameter (dj0 = 2451545d0)
!  Days per Julian century
double precision djc
parameter (djc = 36525d0)
!  Miscellaneous
double precision t, el, elp, f, d, om, arg, dp, de, sarg, carg, &
                 dpsils, depsls, &
                 al, alsu, af, ad, aom, alme, alve, alea, alma, &
                 alju, alsa, alur, alne, apa, dpsipl, depspl
integer i, j
!  -------------------------
!  Luni-Solar nutation model
!  -------------------------
!  Number of terms in the luni-solar nutation model
integer nls
parameter (nls = 678)
!  Coefficients for fundamental arguments
integer nals(5,nls)
!  Longitude and obliquity coefficients
double precision cls(6,nls)
!  ---------------
!  Planetary terms
!  ---------------
!  Number of terms in the planetary nutation model
integer npl
parameter (npl = 687)
!  Coefficients for fundamental arguments
integer napl(14,npl)
!  Longitude and obliquity coefficients
integer icpl(4,npl)
!  ----------------------------------------
!  Tables of argument and term coefficients
!  ----------------------------------------
!
!  Luni-Solar argument multipliers:
!               L     L'    F     D     Om
data ((nals(i,j), i=1,5), j=  1, 10) / &
          0,    0,    0,    0,    1, &
          0,    0,    2,   -2,    2, &
          0,    0,    2,    0,    2, &
          0,    0,    0,    0,    2, &
          0,    1,    0,    0,    0, &
          0,    1,    2,   -2,    2, &
          1,    0,    0,    0,    0, &
          0,    0,    2,    0,    1, &
          1,    0,    2,    0,    2, &
          0,   -1,    2,   -2,    2 /
data ((nals(i,j), i=1,5), j= 11, 20) / &
          0,    0,    2,   -2,    1, &
         -1,    0,    2,    0,    2, &
         -1,    0,    0,    2,    0, &
          1,    0,    0,    0,    1, &
         -1,    0,    0,    0,    1, &
         -1,    0,    2,    2,    2, &
          1,    0,    2,    0,    1, &
         -2,    0,    2,    0,    1, &
          0,    0,    0,    2,    0, &
          0,    0,    2,    2,    2 /
data ((nals(i,j), i=1,5), j= 21, 30) / &
          0,   -2,    2,   -2,    2, &
         -2,    0,    0,    2,    0, &
          2,    0,    2,    0,    2, &
          1,    0,    2,   -2,    2, &
         -1,    0,    2,    0,    1, &
          2,    0,    0,    0,    0, &
          0,    0,    2,    0,    0, &
          0,    1,    0,    0,    1, &
         -1,    0,    0,    2,    1, &
          0,    2,    2,   -2,    2 /
data ((nals(i,j), i=1,5), j= 31, 40) / &
          0,    0,   -2,    2,    0, &
          1,    0,    0,   -2,    1, &
          0,   -1,    0,    0,    1, &
         -1,    0,    2,    2,    1, &
          0,    2,    0,    0,    0, &
          1,    0,    2,    2,    2, &
         -2,    0,    2,    0,    0, &
          0,    1,    2,    0,    2, &
          0,    0,    2,    2,    1, &
          0,   -1,    2,    0,    2 /
data ((nals(i,j), i=1,5), j= 41, 50) / &
          0,    0,    0,    2,    1, &
          1,    0,    2,   -2,    1, &
          2,    0,    2,   -2,    2, &
         -2,    0,    0,    2,    1, &
          2,    0,    2,    0,    1, &
          0,   -1,    2,   -2,    1, &
          0,    0,    0,   -2,    1, &
         -1,   -1,    0,    2,    0, &
          2,    0,    0,   -2,    1, &
          1,    0,    0,    2,    0 /
data ((nals(i,j), i=1,5), j= 51, 60) / &
          0,    1,    2,   -2,    1, &
          1,   -1,    0,    0,    0, &
         -2,    0,    2,    0,    2, &
          3,    0,    2,    0,    2, &
          0,   -1,    0,    2,    0, &
          1,   -1,    2,    0,    2, &
          0,    0,    0,    1,    0, &
         -1,   -1,    2,    2,    2, &
         -1,    0,    2,    0,    0, &
          0,   -1,    2,    2,    2 /
data ((nals(i,j), i=1,5), j= 61, 70) / &
         -2,    0,    0,    0,    1, &
          1,    1,    2,    0,    2, &
          2,    0,    0,    0,    1, &
         -1,    1,    0,    1,    0, &
          1,    1,    0,    0,    0, &
          1,    0,    2,    0,    0, &
         -1,    0,    2,   -2,    1, &
          1,    0,    0,    0,    2, &
         -1,    0,    0,    1,    0, &
          0,    0,    2,    1,    2 /
data ((nals(i,j), i=1,5), j= 71, 80) / &
         -1,    0,    2,    4,    2, &
         -1,    1,    0,    1,    1, &
          0,   -2,    2,   -2,    1, &
          1,    0,    2,    2,    1, &
         -2,    0,    2,    2,    2, &
         -1,    0,    0,    0,    2, &
          1,    1,    2,   -2,    2, &
         -2,    0,    2,    4,    2, &
         -1,    0,    4,    0,    2, &
          2,    0,    2,   -2,    1 /
data ((nals(i,j), i=1,5), j= 81, 90) / &
          2,    0,    2,    2,    2, &
          1,    0,    0,    2,    1, &
          3,    0,    0,    0,    0, &
          3,    0,    2,   -2,    2, &
          0,    0,    4,   -2,    2, &
          0,    1,    2,    0,    1, &
          0,    0,   -2,    2,    1, &
          0,    0,    2,   -2,    3, &
         -1,    0,    0,    4,    0, &
          2,    0,   -2,    0,    1 /
data ((nals(i,j), i=1,5), j= 91,100) / &
         -2,    0,    0,    4,    0, &
         -1,   -1,    0,    2,    1, &
         -1,    0,    0,    1,    1, &
          0,    1,    0,    0,    2, &
          0,    0,   -2,    0,    1, &
          0,   -1,    2,    0,    1, &
          0,    0,    2,   -1,    2, &
          0,    0,    2,    4,    2, &
         -2,   -1,    0,    2,    0, &
          1,    1,    0,   -2,    1 /
data ((nals(i,j), i=1,5), j=101,110) / &
         -1,    1,    0,    2,    0, &
         -1,    1,    0,    1,    2, &
          1,   -1,    0,    0,    1, &
          1,   -1,    2,    2,    2, &
         -1,    1,    2,    2,    2, &
          3,    0,    2,    0,    1, &
          0,    1,   -2,    2,    0, &
         -1,    0,    0,   -2,    1, &
          0,    1,    2,    2,    2, &
         -1,   -1,    2,    2,    1 /
data ((nals(i,j), i=1,5), j=111,120) / &
          0,   -1,    0,    0,    2, &
          1,    0,    2,   -4,    1, &
         -1,    0,   -2,    2,    0, &
          0,   -1,    2,    2,    1, &
          2,   -1,    2,    0,    2, &
          0,    0,    0,    2,    2, &
          1,   -1,    2,    0,    1, &
         -1,    1,    2,    0,    2, &
          0,    1,    0,    2,    0, &
          0,   -1,   -2,    2,    0 /
data ((nals(i,j), i=1,5), j=121,130) / &
          0,    3,    2,   -2,    2, &
          0,    0,    0,    1,    1, &
         -1,    0,    2,    2,    0, &
          2,    1,    2,    0,    2, &
          1,    1,    0,    0,    1, &
          1,    1,    2,    0,    1, &
          2,    0,    0,    2,    0, &
          1,    0,   -2,    2,    0, &
         -1,    0,    0,    2,    2, &
          0,    1,    0,    1,    0 /
data ((nals(i,j), i=1,5), j=131,140) / &
          0,    1,    0,   -2,    1, &
         -1,    0,    2,   -2,    2, &
          0,    0,    0,   -1,    1, &
         -1,    1,    0,    0,    1, &
          1,    0,    2,   -1,    2, &
          1,   -1,    0,    2,    0, &
          0,    0,    0,    4,    0, &
          1,    0,    2,    1,    2, &
          0,    0,    2,    1,    1, &
          1,    0,    0,   -2,    2 /
data ((nals(i,j), i=1,5), j=141,150) / &
         -1,    0,    2,    4,    1, &
          1,    0,   -2,    0,    1, &
          1,    1,    2,   -2,    1, &
          0,    0,    2,    2,    0, &
         -1,    0,    2,   -1,    1, &
         -2,    0,    2,    2,    1, &
          4,    0,    2,    0,    2, &
          2,   -1,    0,    0,    0, &
          2,    1,    2,   -2,    2, &
          0,    1,    2,    1,    2 /
data ((nals(i,j), i=1,5), j=151,160) / &
          1,    0,    4,   -2,    2, &
         -1,   -1,    0,    0,    1, &
          0,    1,    0,    2,    1, &
         -2,    0,    2,    4,    1, &
          2,    0,    2,    0,    0, &
          1,    0,    0,    1,    0, &
         -1,    0,    0,    4,    1, &
         -1,    0,    4,    0,    1, &
          2,    0,    2,    2,    1, &
          0,    0,    2,   -3,    2 /
data ((nals(i,j), i=1,5), j=161,170) / &
         -1,   -2,    0,    2,    0, &
          2,    1,    0,    0,    0, &
          0,    0,    4,    0,    2, &
          0,    0,    0,    0,    3, &
          0,    3,    0,    0,    0, &
          0,    0,    2,   -4,    1, &
          0,   -1,    0,    2,    1, &
          0,    0,    0,    4,    1, &
         -1,   -1,    2,    4,    2, &
          1,    0,    2,    4,    2 /
data ((nals(i,j), i=1,5), j=171,180) / &
         -2,    2,    0,    2,    0, &
         -2,   -1,    2,    0,    1, &
         -2,    0,    0,    2,    2, &
         -1,   -1,    2,    0,    2, &
          0,    0,    4,   -2,    1, &
          3,    0,    2,   -2,    1, &
         -2,   -1,    0,    2,    1, &
          1,    0,    0,   -1,    1, &
          0,   -2,    0,    2,    0, &
         -2,    0,    0,    4,    1 /
data ((nals(i,j), i=1,5), j=181,190) / &
         -3,    0,    0,    0,    1, &
          1,    1,    2,    2,    2, &
          0,    0,    2,    4,    1, &
          3,    0,    2,    2,    2, &
         -1,    1,    2,   -2,    1, &
          2,    0,    0,   -4,    1, &
          0,    0,    0,   -2,    2, &
          2,    0,    2,   -4,    1, &
         -1,    1,    0,    2,    1, &
          0,    0,    2,   -1,    1 /
data ((nals(i,j), i=1,5), j=191,200) / &
          0,   -2,    2,    2,    2, &
          2,    0,    0,    2,    1, &
          4,    0,    2,   -2,    2, &
          2,    0,    0,   -2,    2, &
          0,    2,    0,    0,    1, &
          1,    0,    0,   -4,    1, &
          0,    2,    2,   -2,    1, &
         -3,    0,    0,    4,    0, &
         -1,    1,    2,    0,    1, &
         -1,   -1,    0,    4,    0 /
data ((nals(i,j), i=1,5), j=201,210) / &
         -1,   -2,    2,    2,    2, &
         -2,   -1,    2,    4,    2, &
          1,   -1,    2,    2,    1, &
         -2,    1,    0,    2,    0, &
         -2,    1,    2,    0,    1, &
          2,    1,    0,   -2,    1, &
         -3,    0,    2,    0,    1, &
         -2,    0,    2,   -2,    1, &
         -1,    1,    0,    2,    2, &
          0,   -1,    2,   -1,    2 /
data ((nals(i,j), i=1,5), j=211,220) / &
         -1,    0,    4,   -2,    2, &
          0,   -2,    2,    0,    2, &
         -1,    0,    2,    1,    2, &
          2,    0,    0,    0,    2, &
          0,    0,    2,    0,    3, &
         -2,    0,    4,    0,    2, &
         -1,    0,   -2,    0,    1, &
         -1,    1,    2,    2,    1, &
          3,    0,    0,    0,    1, &
         -1,    0,    2,    3,    2 /
data ((nals(i,j), i=1,5), j=221,230) / &
          2,   -1,    2,    0,    1, &
          0,    1,    2,    2,    1, &
          0,   -1,    2,    4,    2, &
          2,   -1,    2,    2,    2, &
          0,    2,   -2,    2,    0, &
         -1,   -1,    2,   -1,    1, &
          0,   -2,    0,    0,    1, &
          1,    0,    2,   -4,    2, &
          1,   -1,    0,   -2,    1, &
         -1,   -1,    2,    0,    1 /
data ((nals(i,j), i=1,5), j=231,240) / &
          1,   -1,    2,   -2,    2, &
         -2,   -1,    0,    4,    0, &
         -1,    0,    0,    3,    0, &
         -2,   -1,    2,    2,    2, &
          0,    2,    2,    0,    2, &
          1,    1,    0,    2,    0, &
          2,    0,    2,   -1,    2, &
          1,    0,    2,    1,    1, &
          4,    0,    0,    0,    0, &
          2,    1,    2,    0,    1 /
data ((nals(i,j), i=1,5), j=241,250) / &
          3,   -1,    2,    0,    2, &
         -2,    2,    0,    2,    1, &
          1,    0,    2,   -3,    1, &
          1,    1,    2,   -4,    1, &
         -1,   -1,    2,   -2,    1, &
          0,   -1,    0,   -1,    1, &
          0,   -1,    0,   -2,    1, &
         -2,    0,    0,    0,    2, &
         -2,    0,   -2,    2,    0, &
         -1,    0,   -2,    4,    0 /
data ((nals(i,j), i=1,5), j=251,260) / &
          1,   -2,    0,    0,    0, &
          0,    1,    0,    1,    1, &
         -1,    2,    0,    2,    0, &
          1,   -1,    2,   -2,    1, &
          1,    2,    2,   -2,    2, &
          2,   -1,    2,   -2,    2, &
          1,    0,    2,   -1,    1, &
          2,    1,    2,   -2,    1, &
         -2,    0,    0,   -2,    1, &
          1,   -2,    2,    0,    2 /
data ((nals(i,j), i=1,5), j=261,270) / &
          0,    1,    2,    1,    1, &
          1,    0,    4,   -2,    1, &
         -2,    0,    4,    2,    2, &
          1,    1,    2,    1,    2, &
          1,    0,    0,    4,    0, &
          1,    0,    2,    2,    0, &
          2,    0,    2,    1,    2, &
          3,    1,    2,    0,    2, &
          4,    0,    2,    0,    1, &
         -2,   -1,    2,    0,    0 /
data ((nals(i,j), i=1,5), j=271,280) / &
          0,    1,   -2,    2,    1, &
          1,    0,   -2,    1,    0, &
          0,   -1,   -2,    2,    1, &
          2,   -1,    0,   -2,    1, &
         -1,    0,    2,   -1,    2, &
          1,    0,    2,   -3,    2, &
          0,    1,    2,   -2,    3, &
          0,    0,    2,   -3,    1, &
         -1,    0,   -2,    2,    1, &
          0,    0,    2,   -4,    2 /
data ((nals(i,j), i=1,5), j=281,290) / &
         -2,    1,    0,    0,    1, &
         -1,    0,    0,   -1,    1, &
          2,    0,    2,   -4,    2, &
          0,    0,    4,   -4,    4, &
          0,    0,    4,   -4,    2, &
         -1,   -2,    0,    2,    1, &
         -2,    0,    0,    3,    0, &
          1,    0,   -2,    2,    1, &
         -3,    0,    2,    2,    2, &
         -3,    0,    2,    2,    1 /
data ((nals(i,j), i=1,5), j=291,300) / &
         -2,    0,    2,    2,    0, &
          2,   -1,    0,    0,    1, &
         -2,    1,    2,    2,    2, &
          1,    1,    0,    1,    0, &
          0,    1,    4,   -2,    2, &
         -1,    1,    0,   -2,    1, &
          0,    0,    0,   -4,    1, &
          1,   -1,    0,    2,    1, &
          1,    1,    0,    2,    1, &
         -1,    2,    2,    2,    2 /
data ((nals(i,j), i=1,5), j=301,310) / &
          3,    1,    2,   -2,    2, &
          0,   -1,    0,    4,    0, &
          2,   -1,    0,    2,    0, &
          0,    0,    4,    0,    1, &
          2,    0,    4,   -2,    2, &
         -1,   -1,    2,    4,    1, &
          1,    0,    0,    4,    1, &
          1,   -2,    2,    2,    2, &
          0,    0,    2,    3,    2, &
         -1,    1,    2,    4,    2 /
data ((nals(i,j), i=1,5), j=311,320) / &
          3,    0,    0,    2,    0, &
         -1,    0,    4,    2,    2, &
          1,    1,    2,    2,    1, &
         -2,    0,    2,    6,    2, &
          2,    1,    2,    2,    2, &
         -1,    0,    2,    6,    2, &
          1,    0,    2,    4,    1, &
          2,    0,    2,    4,    2, &
          1,    1,   -2,    1,    0, &
         -3,    1,    2,    1,    2 /
data ((nals(i,j), i=1,5), j=321,330) / &
          2,    0,   -2,    0,    2, &
         -1,    0,    0,    1,    2, &
         -4,    0,    2,    2,    1, &
         -1,   -1,    0,    1,    0, &
          0,    0,   -2,    2,    2, &
          1,    0,    0,   -1,    2, &
          0,   -1,    2,   -2,    3, &
         -2,    1,    2,    0,    0, &
          0,    0,    2,   -2,    4, &
         -2,   -2,    0,    2,    0 /
data ((nals(i,j), i=1,5), j=331,340) / &
         -2,    0,   -2,    4,    0, &
          0,   -2,   -2,    2,    0, &
          1,    2,    0,   -2,    1, &
          3,    0,    0,   -4,    1, &
         -1,    1,    2,   -2,    2, &
          1,   -1,    2,   -4,    1, &
          1,    1,    0,   -2,    2, &
         -3,    0,    2,    0,    0, &
         -3,    0,    2,    0,    2, &
         -2,    0,    0,    1,    0 /
data ((nals(i,j), i=1,5), j=341,350) / &
          0,    0,   -2,    1,    0, &
         -3,    0,    0,    2,    1, &
         -1,   -1,   -2,    2,    0, &
          0,    1,    2,   -4,    1, &
          2,    1,    0,   -4,    1, &
          0,    2,    0,   -2,    1, &
          1,    0,    0,   -3,    1, &
         -2,    0,    2,   -2,    2, &
         -2,   -1,    0,    0,    1, &
         -4,    0,    0,    2,    0 /
data ((nals(i,j), i=1,5), j=351,360) / &
          1,    1,    0,   -4,    1, &
         -1,    0,    2,   -4,    1, &
          0,    0,    4,   -4,    1, &
          0,    3,    2,   -2,    2, &
         -3,   -1,    0,    4,    0, &
         -3,    0,    0,    4,    1, &
          1,   -1,   -2,    2,    0, &
         -1,   -1,    0,    2,    2, &
          1,   -2,    0,    0,    1, &
          1,   -1,    0,    0,    2 /
data ((nals(i,j), i=1,5), j=361,370) / &
          0,    0,    0,    1,    2, &
         -1,   -1,    2,    0,    0, &
          1,   -2,    2,   -2,    2, &
          0,   -1,    2,   -1,    1, &
         -1,    0,    2,    0,    3, &
          1,    1,    0,    0,    2, &
         -1,    1,    2,    0,    0, &
          1,    2,    0,    0,    0, &
         -1,    2,    2,    0,    2, &
         -1,    0,    4,   -2,    1 /
data ((nals(i,j), i=1,5), j=371,380) / &
          3,    0,    2,   -4,    2, &
          1,    2,    2,   -2,    1, &
          1,    0,    4,   -4,    2, &
         -2,   -1,    0,    4,    1, &
          0,   -1,    0,    2,    2, &
         -2,    1,    0,    4,    0, &
         -2,   -1,    2,    2,    1, &
          2,    0,   -2,    2,    0, &
          1,    0,    0,    1,    1, &
          0,    1,    0,    2,    2 /
data ((nals(i,j), i=1,5), j=381,390) / &
          1,   -1,    2,   -1,    2, &
         -2,    0,    4,    0,    1, &
          2,    1,    0,    0,    1, &
          0,    1,    2,    0,    0, &
          0,   -1,    4,   -2,    2, &
          0,    0,    4,   -2,    4, &
          0,    2,    2,    0,    1, &
         -3,    0,    0,    6,    0, &
         -1,   -1,    0,    4,    1, &
          1,   -2,    0,    2,    0 /
data ((nals(i,j), i=1,5), j=391,400) / &
         -1,    0,    0,    4,    2, &
         -1,   -2,    2,    2,    1, &
         -1,    0,    0,   -2,    2, &
          1,    0,   -2,   -2,    1, &
          0,    0,   -2,   -2,    1, &
         -2,    0,   -2,    0,    1, &
          0,    0,    0,    3,    1, &
          0,    0,    0,    3,    0, &
         -1,    1,    0,    4,    0, &
         -1,   -1,    2,    2,    0 /
data ((nals(i,j), i=1,5), j=401,410) / &
         -2,    0,    2,    3,    2, &
          1,    0,    0,    2,    2, &
          0,   -1,    2,    1,    2, &
          3,   -1,    0,    0,    0, &
          2,    0,    0,    1,    0, &
          1,   -1,    2,    0,    0, &
          0,    0,    2,    1,    0, &
          1,    0,    2,    0,    3, &
          3,    1,    0,    0,    0, &
          3,   -1,    2,   -2,    2 /
data ((nals(i,j), i=1,5), j=411,420) / &
          2,    0,    2,   -1,    1, &
          1,    1,    2,    0,    0, &
          0,    0,    4,   -1,    2, &
          1,    2,    2,    0,    2, &
         -2,    0,    0,    6,    0, &
          0,   -1,    0,    4,    1, &
         -2,   -1,    2,    4,    1, &
          0,   -2,    2,    2,    1, &
          0,   -1,    2,    2,    0, &
         -1,    0,    2,    3,    1 /
data ((nals(i,j), i=1,5), j=421,430) / &
         -2,    1,    2,    4,    2, &
          2,    0,    0,    2,    2, &
          2,   -2,    2,    0,    2, &
         -1,    1,    2,    3,    2, &
          3,    0,    2,   -1,    2, &
          4,    0,    2,   -2,    1, &
         -1,    0,    0,    6,    0, &
         -1,   -2,    2,    4,    2, &
         -3,    0,    2,    6,    2, &
         -1,    0,    2,    4,    0 /
data ((nals(i,j), i=1,5), j=431,440) / &
          3,    0,    0,    2,    1, &
          3,   -1,    2,    0,    1, &
          3,    0,    2,    0,    0, &
          1,    0,    4,    0,    2, &
          5,    0,    2,   -2,    2, &
          0,   -1,    2,    4,    1, &
          2,   -1,    2,    2,    1, &
          0,    1,    2,    4,    2, &
          1,   -1,    2,    4,    2, &
          3,   -1,    2,    2,    2 /
data ((nals(i,j), i=1,5), j=441,450) / &
          3,    0,    2,    2,    1, &
          5,    0,    2,    0,    2, &
          0,    0,    2,    6,    2, &
          4,    0,    2,    2,    2, &
          0,   -1,    1,   -1,    1, &
         -1,    0,    1,    0,    3, &
          0,   -2,    2,   -2,    3, &
          1,    0,   -1,    0,    1, &
          2,   -2,    0,   -2,    1, &
         -1,    0,    1,    0,    2 /
data ((nals(i,j), i=1,5), j=451,460) / &
         -1,    0,    1,    0,    1, &
         -1,   -1,    2,   -1,    2, &
         -2,    2,    0,    2,    2, &
         -1,    0,    1,    0,    0, &
         -4,    1,    2,    2,    2, &
         -3,    0,    2,    1,    1, &
         -2,   -1,    2,    0,    2, &
          1,    0,   -2,    1,    1, &
          2,   -1,   -2,    0,    1, &
         -4,    0,    2,    2,    0 /
data ((nals(i,j), i=1,5), j=461,470) / &
         -3,    1,    0,    3,    0, &
         -1,    0,   -1,    2,    0, &
          0,   -2,    0,    0,    2, &
          0,   -2,    0,    0,    2, &
         -3,    0,    0,    3,    0, &
         -2,   -1,    0,    2,    2, &
         -1,    0,   -2,    3,    0, &
         -4,    0,    0,    4,    0, &
          2,    1,   -2,    0,    1, &
          2,   -1,    0,   -2,    2 /
data ((nals(i,j), i=1,5), j=471,480) / &
          0,    0,    1,   -1,    0, &
         -1,    2,    0,    1,    0, &
         -2,    1,    2,    0,    2, &
          1,    1,    0,   -1,    1, &
          1,    0,    1,   -2,    1, &
          0,    2,    0,    0,    2, &
          1,   -1,    2,   -3,    1, &
         -1,    1,    2,   -1,    1, &
         -2,    0,    4,   -2,    2, &
         -2,    0,    4,   -2,    1 /
data ((nals(i,j), i=1,5), j=481,490) / &
         -2,   -2,    0,    2,    1, &
         -2,    0,   -2,    4,    0, &
          1,    2,    2,   -4,    1, &
          1,    1,    2,   -4,    2, &
         -1,    2,    2,   -2,    1, &
          2,    0,    0,   -3,    1, &
         -1,    2,    0,    0,    1, &
          0,    0,    0,   -2,    0, &
         -1,   -1,    2,   -2,    2, &
         -1,    1,    0,    0,    2 /
data ((nals(i,j), i=1,5), j=491,500) / &
          0,    0,    0,   -1,    2, &
         -2,    1,    0,    1,    0, &
          1,   -2,    0,   -2,    1, &
          1,    0,   -2,    0,    2, &
         -3,    1,    0,    2,    0, &
         -1,    1,   -2,    2,    0, &
         -1,   -1,    0,    0,    2, &
         -3,    0,    0,    2,    0, &
         -3,   -1,    0,    2,    0, &
          2,    0,    2,   -6,    1 /
data ((nals(i,j), i=1,5), j=501,510) / &
          0,    1,    2,   -4,    2, &
          2,    0,    0,   -4,    2, &
         -2,    1,    2,   -2,    1, &
          0,   -1,    2,   -4,    1, &
          0,    1,    0,   -2,    2, &
         -1,    0,    0,   -2,    0, &
          2,    0,   -2,   -2,    1, &
         -4,    0,    2,    0,    1, &
         -1,   -1,    0,   -1,    1, &
          0,    0,   -2,    0,    2 /
data ((nals(i,j), i=1,5), j=511,520) / &
         -3,    0,    0,    1,    0, &
         -1,    0,   -2,    1,    0, &
         -2,    0,   -2,    2,    1, &
          0,    0,   -4,    2,    0, &
         -2,   -1,   -2,    2,    0, &
          1,    0,    2,   -6,    1, &
         -1,    0,    2,   -4,    2, &
          1,    0,    0,   -4,    2, &
          2,    1,    2,   -4,    2, &
          2,    1,    2,   -4,    1 /
data ((nals(i,j), i=1,5), j=521,530) / &
          0,    1,    4,   -4,    4, &
          0,    1,    4,   -4,    2, &
         -1,   -1,   -2,    4,    0, &
         -1,   -3,    0,    2,    0, &
         -1,    0,   -2,    4,    1, &
         -2,   -1,    0,    3,    0, &
          0,    0,   -2,    3,    0, &
         -2,    0,    0,    3,    1, &
          0,   -1,    0,    1,    0, &
         -3,    0,    2,    2,    0 /
data ((nals(i,j), i=1,5), j=531,540) / &
          1,    1,   -2,    2,    0, &
         -1,    1,    0,    2,    2, &
          1,   -2,    2,   -2,    1, &
          0,    0,    1,    0,    2, &
          0,    0,    1,    0,    1, &
          0,    0,    1,    0,    0, &
         -1,    2,    0,    2,    1, &
          0,    0,    2,    0,    2, &
         -2,    0,    2,    0,    2, &
          2,    0,    0,   -1,    1 /
data ((nals(i,j), i=1,5), j=541,550) / &
          3,    0,    0,   -2,    1, &
          1,    0,    2,   -2,    3, &
          1,    2,    0,    0,    1, &
          2,    0,    2,   -3,    2, &
         -1,    1,    4,   -2,    2, &
         -2,   -2,    0,    4,    0, &
          0,   -3,    0,    2,    0, &
          0,    0,   -2,    4,    0, &
         -1,   -1,    0,    3,    0, &
         -2,    0,    0,    4,    2 /
data ((nals(i,j), i=1,5), j=551,560) / &
         -1,    0,    0,    3,    1, &
          2,   -2,    0,    0,    0, &
          1,   -1,    0,    1,    0, &
         -1,    0,    0,    2,    0, &
          0,   -2,    2,    0,    1, &
         -1,    0,    1,    2,    1, &
         -1,    1,    0,    3,    0, &
         -1,   -1,    2,    1,    2, &
          0,   -1,    2,    0,    0, &
         -2,    1,    2,    2,    1 /
data ((nals(i,j), i=1,5), j=561,570) / &
          2,   -2,    2,   -2,    2, &
          1,    1,    0,    1,    1, &
          1,    0,    1,    0,    1, &
          1,    0,    1,    0,    0, &
          0,    2,    0,    2,    0, &
          2,   -1,    2,   -2,    1, &
          0,   -1,    4,   -2,    1, &
          0,    0,    4,   -2,    3, &
          0,    1,    4,   -2,    1, &
          4,    0,    2,   -4,    2 /
data ((nals(i,j), i=1,5), j=571,580) / &
          2,    2,    2,   -2,    2, &
          2,    0,    4,   -4,    2, &
         -1,   -2,    0,    4,    0, &
         -1,   -3,    2,    2,    2, &
         -3,    0,    2,    4,    2, &
         -3,    0,    2,   -2,    1, &
         -1,   -1,    0,   -2,    1, &
         -3,    0,    0,    0,    2, &
         -3,    0,   -2,    2,    0, &
          0,    1,    0,   -4,    1 /
data ((nals(i,j), i=1,5), j=581,590) / &
         -2,    1,    0,   -2,    1, &
         -4,    0,    0,    0,    1, &
         -1,    0,    0,   -4,    1, &
         -3,    0,    0,   -2,    1, &
          0,    0,    0,    3,    2, &
         -1,    1,    0,    4,    1, &
          1,   -2,    2,    0,    1, &
          0,    1,    0,    3,    0, &
         -1,    0,    2,    2,    3, &
          0,    0,    2,    2,    2 /
data ((nals(i,j), i=1,5), j=591,600) / &
         -2,    0,    2,    2,    2, &
         -1,    1,    2,    2,    0, &
          3,    0,    0,    0,    2, &
          2,    1,    0,    1,    0, &
          2,   -1,    2,   -1,    2, &
          0,    0,    2,    0,    1, &
          0,    0,    3,    0,    3, &
          0,    0,    3,    0,    2, &
         -1,    2,    2,    2,    1, &
         -1,    0,    4,    0,    0 /
data ((nals(i,j), i=1,5), j=601,610) / &
          1,    2,    2,    0,    1, &
          3,    1,    2,   -2,    1, &
          1,    1,    4,   -2,    2, &
         -2,   -1,    0,    6,    0, &
          0,   -2,    0,    4,    0, &
         -2,    0,    0,    6,    1, &
         -2,   -2,    2,    4,    2, &
          0,   -3,    2,    2,    2, &
          0,    0,    0,    4,    2, &
         -1,   -1,    2,    3,    2 /
data ((nals(i,j), i=1,5), j=611,620) / &
         -2,    0,    2,    4,    0, &
          2,   -1,    0,    2,    1, &
          1,    0,    0,    3,    0, &
          0,    1,    0,    4,    1, &
          0,    1,    0,    4,    0, &
          1,   -1,    2,    1,    2, &
          0,    0,    2,    2,    3, &
          1,    0,    2,    2,    2, &
         -1,    0,    2,    2,    2, &
         -2,    0,    4,    2,    1 /
data ((nals(i,j), i=1,5), j=621,630) / &
          2,    1,    0,    2,    1, &
          2,    1,    0,    2,    0, &
          2,   -1,    2,    0,    0, &
          1,    0,    2,    1,    0, &
          0,    1,    2,    2,    0, &
          2,    0,    2,    0,    3, &
          3,    0,    2,    0,    2, &
          1,    0,    2,    0,    2, &
          1,    0,    3,    0,    3, &
          1,    1,    2,    1,    1 /
data ((nals(i,j), i=1,5), j=631,640) / &
          0,    2,    2,    2,    2, &
          2,    1,    2,    0,    0, &
          2,    0,    4,   -2,    1, &
          4,    1,    2,   -2,    2, &
         -1,   -1,    0,    6,    0, &
         -3,   -1,    2,    6,    2, &
         -1,    0,    0,    6,    1, &
         -3,    0,    2,    6,    1, &
          1,   -1,    0,    4,    1, &
          1,   -1,    0,    4,    0 /
data ((nals(i,j), i=1,5), j=641,650) / &
         -2,    0,    2,    5,    2, &
          1,   -2,    2,    2,    1, &
          3,   -1,    0,    2,    0, &
          1,   -1,    2,    2,    0, &
          0,    0,    2,    3,    1, &
         -1,    1,    2,    4,    1, &
          0,    1,    2,    3,    2, &
         -1,    0,    4,    2,    1, &
          2,    0,    2,    1,    1, &
          5,    0,    0,    0,    0 /
data ((nals(i,j), i=1,5), j=651,660) / &
          2,    1,    2,    1,    2, &
          1,    0,    4,    0,    1, &
          3,    1,    2,    0,    1, &
          3,    0,    4,   -2,    2, &
         -2,   -1,    2,    6,    2, &
          0,    0,    0,    6,    0, &
          0,   -2,    2,    4,    2, &
         -2,    0,    2,    6,    1, &
          2,    0,    0,    4,    1, &
          2,    0,    0,    4,    0 /
data ((nals(i,j), i=1,5), j=661,670) / &
          2,   -2,    2,    2,    2, &
          0,    0,    2,    4,    0, &
          1,    0,    2,    3,    2, &
          4,    0,    0,    2,    0, &
          2,    0,    2,    2,    0, &
          0,    0,    4,    2,    2, &
          4,   -1,    2,    0,    2, &
          3,    0,    2,    1,    2, &
          2,    1,    2,    2,    1, &
          4,    1,    2,    0,    2 /
data ((nals(i,j), i=1,5), j=671,678) / &
         -1,   -1,    2,    6,    2, &
         -1,    0,    2,    6,    1, &
          1,   -1,    2,    4,    1, &
          1,    1,    2,    4,    2, &
          3,    1,    2,    2,    2, &
          5,    0,    2,    0,    1, &
          2,   -1,    2,    4,    2, &
          2,    0,    2,    4,    1 /
!
!  Luni-Solar nutation coefficients, unit 1e-7 arcsec:
!  longitude (sin, t*sin, cos), obliquity (cos, t*cos, sin)
!
data ((cls(i,j), i=1,6), j=  1, 10) / &
 -172064161d0, -174666d0,  33386d0, 92052331d0,  9086d0, 15377d0, &
  -13170906d0,   -1675d0, -13696d0,  5730336d0, -3015d0, -4587d0, &
   -2276413d0,    -234d0,   2796d0,   978459d0,  -485d0,  1374d0, &
    2074554d0,     207d0,   -698d0,  -897492d0,   470d0,  -291d0, &
    1475877d0,   -3633d0,  11817d0,    73871d0,  -184d0, -1924d0, &
    -516821d0,    1226d0,   -524d0,   224386d0,  -677d0,  -174d0, &
     711159d0,      73d0,   -872d0,    -6750d0,     0d0,   358d0, &
    -387298d0,    -367d0,    380d0,   200728d0,    18d0,   318d0, &
    -301461d0,     -36d0,    816d0,   129025d0,   -63d0,   367d0, &
     215829d0,    -494d0,    111d0,   -95929d0,   299d0,   132d0 /      !
data ((cls(i,j), i=1,6), j= 11, 20) / &
     128227d0,     137d0,    181d0,   -68982d0,    -9d0,    39d0, &
     123457d0,      11d0,     19d0,   -53311d0,    32d0,    -4d0, &
     156994d0,      10d0,   -168d0,    -1235d0,     0d0,    82d0, &
      63110d0,      63d0,     27d0,   -33228d0,     0d0,    -9d0, &
     -57976d0,     -63d0,   -189d0,    31429d0,     0d0,   -75d0, &
     -59641d0,     -11d0,    149d0,    25543d0,   -11d0,    66d0, &
     -51613d0,     -42d0,    129d0,    26366d0,     0d0,    78d0, &
      45893d0,      50d0,     31d0,   -24236d0,   -10d0,    20d0, &
      63384d0,      11d0,   -150d0,    -1220d0,     0d0,    29d0, &
     -38571d0,      -1d0,    158d0,    16452d0,   -11d0,    68d0 /      !
data ((cls(i,j), i=1,6), j= 21, 30) / &
      32481d0,       0d0,      0d0,   -13870d0,     0d0,     0d0, &
     -47722d0,       0d0,    -18d0,      477d0,     0d0,   -25d0, &
     -31046d0,      -1d0,    131d0,    13238d0,   -11d0,    59d0, &
      28593d0,       0d0,     -1d0,   -12338d0,    10d0,    -3d0, &
      20441d0,      21d0,     10d0,   -10758d0,     0d0,    -3d0, &
      29243d0,       0d0,    -74d0,     -609d0,     0d0,    13d0, &
      25887d0,       0d0,    -66d0,     -550d0,     0d0,    11d0, &
     -14053d0,     -25d0,     79d0,     8551d0,    -2d0,   -45d0, &
      15164d0,      10d0,     11d0,    -8001d0,     0d0,    -1d0, &
     -15794d0,      72d0,    -16d0,     6850d0,   -42d0,    -5d0 /      !
data ((cls(i,j), i=1,6), j= 31, 40) / &
      21783d0,       0d0,     13d0,     -167d0,     0d0,    13d0, &
     -12873d0,     -10d0,    -37d0,     6953d0,     0d0,   -14d0, &
     -12654d0,      11d0,     63d0,     6415d0,     0d0,    26d0, &
     -10204d0,       0d0,     25d0,     5222d0,     0d0,    15d0, &
      16707d0,     -85d0,    -10d0,      168d0,    -1d0,    10d0, &
      -7691d0,       0d0,     44d0,     3268d0,     0d0,    19d0, &
     -11024d0,       0d0,    -14d0,      104d0,     0d0,     2d0, &
       7566d0,     -21d0,    -11d0,    -3250d0,     0d0,    -5d0, &
      -6637d0,     -11d0,     25d0,     3353d0,     0d0,    14d0, &
      -7141d0,      21d0,      8d0,     3070d0,     0d0,     4d0 /      !
data ((cls(i,j), i=1,6), j= 41, 50) / &
      -6302d0,     -11d0,      2d0,     3272d0,     0d0,     4d0, &
       5800d0,      10d0,      2d0,    -3045d0,     0d0,    -1d0, &
       6443d0,       0d0,     -7d0,    -2768d0,     0d0,    -4d0, &
      -5774d0,     -11d0,    -15d0,     3041d0,     0d0,    -5d0, &
      -5350d0,       0d0,     21d0,     2695d0,     0d0,    12d0, &
      -4752d0,     -11d0,     -3d0,     2719d0,     0d0,    -3d0, &
      -4940d0,     -11d0,    -21d0,     2720d0,     0d0,    -9d0, &
       7350d0,       0d0,     -8d0,      -51d0,     0d0,     4d0, &
       4065d0,       0d0,      6d0,    -2206d0,     0d0,     1d0, &
       6579d0,       0d0,    -24d0,     -199d0,     0d0,     2d0 /      !
data ((cls(i,j), i=1,6), j= 51, 60) / &
       3579d0,       0d0,      5d0,    -1900d0,     0d0,     1d0, &
       4725d0,       0d0,     -6d0,      -41d0,     0d0,     3d0, &
      -3075d0,       0d0,     -2d0,     1313d0,     0d0,    -1d0, &
      -2904d0,       0d0,     15d0,     1233d0,     0d0,     7d0, &
       4348d0,       0d0,    -10d0,      -81d0,     0d0,     2d0, &
      -2878d0,       0d0,      8d0,     1232d0,     0d0,     4d0, &
      -4230d0,       0d0,      5d0,      -20d0,     0d0,    -2d0, &
      -2819d0,       0d0,      7d0,     1207d0,     0d0,     3d0, &
      -4056d0,       0d0,      5d0,       40d0,     0d0,    -2d0, &
      -2647d0,       0d0,     11d0,     1129d0,     0d0,     5d0 /      !
data ((cls(i,j), i=1,6), j= 61, 70) / &
      -2294d0,       0d0,    -10d0,     1266d0,     0d0,    -4d0, &
       2481d0,       0d0,     -7d0,    -1062d0,     0d0,    -3d0, &
       2179d0,       0d0,     -2d0,    -1129d0,     0d0,    -2d0, &
       3276d0,       0d0,      1d0,       -9d0,     0d0,     0d0, &
      -3389d0,       0d0,      5d0,       35d0,     0d0,    -2d0, &
       3339d0,       0d0,    -13d0,     -107d0,     0d0,     1d0, &
      -1987d0,       0d0,     -6d0,     1073d0,     0d0,    -2d0, &
      -1981d0,       0d0,      0d0,      854d0,     0d0,     0d0, &
       4026d0,       0d0,   -353d0,     -553d0,     0d0,  -139d0, &
       1660d0,       0d0,     -5d0,     -710d0,     0d0,    -2d0 /      !
data ((cls(i,j), i=1,6), j= 71, 80) / &
      -1521d0,       0d0,      9d0,      647d0,     0d0,     4d0, &
       1314d0,       0d0,      0d0,     -700d0,     0d0,     0d0, &
      -1283d0,       0d0,      0d0,      672d0,     0d0,     0d0, &
      -1331d0,       0d0,      8d0,      663d0,     0d0,     4d0, &
       1383d0,       0d0,     -2d0,     -594d0,     0d0,    -2d0, &
       1405d0,       0d0,      4d0,     -610d0,     0d0,     2d0, &
       1290d0,       0d0,      0d0,     -556d0,     0d0,     0d0, &
      -1214d0,       0d0,      5d0,      518d0,     0d0,     2d0, &
       1146d0,       0d0,     -3d0,     -490d0,     0d0,    -1d0, &
       1019d0,       0d0,     -1d0,     -527d0,     0d0,    -1d0 /      !
data ((cls(i,j), i=1,6), j= 81, 90) / &
      -1100d0,       0d0,      9d0,      465d0,     0d0,     4d0, &
       -970d0,       0d0,      2d0,      496d0,     0d0,     1d0, &
       1575d0,       0d0,     -6d0,      -50d0,     0d0,     0d0, &
        934d0,       0d0,     -3d0,     -399d0,     0d0,    -1d0, &
        922d0,       0d0,     -1d0,     -395d0,     0d0,    -1d0, &
        815d0,       0d0,     -1d0,     -422d0,     0d0,    -1d0, &
        834d0,       0d0,      2d0,     -440d0,     0d0,     1d0, &
       1248d0,       0d0,      0d0,     -170d0,     0d0,     1d0, &
       1338d0,       0d0,     -5d0,      -39d0,     0d0,     0d0, &
        716d0,       0d0,     -2d0,     -389d0,     0d0,    -1d0 /      !
data ((cls(i,j), i=1,6), j= 91,100) / &
       1282d0,       0d0,     -3d0,      -23d0,     0d0,     1d0, &
        742d0,       0d0,      1d0,     -391d0,     0d0,     0d0, &
       1020d0,       0d0,    -25d0,     -495d0,     0d0,   -10d0, &
        715d0,       0d0,     -4d0,     -326d0,     0d0,     2d0, &
       -666d0,       0d0,     -3d0,      369d0,     0d0,    -1d0, &
       -667d0,       0d0,      1d0,      346d0,     0d0,     1d0, &
       -704d0,       0d0,      0d0,      304d0,     0d0,     0d0, &
       -694d0,       0d0,      5d0,      294d0,     0d0,     2d0, &
      -1014d0,       0d0,     -1d0,        4d0,     0d0,    -1d0, &
       -585d0,       0d0,     -2d0,      316d0,     0d0,    -1d0 /      !
data ((cls(i,j), i=1,6), j=101,110) / &
       -949d0,       0d0,      1d0,        8d0,     0d0,    -1d0, &
       -595d0,       0d0,      0d0,      258d0,     0d0,     0d0, &
        528d0,       0d0,      0d0,     -279d0,     0d0,     0d0, &
       -590d0,       0d0,      4d0,      252d0,     0d0,     2d0, &
        570d0,       0d0,     -2d0,     -244d0,     0d0,    -1d0, &
       -502d0,       0d0,      3d0,      250d0,     0d0,     2d0, &
       -875d0,       0d0,      1d0,       29d0,     0d0,     0d0, &
       -492d0,       0d0,     -3d0,      275d0,     0d0,    -1d0, &
        535d0,       0d0,     -2d0,     -228d0,     0d0,    -1d0, &
       -467d0,       0d0,      1d0,      240d0,     0d0,     1d0 /      !
data ((cls(i,j), i=1,6), j=111,120) / &
        591d0,       0d0,      0d0,     -253d0,     0d0,     0d0, &
       -453d0,       0d0,     -1d0,      244d0,     0d0,    -1d0, &
        766d0,       0d0,      1d0,        9d0,     0d0,     0d0, &
       -446d0,       0d0,      2d0,      225d0,     0d0,     1d0, &
       -488d0,       0d0,      2d0,      207d0,     0d0,     1d0, &
       -468d0,       0d0,      0d0,      201d0,     0d0,     0d0, &
       -421d0,       0d0,      1d0,      216d0,     0d0,     1d0, &
        463d0,       0d0,      0d0,     -200d0,     0d0,     0d0, &
       -673d0,       0d0,      2d0,       14d0,     0d0,     0d0, &
        658d0,       0d0,      0d0,       -2d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=121,130) / &
       -438d0,       0d0,      0d0,      188d0,     0d0,     0d0, &
       -390d0,       0d0,      0d0,      205d0,     0d0,     0d0, &
        639d0,     -11d0,     -2d0,      -19d0,     0d0,     0d0, &
        412d0,       0d0,     -2d0,     -176d0,     0d0,    -1d0, &
       -361d0,       0d0,      0d0,      189d0,     0d0,     0d0, &
        360d0,       0d0,     -1d0,     -185d0,     0d0,    -1d0, &
        588d0,       0d0,     -3d0,      -24d0,     0d0,     0d0, &
       -578d0,       0d0,      1d0,        5d0,     0d0,     0d0, &
       -396d0,       0d0,      0d0,      171d0,     0d0,     0d0, &
        565d0,       0d0,     -1d0,       -6d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=131,140) / &
       -335d0,       0d0,     -1d0,      184d0,     0d0,    -1d0, &
        357d0,       0d0,      1d0,     -154d0,     0d0,     0d0, &
        321d0,       0d0,      1d0,     -174d0,     0d0,     0d0, &
       -301d0,       0d0,     -1d0,      162d0,     0d0,     0d0, &
       -334d0,       0d0,      0d0,      144d0,     0d0,     0d0, &
        493d0,       0d0,     -2d0,      -15d0,     0d0,     0d0, &
        494d0,       0d0,     -2d0,      -19d0,     0d0,     0d0, &
        337d0,       0d0,     -1d0,     -143d0,     0d0,    -1d0, &
        280d0,       0d0,     -1d0,     -144d0,     0d0,     0d0, &
        309d0,       0d0,      1d0,     -134d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=141,150) / &
       -263d0,       0d0,      2d0,      131d0,     0d0,     1d0, &
        253d0,       0d0,      1d0,     -138d0,     0d0,     0d0, &
        245d0,       0d0,      0d0,     -128d0,     0d0,     0d0, &
        416d0,       0d0,     -2d0,      -17d0,     0d0,     0d0, &
       -229d0,       0d0,      0d0,      128d0,     0d0,     0d0, &
        231d0,       0d0,      0d0,     -120d0,     0d0,     0d0, &
       -259d0,       0d0,      2d0,      109d0,     0d0,     1d0, &
        375d0,       0d0,     -1d0,       -8d0,     0d0,     0d0, &
        252d0,       0d0,      0d0,     -108d0,     0d0,     0d0, &
       -245d0,       0d0,      1d0,      104d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=151,160) / &
        243d0,       0d0,     -1d0,     -104d0,     0d0,     0d0, &
        208d0,       0d0,      1d0,     -112d0,     0d0,     0d0, &
        199d0,       0d0,      0d0,     -102d0,     0d0,     0d0, &
       -208d0,       0d0,      1d0,      105d0,     0d0,     0d0, &
        335d0,       0d0,     -2d0,      -14d0,     0d0,     0d0, &
       -325d0,       0d0,      1d0,        7d0,     0d0,     0d0, &
       -187d0,       0d0,      0d0,       96d0,     0d0,     0d0, &
        197d0,       0d0,     -1d0,     -100d0,     0d0,     0d0, &
       -192d0,       0d0,      2d0,       94d0,     0d0,     1d0, &
       -188d0,       0d0,      0d0,       83d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=161,170) / &
        276d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
       -286d0,       0d0,      1d0,        6d0,     0d0,     0d0, &
        186d0,       0d0,     -1d0,      -79d0,     0d0,     0d0, &
       -219d0,       0d0,      0d0,       43d0,     0d0,     0d0, &
        276d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
       -153d0,       0d0,     -1d0,       84d0,     0d0,     0d0, &
       -156d0,       0d0,      0d0,       81d0,     0d0,     0d0, &
       -154d0,       0d0,      1d0,       78d0,     0d0,     0d0, &
       -174d0,       0d0,      1d0,       75d0,     0d0,     0d0, &
       -163d0,       0d0,      2d0,       69d0,     0d0,     1d0 /      !
data ((cls(i,j), i=1,6), j=171,180) / &
       -228d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
         91d0,       0d0,     -4d0,      -54d0,     0d0,    -2d0, &
        175d0,       0d0,      0d0,      -75d0,     0d0,     0d0, &
       -159d0,       0d0,      0d0,       69d0,     0d0,     0d0, &
        141d0,       0d0,      0d0,      -72d0,     0d0,     0d0, &
        147d0,       0d0,      0d0,      -75d0,     0d0,     0d0, &
       -132d0,       0d0,      0d0,       69d0,     0d0,     0d0, &
        159d0,       0d0,    -28d0,      -54d0,     0d0,    11d0, &
        213d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
        123d0,       0d0,      0d0,      -64d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=181,190) / &
       -118d0,       0d0,     -1d0,       66d0,     0d0,     0d0, &
        144d0,       0d0,     -1d0,      -61d0,     0d0,     0d0, &
       -121d0,       0d0,      1d0,       60d0,     0d0,     0d0, &
       -134d0,       0d0,      1d0,       56d0,     0d0,     1d0, &
       -105d0,       0d0,      0d0,       57d0,     0d0,     0d0, &
       -102d0,       0d0,      0d0,       56d0,     0d0,     0d0, &
        120d0,       0d0,      0d0,      -52d0,     0d0,     0d0, &
        101d0,       0d0,      0d0,      -54d0,     0d0,     0d0, &
       -113d0,       0d0,      0d0,       59d0,     0d0,     0d0, &
       -106d0,       0d0,      0d0,       61d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=191,200) / &
       -129d0,       0d0,      1d0,       55d0,     0d0,     0d0, &
       -114d0,       0d0,      0d0,       57d0,     0d0,     0d0, &
        113d0,       0d0,     -1d0,      -49d0,     0d0,     0d0, &
       -102d0,       0d0,      0d0,       44d0,     0d0,     0d0, &
        -94d0,       0d0,      0d0,       51d0,     0d0,     0d0, &
       -100d0,       0d0,     -1d0,       56d0,     0d0,     0d0, &
         87d0,       0d0,      0d0,      -47d0,     0d0,     0d0, &
        161d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         96d0,       0d0,      0d0,      -50d0,     0d0,     0d0, &
        151d0,       0d0,     -1d0,       -5d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=201,210) / &
       -104d0,       0d0,      0d0,       44d0,     0d0,     0d0, &
       -110d0,       0d0,      0d0,       48d0,     0d0,     0d0, &
       -100d0,       0d0,      1d0,       50d0,     0d0,     0d0, &
         92d0,       0d0,     -5d0,       12d0,     0d0,    -2d0, &
         82d0,       0d0,      0d0,      -45d0,     0d0,     0d0, &
         82d0,       0d0,      0d0,      -45d0,     0d0,     0d0, &
        -78d0,       0d0,      0d0,       41d0,     0d0,     0d0, &
        -77d0,       0d0,      0d0,       43d0,     0d0,     0d0, &
          2d0,       0d0,      0d0,       54d0,     0d0,     0d0, &
         94d0,       0d0,      0d0,      -40d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=211,220) / &
        -93d0,       0d0,      0d0,       40d0,     0d0,     0d0, &
        -83d0,       0d0,     10d0,       40d0,     0d0,    -2d0, &
         83d0,       0d0,      0d0,      -36d0,     0d0,     0d0, &
        -91d0,       0d0,      0d0,       39d0,     0d0,     0d0, &
        128d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
        -79d0,       0d0,      0d0,       34d0,     0d0,     0d0, &
        -83d0,       0d0,      0d0,       47d0,     0d0,     0d0, &
         84d0,       0d0,      0d0,      -44d0,     0d0,     0d0, &
         83d0,       0d0,      0d0,      -43d0,     0d0,     0d0, &
         91d0,       0d0,      0d0,      -39d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=221,230) / &
        -77d0,       0d0,      0d0,       39d0,     0d0,     0d0, &
         84d0,       0d0,      0d0,      -43d0,     0d0,     0d0, &
        -92d0,       0d0,      1d0,       39d0,     0d0,     0d0, &
        -92d0,       0d0,      1d0,       39d0,     0d0,     0d0, &
        -94d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         68d0,       0d0,      0d0,      -36d0,     0d0,     0d0, &
        -61d0,       0d0,      0d0,       32d0,     0d0,     0d0, &
         71d0,       0d0,      0d0,      -31d0,     0d0,     0d0, &
         62d0,       0d0,      0d0,      -34d0,     0d0,     0d0, &
        -63d0,       0d0,      0d0,       33d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=231,240) / &
        -73d0,       0d0,      0d0,       32d0,     0d0,     0d0, &
        115d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
       -103d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         63d0,       0d0,      0d0,      -28d0,     0d0,     0d0, &
         74d0,       0d0,      0d0,      -32d0,     0d0,     0d0, &
       -103d0,       0d0,     -3d0,        3d0,     0d0,    -1d0, &
        -69d0,       0d0,      0d0,       30d0,     0d0,     0d0, &
         57d0,       0d0,      0d0,      -29d0,     0d0,     0d0, &
         94d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
         64d0,       0d0,      0d0,      -33d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=241,250) / &
        -63d0,       0d0,      0d0,       26d0,     0d0,     0d0, &
        -38d0,       0d0,      0d0,       20d0,     0d0,     0d0, &
        -43d0,       0d0,      0d0,       24d0,     0d0,     0d0, &
        -45d0,       0d0,      0d0,       23d0,     0d0,     0d0, &
         47d0,       0d0,      0d0,      -24d0,     0d0,     0d0, &
        -48d0,       0d0,      0d0,       25d0,     0d0,     0d0, &
         45d0,       0d0,      0d0,      -26d0,     0d0,     0d0, &
         56d0,       0d0,      0d0,      -25d0,     0d0,     0d0, &
         88d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
        -75d0,       0d0,      0d0,        0d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=251,260) / &
         85d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         49d0,       0d0,      0d0,      -26d0,     0d0,     0d0, &
        -74d0,       0d0,     -3d0,       -1d0,     0d0,    -1d0, &
        -39d0,       0d0,      0d0,       21d0,     0d0,     0d0, &
         45d0,       0d0,      0d0,      -20d0,     0d0,     0d0, &
         51d0,       0d0,      0d0,      -22d0,     0d0,     0d0, &
        -40d0,       0d0,      0d0,       21d0,     0d0,     0d0, &
         41d0,       0d0,      0d0,      -21d0,     0d0,     0d0, &
        -42d0,       0d0,      0d0,       24d0,     0d0,     0d0, &
        -51d0,       0d0,      0d0,       22d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=261,270) / &
        -42d0,       0d0,      0d0,       22d0,     0d0,     0d0, &
         39d0,       0d0,      0d0,      -21d0,     0d0,     0d0, &
         46d0,       0d0,      0d0,      -18d0,     0d0,     0d0, &
        -53d0,       0d0,      0d0,       22d0,     0d0,     0d0, &
         82d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
         81d0,       0d0,     -1d0,       -4d0,     0d0,     0d0, &
         47d0,       0d0,      0d0,      -19d0,     0d0,     0d0, &
         53d0,       0d0,      0d0,      -23d0,     0d0,     0d0, &
        -45d0,       0d0,      0d0,       22d0,     0d0,     0d0, &
        -44d0,       0d0,      0d0,       -2d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=271,280) / &
        -33d0,       0d0,      0d0,       16d0,     0d0,     0d0, &
        -61d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
         28d0,       0d0,      0d0,      -15d0,     0d0,     0d0, &
        -38d0,       0d0,      0d0,       19d0,     0d0,     0d0, &
        -33d0,       0d0,      0d0,       21d0,     0d0,     0d0, &
        -60d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         48d0,       0d0,      0d0,      -10d0,     0d0,     0d0, &
         27d0,       0d0,      0d0,      -14d0,     0d0,     0d0, &
         38d0,       0d0,      0d0,      -20d0,     0d0,     0d0, &
         31d0,       0d0,      0d0,      -13d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=281,290) / &
        -29d0,       0d0,      0d0,       15d0,     0d0,     0d0, &
         28d0,       0d0,      0d0,      -15d0,     0d0,     0d0, &
        -32d0,       0d0,      0d0,       15d0,     0d0,     0d0, &
         45d0,       0d0,      0d0,       -8d0,     0d0,     0d0, &
        -44d0,       0d0,      0d0,       19d0,     0d0,     0d0, &
         28d0,       0d0,      0d0,      -15d0,     0d0,     0d0, &
        -51d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -36d0,       0d0,      0d0,       20d0,     0d0,     0d0, &
         44d0,       0d0,      0d0,      -19d0,     0d0,     0d0, &
         26d0,       0d0,      0d0,      -14d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=291,300) / &
        -60d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         35d0,       0d0,      0d0,      -18d0,     0d0,     0d0, &
        -27d0,       0d0,      0d0,       11d0,     0d0,     0d0, &
         47d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         36d0,       0d0,      0d0,      -15d0,     0d0,     0d0, &
        -36d0,       0d0,      0d0,       20d0,     0d0,     0d0, &
        -35d0,       0d0,      0d0,       19d0,     0d0,     0d0, &
        -37d0,       0d0,      0d0,       19d0,     0d0,     0d0, &
         32d0,       0d0,      0d0,      -16d0,     0d0,     0d0, &
         35d0,       0d0,      0d0,      -14d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=301,310) / &
         32d0,       0d0,      0d0,      -13d0,     0d0,     0d0, &
         65d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         47d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         32d0,       0d0,      0d0,      -16d0,     0d0,     0d0, &
         37d0,       0d0,      0d0,      -16d0,     0d0,     0d0, &
        -30d0,       0d0,      0d0,       15d0,     0d0,     0d0, &
        -32d0,       0d0,      0d0,       16d0,     0d0,     0d0, &
        -31d0,       0d0,      0d0,       13d0,     0d0,     0d0, &
         37d0,       0d0,      0d0,      -16d0,     0d0,     0d0, &
         31d0,       0d0,      0d0,      -13d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=311,320) / &
         49d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         32d0,       0d0,      0d0,      -13d0,     0d0,     0d0, &
         23d0,       0d0,      0d0,      -12d0,     0d0,     0d0, &
        -43d0,       0d0,      0d0,       18d0,     0d0,     0d0, &
         26d0,       0d0,      0d0,      -11d0,     0d0,     0d0, &
        -32d0,       0d0,      0d0,       14d0,     0d0,     0d0, &
        -29d0,       0d0,      0d0,       14d0,     0d0,     0d0, &
        -27d0,       0d0,      0d0,       12d0,     0d0,     0d0, &
         30d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -11d0,       0d0,      0d0,        5d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=321,330) / &
        -21d0,       0d0,      0d0,       10d0,     0d0,     0d0, &
        -34d0,       0d0,      0d0,       15d0,     0d0,     0d0, &
        -10d0,       0d0,      0d0,        6d0,     0d0,     0d0, &
        -36d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -9d0,       0d0,      0d0,        4d0,     0d0,     0d0, &
        -12d0,       0d0,      0d0,        5d0,     0d0,     0d0, &
        -21d0,       0d0,      0d0,        5d0,     0d0,     0d0, &
        -29d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
        -15d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
        -20d0,       0d0,      0d0,        0d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=331,340) / &
         28d0,       0d0,      0d0,        0d0,     0d0,    -2d0, &
         17d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -22d0,       0d0,      0d0,       12d0,     0d0,     0d0, &
        -14d0,       0d0,      0d0,        7d0,     0d0,     0d0, &
         24d0,       0d0,      0d0,      -11d0,     0d0,     0d0, &
         11d0,       0d0,      0d0,       -6d0,     0d0,     0d0, &
         14d0,       0d0,      0d0,       -6d0,     0d0,     0d0, &
         24d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         18d0,       0d0,      0d0,       -8d0,     0d0,     0d0, &
        -38d0,       0d0,      0d0,        0d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=341,350) / &
        -31d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -16d0,       0d0,      0d0,        8d0,     0d0,     0d0, &
         29d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -18d0,       0d0,      0d0,       10d0,     0d0,     0d0, &
        -10d0,       0d0,      0d0,        5d0,     0d0,     0d0, &
        -17d0,       0d0,      0d0,       10d0,     0d0,     0d0, &
          9d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
         16d0,       0d0,      0d0,       -6d0,     0d0,     0d0, &
         22d0,       0d0,      0d0,      -12d0,     0d0,     0d0, &
         20d0,       0d0,      0d0,        0d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=351,360) / &
        -13d0,       0d0,      0d0,        6d0,     0d0,     0d0, &
        -17d0,       0d0,      0d0,        9d0,     0d0,     0d0, &
        -14d0,       0d0,      0d0,        8d0,     0d0,     0d0, &
          0d0,       0d0,      0d0,       -7d0,     0d0,     0d0, &
         14d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         19d0,       0d0,      0d0,      -10d0,     0d0,     0d0, &
        -34d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -20d0,       0d0,      0d0,        8d0,     0d0,     0d0, &
          9d0,       0d0,      0d0,       -5d0,     0d0,     0d0, &
        -18d0,       0d0,      0d0,        7d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=361,370) / &
         13d0,       0d0,      0d0,       -6d0,     0d0,     0d0, &
         17d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -12d0,       0d0,      0d0,        5d0,     0d0,     0d0, &
         15d0,       0d0,      0d0,       -8d0,     0d0,     0d0, &
        -11d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
         13d0,       0d0,      0d0,       -5d0,     0d0,     0d0, &
        -18d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -35d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          9d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
        -19d0,       0d0,      0d0,       10d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=371,380) / &
        -26d0,       0d0,      0d0,       11d0,     0d0,     0d0, &
          8d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
        -10d0,       0d0,      0d0,        4d0,     0d0,     0d0, &
         10d0,       0d0,      0d0,       -6d0,     0d0,     0d0, &
        -21d0,       0d0,      0d0,        9d0,     0d0,     0d0, &
        -15d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          9d0,       0d0,      0d0,       -5d0,     0d0,     0d0, &
        -29d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -19d0,       0d0,      0d0,       10d0,     0d0,     0d0, &
         12d0,       0d0,      0d0,       -5d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=381,390) / &
         22d0,       0d0,      0d0,       -9d0,     0d0,     0d0, &
        -10d0,       0d0,      0d0,        5d0,     0d0,     0d0, &
        -20d0,       0d0,      0d0,       11d0,     0d0,     0d0, &
        -20d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -17d0,       0d0,      0d0,        7d0,     0d0,     0d0, &
         15d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
          8d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
         14d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -12d0,       0d0,      0d0,        6d0,     0d0,     0d0, &
         25d0,       0d0,      0d0,        0d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=391,400) / &
        -13d0,       0d0,      0d0,        6d0,     0d0,     0d0, &
        -14d0,       0d0,      0d0,        8d0,     0d0,     0d0, &
         13d0,       0d0,      0d0,       -5d0,     0d0,     0d0, &
        -17d0,       0d0,      0d0,        9d0,     0d0,     0d0, &
        -12d0,       0d0,      0d0,        6d0,     0d0,     0d0, &
        -10d0,       0d0,      0d0,        5d0,     0d0,     0d0, &
         10d0,       0d0,      0d0,       -6d0,     0d0,     0d0, &
        -15d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -22d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         28d0,       0d0,      0d0,       -1d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=401,410) / &
         15d0,       0d0,      0d0,       -7d0,     0d0,     0d0, &
         23d0,       0d0,      0d0,      -10d0,     0d0,     0d0, &
         12d0,       0d0,      0d0,       -5d0,     0d0,     0d0, &
         29d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
        -25d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
         22d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -18d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         15d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
        -23d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         12d0,       0d0,      0d0,       -5d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=411,420) / &
         -8d0,       0d0,      0d0,        4d0,     0d0,     0d0, &
        -19d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -10d0,       0d0,      0d0,        4d0,     0d0,     0d0, &
         21d0,       0d0,      0d0,       -9d0,     0d0,     0d0, &
         23d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
        -16d0,       0d0,      0d0,        8d0,     0d0,     0d0, &
        -19d0,       0d0,      0d0,        9d0,     0d0,     0d0, &
        -22d0,       0d0,      0d0,       10d0,     0d0,     0d0, &
         27d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         16d0,       0d0,      0d0,       -8d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=421,430) / &
         19d0,       0d0,      0d0,       -8d0,     0d0,     0d0, &
          9d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
         -9d0,       0d0,      0d0,        4d0,     0d0,     0d0, &
         -9d0,       0d0,      0d0,        4d0,     0d0,     0d0, &
         -8d0,       0d0,      0d0,        4d0,     0d0,     0d0, &
         18d0,       0d0,      0d0,       -9d0,     0d0,     0d0, &
         16d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
        -10d0,       0d0,      0d0,        4d0,     0d0,     0d0, &
        -23d0,       0d0,      0d0,        9d0,     0d0,     0d0, &
         16d0,       0d0,      0d0,       -1d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=431,440) / &
        -12d0,       0d0,      0d0,        6d0,     0d0,     0d0, &
         -8d0,       0d0,      0d0,        4d0,     0d0,     0d0, &
         30d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         24d0,       0d0,      0d0,      -10d0,     0d0,     0d0, &
         10d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
        -16d0,       0d0,      0d0,        7d0,     0d0,     0d0, &
        -16d0,       0d0,      0d0,        7d0,     0d0,     0d0, &
         17d0,       0d0,      0d0,       -7d0,     0d0,     0d0, &
        -24d0,       0d0,      0d0,       10d0,     0d0,     0d0, &
        -12d0,       0d0,      0d0,        5d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=441,450) / &
        -24d0,       0d0,      0d0,       11d0,     0d0,     0d0, &
        -23d0,       0d0,      0d0,        9d0,     0d0,     0d0, &
        -13d0,       0d0,      0d0,        5d0,     0d0,     0d0, &
        -15d0,       0d0,      0d0,        7d0,     0d0,     0d0, &
          0d0,       0d0,  -1988d0,        0d0,     0d0, -1679d0, &
          0d0,       0d0,    -63d0,        0d0,     0d0,   -27d0, &
         -4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          0d0,       0d0,      5d0,        0d0,     0d0,     4d0, &
          5d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
          0d0,       0d0,    364d0,        0d0,     0d0,   176d0 /      !
data ((cls(i,j), i=1,6), j=451,460) / &
          0d0,       0d0,  -1044d0,        0d0,     0d0,  -891d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          0d0,       0d0,    330d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
         -5d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,        0d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=461,470) / &
          3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          0d0,       0d0,      5d0,        0d0,     0d0,     0d0, &
          0d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
        -12d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=471,480) / &
         -5d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
          7d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
          0d0,       0d0,    -12d0,        0d0,     0d0,   -10d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=481,490) / &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
          0d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
          7d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         -5d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -5d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -2d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=491,500) / &
         -8d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
          9d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
         -5d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=501,510) / &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         -5d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          9d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          9d0,       0d0,      0d0,       -3d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=511,520) / &
         -4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          8d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,       -3d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=521,530) / &
          3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          9d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -5d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
        -13d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        0d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=531,540) / &
         10d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         10d0,       0d0,     13d0,        6d0,     0d0,    -5d0, &
          0d0,       0d0,     30d0,        0d0,     0d0,    14d0, &
          0d0,       0d0,   -162d0,        0d0,     0d0,  -138d0, &
          0d0,       0d0,     75d0,        0d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        4d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -2d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=541,550) / &
          5d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -5d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          9d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=551,560) / &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          7d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -6d0,       0d0,     -3d0,        3d0,     0d0,     1d0, &
          0d0,       0d0,     -3d0,        0d0,     0d0,    -2d0, &
         11d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         11d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=561,570) / &
         -1d0,       0d0,      3d0,        3d0,     0d0,    -1d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          0d0,       0d0,    -13d0,        0d0,     0d0,   -11d0, &
          3d0,       0d0,      6d0,        0d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        3d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=571,580) / &
          8d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         11d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          8d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         11d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -6d0,       0d0,      0d0,        3d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=581,590) / &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -8d0,       0d0,      0d0,        4d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
         -6d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -2d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=591,600) / &
         -5d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          0d0,       0d0,    -26d0,        0d0,     0d0,   -11d0, &
          0d0,       0d0,    -10d0,        0d0,     0d0,    -5d0, &
          5d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
        -13d0,       0d0,      0d0,        0d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=601,610) / &
          3d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          7d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -6d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -5d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -7d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -2d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=611,620) / &
         13d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
        -11d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,       -3d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=621,630) / &
          3d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
        -12d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
          0d0,       0d0,     -5d0,        0d0,     0d0,    -2d0, &
         -7d0,       0d0,      0d0,        4d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=631,640) / &
          6d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
         -5d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         12d0,       0d0,      0d0,        0d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=641,650) / &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         -6d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
          6d0,       0d0,      0d0,        0d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=651,660) / &
         -6d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          7d0,       0d0,      0d0,       -4d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         -5d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         -6d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
         -6d0,       0d0,      0d0,        3d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         10d0,       0d0,      0d0,        0d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=661,670) / &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          7d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          7d0,       0d0,      0d0,       -3d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
         11d0,       0d0,      0d0,        0d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
         -6d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          5d0,       0d0,      0d0,       -2d0,     0d0,     0d0 /      !
data ((cls(i,j), i=1,6), j=671,678) / &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -4d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0, &
          4d0,       0d0,      0d0,       -2d0,     0d0,     0d0, &
          3d0,       0d0,      0d0,       -1d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        1d0,     0d0,     0d0, &
         -3d0,       0d0,      0d0,        2d0,     0d0,     0d0 /      !
!
!  Planetary argument multipliers:
!              L   L'  F   D   Om  Me  Ve  E  Ma  Ju  Sa  Ur  Ne  pre
data ((napl(i,j), i=1,14), j=  1, 10) / &
         0,  0,  0,  0,  0,  0,  0,  8,-16,  4,  5,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -8, 16, -4, -5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  8,-16,  4,  5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  2,  2, &
         0,  0,  0,  0,  0,  0,  0, -4,  8, -1, -5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  4, -8,  3,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  0,  3, -8,  3,  0,  0,  0,  0, &
        -1,  0,  0,  0,  0,  0, 10, -3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0, -2,  6, -3,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  4, -8,  3,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j= 11, 20) / &
         0,  0,  1, -1,  1,  0,  0, -5,  8, -3,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -4,  8, -3,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  4, -8,  1,  5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -5,  6,  4,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -5,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  2, -5,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -5,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0, -2,  5,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0, -2,  5,  0,  0,  1 /
data ((napl(i,j), i=1,14), j= 21, 30) / &
         0,  0,  0,  0,  0,  0,  0,  0,  0, -2,  5,  0,  0,  2, &
         2,  0, -1, -1,  0,  0,  0,  3, -7,  0,  0,  0,  0,  0, &
         1,  0,  0, -2,  0,  0, 19,-21,  3,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  2, -4,  0, -3,  0,  0,  0,  0, &
         1,  0,  0, -1,  1,  0,  0, -1,  0,  2,  0,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0, -4, 10,  0,  0,  0, &
        -2,  0,  0,  2,  1,  0,  0,  2,  0,  0, -5,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  3, -7,  4,  0,  0,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  0,  1,  0,  1, -1,  0,  0,  0, &
        -2,  0,  0,  2,  1,  0,  0,  2,  0, -2,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j= 31, 40) / &
        -1,  0,  0,  0,  0,  0, 18,-16,  0,  0,  0,  0,  0,  0, &
        -2,  0,  1,  1,  2,  0,  0,  1,  0, -2,  0,  0,  0,  0, &
        -1,  0,  1, -1,  1,  0, 18,-17,  0,  0,  0,  0,  0,  0, &
        -1,  0,  0,  1,  1,  0,  0,  2, -2,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -8, 13,  0,  0,  0,  0,  0,  2, &
         0,  0,  2, -2,  2,  0, -8, 11,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -8, 13,  0,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0, -8, 12,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  8,-13,  0,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  8,-14,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j= 41, 50) / &
         0,  0,  0,  0,  0,  0,  8,-13,  0,  0,  0,  0,  0,  1, &
        -2,  0,  0,  2,  1,  0,  0,  2,  0, -4,  5,  0,  0,  0, &
        -2,  0,  0,  2,  2,  0,  3, -3,  0,  0,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  2,  0, -3,  1,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  3, -5,  0,  2,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  2,  0, -4,  3,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0, -1,  2,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  2,  0,  0, -2,  2,  0,  0,  0,  0,  0, &
        -1,  0,  1,  0,  1,  0,  3, -5,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j= 51, 60) / &
        -1,  0,  0,  1,  0,  0,  3, -4,  0,  0,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  2,  0, -2, -2,  0,  0,  0, &
        -2,  0,  2,  0,  2,  0,  0, -5,  9,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  0, -1,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  0,  0,  2,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  1, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  2, &
        -1,  0,  0,  1,  0,  0,  0,  3, -4,  0,  0,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  0,  1,  0,  0,  2,  0,  0,  0 /
data ((napl(i,j), i=1,14), j= 61, 70) / &
         0,  0,  1, -1,  2,  0,  0, -1,  0,  0,  2,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0, -9, 17,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  2,  0, -3,  5,  0,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0, -1,  2,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0, &
         1,  0,  0, -2,  0,  0, 17,-16,  0, -2,  0,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  1, -3,  0,  0,  0, &
        -2,  0,  0,  2,  1,  0,  0,  5, -6,  0,  0,  0,  0,  0, &
         0,  0, -2,  2,  0,  0,  0,  9,-13,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  2,  0,  0, -1,  0,  0,  1,  0,  0,  0 /
data ((napl(i,j), i=1,14), j= 71, 80) / &
         0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0, &
         0,  0, -2,  2,  0,  0,  5, -6,  0,  0,  0,  0,  0,  0, &
         0,  0, -1,  1,  1,  0,  5, -7,  0,  0,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  6, -8,  0,  0,  0,  0,  0,  0, &
         2,  0,  1, -3,  1,  0, -6,  7,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  2,  0,  0,  0,  0,  1,  0,  0,  0,  0, &
         0,  0, -1,  1,  1,  0,  0,  1,  0,  1,  0,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  0,  2,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  1 /
data ((napl(i,j), i=1,14), j= 81, 90) / &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -8, 15,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -8, 15,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  0, -9, 15,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  8,-15,  0,  0,  0,  0,  0, &
         1,  0, -1, -1,  0,  0,  0,  8,-15,  0,  0,  0,  0,  0, &
         2,  0,  0, -2,  0,  0,  2, -5,  0,  0,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  2,  0, -5,  5,  0,  0,  0, &
         2,  0,  0, -2,  1,  0,  0, -6,  8,  0,  0,  0,  0,  0, &
         2,  0,  0, -2,  1,  0,  0, -2,  0,  3,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j= 91,100) / &
        -2,  0,  1,  1,  0,  0,  0,  1,  0, -3,  0,  0,  0,  0, &
        -2,  0,  1,  1,  1,  0,  0,  1,  0, -3,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  2,  0, -3,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  6, -8,  0,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  2,  0, -1, -5,  0,  0,  0, &
        -1,  0,  0,  1,  0,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
        -1,  0,  1,  1,  1,  0,-20, 20,  0,  0,  0,  0,  0,  0, &
         1,  0,  0, -2,  0,  0, 20,-21,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0,  8,-15,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  0,-10, 15,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=101,110) / &
         0,  0, -1,  1,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0, &
         0,  0,  1, -1,  2,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0, -2,  4,  0,  0,  0, &
         2,  0,  0, -2,  1,  0, -6,  8,  0,  0,  0,  0,  0,  0, &
         0,  0, -2,  2,  1,  0,  5, -6,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  0, -1,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  1,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=111,120) / &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  2, &
         0,  0,  2, -2,  1,  0,  0, -9, 13,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0,  7,-13,  0,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  5, -6,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  9,-17,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -9, 17,  0,  0,  0,  0,  2, &
         1,  0,  0, -1,  1,  0,  0, -3,  4,  0,  0,  0,  0,  0, &
         1,  0,  0, -1,  1,  0, -3,  4,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  2,  0,  0, -1,  2,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=121,130) / &
         0,  0, -1,  1,  1,  0,  0,  0,  2,  0,  0,  0,  0,  0, &
         0,  0, -2,  2,  0,  1,  0, -2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  3, -5,  0,  2,  0,  0,  0,  0, &
        -2,  0,  0,  2,  1,  0,  0,  2,  0, -3,  1,  0,  0,  0, &
        -2,  0,  0,  2,  1,  0,  3, -3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  8,-13,  0,  0,  0,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  8,-12,  0,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0, -8, 11,  0,  0,  0,  0,  0,  0, &
        -1,  0,  0,  1,  0,  0,  0,  2, -2,  0,  0,  0,  0,  0, &
        -1,  0,  0,  0,  1,  0, 18,-16,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=131,140) / &
         0,  0,  1, -1,  1,  0,  0, -1,  0, -1,  1,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  3, -7,  4,  0,  0,  0,  0,  0, &
        -2,  0,  1,  1,  1,  0,  0, -3,  7,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  2,  0,  0, -1,  0, -2,  5,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0,  0,  0, -2,  5,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
         1,  0,  0,  0,  1,  0,-10,  3,  0,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  0, -2,  0,  0,  0,  0,  0,  0, &
        -1,  0,  0,  0,  1,  0, 10, -3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0,  4, -8,  3,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=141,150) / &
         0,  0,  0,  0,  1,  0,  0,  0,  0,  2, -5,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  0,  1,  0,  2, -5,  0,  0,  0, &
         2,  0, -1, -1,  1,  0,  0,  3, -7,  0,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  2,  0,  0, -5,  0,  0,  0, &
         0,  0,  0,  0,  1,  0, -3,  7, -4,  0,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
         1,  0,  0,  0,  1,  0,-18, 16,  0,  0,  0,  0,  0,  0, &
        -2,  0,  1,  1,  1,  0,  0,  1,  0, -2,  0,  0,  0,  0, &
         0,  0,  1, -1,  2,  0, -8, 12,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0, -8, 13,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=151,160) / &
         0,  0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  0,  0, -2,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -2,  2,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -1,  2,  0,  0,  0,  0,  1, &
        -1,  0,  0,  1,  1,  0,  3, -4,  0,  0,  0,  0,  0,  0, &
        -1,  0,  0,  1,  1,  0,  0,  3, -4,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  0, -2,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  2,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  1 /
data ((napl(i,j), i=1,14), j=161,170) / &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  2, &
         0,  0,  1, -1,  0,  0,  3, -6,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0, -3,  5,  0,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  2,  0, -3,  4,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0, -2,  4,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0, -5,  6,  0,  0,  0,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  5, -7,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  5, -8,  0,  0,  0,  0,  0,  0, &
        -2,  0,  0,  2,  1,  0,  6, -8,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0, -8, 15,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=171,180) / &
        -2,  0,  0,  2,  1,  0,  0,  2,  0, -3,  0,  0,  0,  0, &
        -2,  0,  0,  2,  1,  0,  0,  6, -8,  0,  0,  0,  0,  0, &
         1,  0,  0, -1,  1,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0, -1,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1 /
data ((napl(i,j), i=1,14), j=181,190) / &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  2, &
         0,  0,  1, -1,  2,  0,  0, -1,  0,  0, -1,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0,  0,  0,  0, -1,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  0,  1,  0,  0, -1,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -7, 13,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  7,-13,  0,  0,  0,  0,  0, &
         2,  0,  0, -2,  1,  0,  0, -5,  6,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  0, -8, 11,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1, -1,  0,  2,  0,  0,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  4, -4,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=191,200) / &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  2, -2,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  0,  3,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  2, &
        -2,  0,  0,  2,  0,  0,  3, -3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  2,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
         0,  0,  0,  0,  2,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
         2,  0,  0, -2,  1,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
         0,  0,  1, -1,  2,  0,  0, -1,  0,  2,  0,  0,  0,  0, &
         0,  0,  1, -1,  2,  0,  0,  0, -2,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=201,210) / &
         0,  0,  0,  0,  1,  0,  0,  1, -2,  0,  0,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  0,  2, -2,  0,  0,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  0,  1,  0,  0, -2,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  0, -2,  0,  0,  2,  0,  0,  0, &
         0,  0,  1, -1,  1,  0,  3, -6,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  1,  0, -3,  4,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -3,  5,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0, -3,  5,  0,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=211,220) / &
         0,  0,  2, -2,  2,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -3,  5,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2, -4,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  0,  1, -4,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  2, -4,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -2,  4,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  0, -3,  4,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -2,  4,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0, -2,  4,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -5,  8,  0,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=221,230) / &
         0,  0,  2, -2,  2,  0, -5,  6,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -5,  8,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -5,  8,  0,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0, -5,  7,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -5,  8,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  5, -8,  0,  0,  0,  0,  0,  0, &
         0,  0,  1, -1,  2,  0,  0, -1,  0, -1,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0,  0,  0, -1,  0,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  0, -2,  0,  1,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=231,240) / &
         0,  0,  0,  0,  0,  0,  0, -6, 11,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  6,-11,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0, -1,  0,  4,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  1,  0, -4,  0,  0,  0,  0,  0,  0, &
         2,  0,  0, -2,  1,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  2,  0,  0, -2,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  0, -7,  9,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  4, -5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  1 /
data ((napl(i,j), i=1,14), j=241,250) / &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  2,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  2, &
         0,  0,  2, -2,  2,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  2, &
         0,  0,  0,  0,  1,  0,  3, -5,  0,  0,  0,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  3, -4,  0,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0,  2, -4,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  0, -4,  4,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=251,260) / &
         0,  0,  1, -1,  2,  0, -5,  7,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  3, -6,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -3,  6,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  0, -4,  6,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -3,  6,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0, -3,  6,  0,  0,  0,  0,  2, &
         0,  0, -1,  1,  0,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  2, -3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -5,  9,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -5,  9,  0,  0,  0,  0,  1 /
data ((napl(i,j), i=1,14), j=261,270) / &
         0,  0,  0,  0,  0,  0,  0,  5, -9,  0,  0,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  0,  1,  0, -2,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
        -2,  0,  1,  1,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
         0,  0, -2,  2,  0,  0,  3, -3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -6, 10,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0, -6, 10,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -2,  3,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -2,  3,  0,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0, -2,  2,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=271,280) / &
         0,  0,  0,  0,  0,  0,  2, -3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  2, -3,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  0, -1,  0,  3,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  4, -8,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -4,  8,  0,  0,  0,  0,  2, &
         0,  0, -2,  2,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -4,  7,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=281,290) / &
         0,  0,  0,  0,  0,  0,  0, -4,  7,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  4, -7,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0, -2,  3,  0,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -5, 10,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  1,  0, -1,  2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -3,  5,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -3,  5,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  3, -5,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=291,300) / &
         0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  1, -3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  1, -2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -1,  2,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0, -1,  2,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -7, 11,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -7, 11,  0,  0,  0,  0,  0,  1, &
         0,  0, -2,  2,  0,  0,  4, -4,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  2, -3,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0, -4,  4,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=301,310) / &
         0,  0, -1,  1,  0,  0,  4, -5,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -4,  7,  0,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0, -4,  6,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -4,  7,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -4,  6,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -4,  6,  0,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0, -4,  5,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -4,  6,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  4, -6,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=311,320) / &
        -2,  0,  0,  2,  0,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0, &
         0,  0, -1,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -1,  0,  5,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  1, -3,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -1,  3,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -7, 12,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -1,  1,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -1,  1,  0,  0,  0,  0,  0,  1 /
data ((napl(i,j), i=1,14), j=321,330) / &
         0,  0,  1, -1,  1,  0, -1,  0,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  1, -2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -2,  5,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -1,  0,  4,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  1,  0, -4,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0, -1,  1,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -6, 10,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -6, 10,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=331,340) / &
         0,  0,  2, -2,  1,  0,  0, -3,  0,  3,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -3,  7,  0,  0,  0,  0,  2, &
        -2,  0,  0,  2,  0,  0,  4, -4,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -5,  8,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  5, -8,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -1,  0,  3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -1,  0,  3,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  1,  0, -3,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  2, -4,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -2,  4,  0,  0,  0,  0,  0,  1 /
data ((napl(i,j), i=1,14), j=341,350) / &
         0,  0,  1, -1,  1,  0, -2,  3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -2,  4,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -6,  9,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -6,  9,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  6, -9,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0,  1,  0, -2,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0, -2,  2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -4,  6,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  4, -6,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  3, -4,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=351,360) / &
         0,  0,  0,  0,  0,  0,  0, -1,  0,  2,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  1,  0, -2,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -5,  9,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  3, -4,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -3,  4,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -3,  4,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  3, -4,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  3, -4,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  1,  0,  0,  2, -2,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=361,370) / &
         0,  0,  0,  0,  1,  0,  0, -1,  0,  2,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  0, -3,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  1, -5,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -1,  0,  1,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  1,  0, -1,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  1,  0, -3,  5,  0,  0,  0, &
         0,  0,  0,  0,  1,  0, -3,  4,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  0, -2,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  2, -2,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=371,380) / &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  0, -1,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0, -2,  2,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -8, 14,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  2, -5,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  5, -8,  3,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  5, -8,  3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  3, -8,  3,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=381,390) / &
         0,  0,  0,  0,  0,  0,  0, -3,  8, -3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  1,  0, -2,  5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -8, 12,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -8, 12,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  1, -2,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  2,  0,  0,  2, &
         0,  0,  2, -2,  1,  0, -5,  5,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=391,400) / &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  3, -6,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -3,  6,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0, -3,  6,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -1,  4,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -5,  7,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -5,  7,  0,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0, -5,  6,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=401,410) / &
         0,  0,  0,  0,  0,  0,  5, -7,  0,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
         0,  0,  0,  0,  0, -1,  0,  3,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  2,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -2,  6,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  1,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -6,  9,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  6, -9,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -2,  2,  0,  0,  0,  0,  0,  1 /
data ((napl(i,j), i=1,14), j=411,420) / &
         0,  0,  1, -1,  1,  0, -2,  1,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  2, -2,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  1,  0,  3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -5,  7,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  5, -7,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0, -2,  2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  4, -5,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  1, -3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -1,  3,  0,  0,  0,  0,  0,  1 /
data ((napl(i,j), i=1,14), j=421,430) / &
         0,  0,  1, -1,  1,  0, -1,  2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -1,  3,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -7, 10,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -7, 10,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  3, -3,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -4,  8,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -4,  5,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -4,  5,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  4, -5,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=431,440) / &
         0,  0,  0,  0,  0,  0,  0, -2,  0,  5,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -9, 13,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -1,  5,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -2,  0,  4,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0, -4,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -2,  7,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0, -3,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=441,450) / &
         0,  0,  0,  0,  0,  0, -2,  5,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0, -2,  5,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -6,  8,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -6,  8,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  6, -8,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  1,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0, -3,  9,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  5, -6,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  5, -6,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=451,460) / &
         0,  0,  0,  0,  0,  0,  0,  2,  0, -2,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  2,  0, -2,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -5, 10,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  4, -4,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  4, -4,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -3,  3,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  3, -3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  3, -3,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  3, -3,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0, -3,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=461,470) / &
         0,  0,  0,  0,  0,  0,  0, -5, 13,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0, -1,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  2,  0, -1,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0, -2,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0, -2,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  3, -2,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  3, -2,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0, -1,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -6, 15,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -8, 15,  0,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=471,480) / &
         0,  0,  0,  0,  0,  0, -3,  9, -4,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  2, -5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -2,  8, -1, -5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  6, -8,  3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  1, &
         0,  0,  1, -1,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=481,490) / &
         0,  0,  0,  0,  0,  0,  0, -6, 16, -4, -5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -2,  8, -3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -2,  8, -3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  6, -8,  1,  5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0, -2,  5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  3, -5,  4,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -8, 11,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -8, 11,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0, -8, 11,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=491,500) / &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  1,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  3, -3,  0,  2,  0,  0,  0,  2, &
         0,  0,  2, -2,  1,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
         0,  0,  1, -1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  1,  2,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  1,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -3,  7,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -5,  6,  0,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=501,510) / &
         0,  0,  0,  0,  0,  0, -5,  6,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  5, -6,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  5, -6,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  0,  2,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -1,  6,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  7, -9,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  2, -1,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  2, -1,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  6, -7,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  5, -5,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=511,520) / &
         0,  0,  0,  0,  0,  0, -1,  4,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0, -1,  4,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -7,  9,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -7,  9,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  4, -3,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  3, -1,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -4,  4,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  4, -4,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  4, -4,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  4, -4,  0,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=521,530) / &
         0,  0,  0,  0,  0,  0,  0,  2,  1,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -3,  0,  5,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -9, 12,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  3,  0, -4,  0,  0,  0,  0, &
         0,  0,  2, -2,  1,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  7, -8,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  3,  0, -3,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=531,540) / &
         0,  0,  0,  0,  0,  0,  0,  3,  0, -3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -2,  6,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -6,  7,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  6, -7,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  6, -6,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  3,  0, -2,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  3,  0, -2,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  5, -4,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  3, -2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  3, -2,  0,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=541,550) / &
         0,  0,  0,  0,  0,  0,  0,  3,  0, -1,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  3,  0, -1,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  3,  0,  0, -2,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  4, -2,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  3,  0,  0, -1,  0,  0,  2, &
         0,  0,  2, -2,  1,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0, -8, 16,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  3,  0,  2, -5,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  7, -8,  3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -5, 16, -4, -5,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=551,560) / &
         0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0, -1,  8, -3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -8, 10,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -8, 10,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0, -8, 10,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  2,  2,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  3,  0,  1,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -3,  8,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -5,  5,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  5, -5,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=561,570) / &
         0,  0,  0,  0,  0,  0,  5, -5,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  5, -5,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  7, -7,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  7, -7,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  6, -5,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  7, -8,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  5, -3,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=571,580) / &
         0,  0,  0,  0,  0,  0,  4, -3,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  1,  2,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -9, 11,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -9, 11,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  4,  0, -4,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  4,  0, -3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -6,  6,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  6, -6,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  6, -6,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  4,  0, -2,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=581,590) / &
         0,  0,  0,  0,  0,  0,  0,  6, -4,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  3, -1,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  3, -1,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  3, -1,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  4,  0, -1,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  4,  0,  0, -2,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  5, -2,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  8, -9,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  5, -4,  0,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=591,600) / &
         0,  0,  0,  0,  0,  0,  2,  1,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  2,  1,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  2,  1,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0, -7,  7,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  7, -7,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  4, -2,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  4, -2,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  4, -2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  4, -2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  5,  0, -4,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=601,610) / &
         0,  0,  0,  0,  0,  0,  0,  5,  0, -3,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  5,  0, -2,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -8,  8,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  8, -8,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  5, -3,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  5, -3,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0, -9,  9,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0, -9,  9,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0, -9,  9,  0,  0,  0,  0,  0,  1 /
data ((napl(i,j), i=1,14), j=611,620) / &
         0,  0,  0,  0,  0,  0,  9, -9,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  6, -4,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  2, &
         0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  1, &
         0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  2 /
data ((napl(i,j), i=1,14), j=621,630) / &
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2, &
         1,  0,  0, -2,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
         1,  0,  0, -2,  0,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
         1,  0,  0, -2,  0,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
         1,  0,  0, -2,  0,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
        -1,  0,  0,  0,  0,  0,  3, -3,  0,  0,  0,  0,  0,  0, &
        -1,  0,  0,  0,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
        -1,  0,  0,  2,  0,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
         1,  0,  0, -2,  0,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
        -2,  0,  0,  2,  0,  0,  0,  4, -8,  3,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=631,640) / &
        -1,  0,  0,  0,  0,  0,  0,  2,  0, -3,  0,  0,  0,  0, &
        -1,  0,  0,  0,  0,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
        -1,  0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
        -1,  0,  0,  2,  0,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
         1,  0, -1,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
        -1,  0,  0,  2,  0,  0,  0,  2,  0, -3,  0,  0,  0,  0, &
        -2,  0,  0,  0,  0,  0,  0,  2,  0, -3,  0,  0,  0,  0, &
         1,  0,  0,  0,  0,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
        -1,  0,  1, -1,  1,  0,  0, -1,  0,  0,  0,  0,  0,  0, &
         1,  0,  1, -1,  1,  0,  0, -1,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=641,650) / &
        -1,  0,  0,  0,  0,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
        -1,  0,  0,  2,  1,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
         0,  0,  0,  0,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
        -1,  0,  0,  2,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
        -1,  0,  0,  2,  0,  0,  3, -3,  0,  0,  0,  0,  0,  0, &
         1,  0,  0, -2,  1,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
         1,  0,  2, -2,  2,  0, -3,  3,  0,  0,  0,  0,  0,  0, &
         1,  0,  2, -2,  2,  0,  0, -2,  0,  2,  0,  0,  0,  0, &
         1,  0,  0,  0,  0,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
         1,  0,  0,  0,  0,  0,  0,  1,  0, -1,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=651,660) / &
         0,  0,  0, -2,  0,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
         0,  0,  0, -2,  0,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
         0,  0,  2,  0,  2,  0, -2,  2,  0,  0,  0,  0,  0,  0, &
         0,  0,  2,  0,  2,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
         0,  0,  2,  0,  2,  0, -1,  1,  0,  0,  0,  0,  0,  0, &
         0,  0,  2,  0,  2,  0, -2,  3,  0,  0,  0,  0,  0,  0, &
         0,  0,  0,  2,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
         0,  0,  1,  1,  2,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
         1,  0,  2,  0,  2,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
        -1,  0,  2,  0,  2,  0, 10, -3,  0,  0,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=661,670) / &
         0,  0,  1,  1,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
         1,  0,  2,  0,  2,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
         0,  0,  2,  0,  2,  0,  0,  4, -8,  3,  0,  0,  0,  0, &
         0,  0,  2,  0,  2,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
        -1,  0,  2,  0,  2,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
         2,  0,  2, -2,  2,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
         1,  0,  2,  0,  1,  0,  0, -2,  0,  3,  0,  0,  0,  0, &
         0,  0,  1,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
        -1,  0,  2,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
        -2,  0,  2,  2,  2,  0,  0,  2,  0, -2,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=671,680) / &
         0,  0,  2,  0,  2,  0,  2, -3,  0,  0,  0,  0,  0,  0, &
         0,  0,  2,  0,  2,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
         0,  0,  2,  0,  2,  0,  0,  1,  0, -1,  0,  0,  0,  0, &
         0,  0,  2,  0,  2,  0,  2, -2,  0,  0,  0,  0,  0,  0, &
        -1,  0,  2,  2,  2,  0,  0, -1,  0,  1,  0,  0,  0,  0, &
         1,  0,  2,  0,  2,  0, -1,  1,  0,  0,  0,  0,  0,  0, &
        -1,  0,  2,  2,  2,  0,  0,  2,  0, -3,  0,  0,  0,  0, &
         2,  0,  2,  0,  2,  0,  0,  2,  0, -3,  0,  0,  0,  0, &
         1,  0,  2,  0,  2,  0,  0, -4,  8, -3,  0,  0,  0,  0, &
         1,  0,  2,  0,  2,  0,  0,  4, -8,  3,  0,  0,  0,  0 /
data ((napl(i,j), i=1,14), j=681,687) / &
         1,  0,  1,  1,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
         0,  0,  2,  0,  2,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
         2,  0,  2,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
        -1,  0,  2,  2,  2,  0,  0,  2,  0, -2,  0,  0,  0,  0, &
        -1,  0,  2,  2,  2,  0,  3, -3,  0,  0,  0,  0,  0,  0, &
         1,  0,  2,  0,  2,  0,  1, -1,  0,  0,  0,  0,  0,  0, &
         0,  0,  2,  2,  2,  0,  0,  2,  0, -2,  0,  0,  0,  0 /
!
!  Planetary nutation coefficients, unit 1e-7 arcsec:
!  longitude (sin, cos), obliquity (sin, cos)
!
data ((icpl(i,j), i=1,4), j=  1, 10) / &
       1440,          0,          0,          0, &
         56,       -117,        -42,        -40, &
        125,        -43,          0,        -54, &
          0,          5,          0,          0, &
          3,         -7,         -3,          0, &
          3,          0,          0,         -2, &
       -114,          0,          0,         61, &
       -219,         89,          0,          0, &
         -3,          0,          0,          0, &
       -462,       1604,          0,          0 /
data ((icpl(i,j), i=1,4), j= 11, 20) / &
         99,          0,          0,        -53, &
         -3,          0,          0,          2, &
          0,          6,          2,          0, &
          3,          0,          0,          0, &
        -12,          0,          0,          0, &
         14,       -218,        117,          8, &
         31,       -481,       -257,        -17, &
       -491,        128,          0,          0, &
      -3084,       5123,       2735,       1647, &
      -1444,       2409,      -1286,       -771 /
data ((icpl(i,j), i=1,4), j= 21, 30) / &
         11,        -24,        -11,         -9, &
         26,         -9,          0,          0, &
        103,        -60,          0,          0, &
          0,        -13,         -7,          0, &
        -26,        -29,        -16,         14, &
          9,        -27,        -14,         -5, &
         12,          0,          0,         -6, &
         -7,          0,          0,          0, &
          0,         24,          0,          0, &
        284,          0,          0,       -151 /
data ((icpl(i,j), i=1,4), j= 31, 40) / &
        226,        101,          0,          0, &
          0,         -8,         -2,          0, &
          0,         -6,         -3,          0, &
          5,          0,          0,         -3, &
        -41,        175,         76,         17, &
          0,         15,          6,          0, &
        425,        212,       -133,        269, &
       1200,        598,        319,       -641, &
        235,        334,          0,          0, &
         11,        -12,         -7,         -6 /
data ((icpl(i,j), i=1,4), j= 41, 50) / &
          5,         -6,          3,          3, &
         -5,          0,          0,          3, &
          6,          0,          0,         -3, &
         15,          0,          0,          0, &
         13,          0,          0,         -7, &
         -6,         -9,          0,          0, &
        266,        -78,          0,          0, &
       -460,       -435,       -232,        246, &
          0,         15,          7,          0, &
         -3,          0,          0,          2 /
data ((icpl(i,j), i=1,4), j= 51, 60) / &
          0,        131,          0,          0, &
          4,          0,          0,          0, &
          0,          3,          0,          0, &
          0,          4,          2,          0, &
          0,          3,          0,          0, &
        -17,        -19,        -10,          9, &
         -9,        -11,          6,         -5, &
         -6,          0,          0,          3, &
        -16,          8,          0,          0, &
          0,          3,          0,          0 /
data ((icpl(i,j), i=1,4), j= 61, 70) / &
         11,         24,         11,         -5, &
         -3,         -4,         -2,          1, &
          3,          0,          0,         -1, &
          0,         -8,         -4,          0, &
          0,          3,          0,          0, &
          0,          5,          0,          0, &
          0,          3,          2,          0, &
         -6,          4,          2,          3, &
         -3,         -5,          0,          0, &
         -5,          0,          0,          2 /
data ((icpl(i,j), i=1,4), j= 71, 80) / &
          4,         24,         13,         -2, &
        -42,         20,          0,          0, &
        -10,        233,          0,          0, &
         -3,          0,          0,          1, &
         78,        -18,          0,          0, &
          0,          3,          1,          0, &
          0,         -3,         -1,          0, &
          0,         -4,         -2,          1, &
          0,         -8,         -4,         -1, &
          0,         -5,          3,          0 /
data ((icpl(i,j), i=1,4), j= 81, 90) / &
         -7,          0,          0,          3, &
        -14,          8,          3,          6, &
          0,          8,         -4,          0, &
          0,         19,         10,          0, &
         45,        -22,          0,          0, &
         -3,          0,          0,          0, &
          0,         -3,          0,          0, &
          0,          3,          0,          0, &
          3,          5,          3,         -2, &
         89,        -16,         -9,        -48 /
data ((icpl(i,j), i=1,4), j= 91,100) / &
          0,          3,          0,          0, &
         -3,          7,          4,          2, &
       -349,        -62,          0,          0, &
        -15,         22,          0,          0, &
         -3,          0,          0,          0, &
        -53,          0,          0,          0, &
          5,          0,          0,         -3, &
          0,         -8,          0,          0, &
         15,         -7,         -4,         -8, &
         -3,          0,          0,          1 /
data ((icpl(i,j), i=1,4), j=101,110) / &
        -21,        -78,          0,          0, &
         20,        -70,        -37,        -11, &
          0,          6,          3,          0, &
          5,          3,          2,         -2, &
        -17,         -4,         -2,          9, &
          0,          6,          3,          0, &
         32,         15,         -8,         17, &
        174,         84,         45,        -93, &
         11,         56,          0,          0, &
        -66,        -12,         -6,         35 /
data ((icpl(i,j), i=1,4), j=111,120) / &
         47,          8,          4,        -25, &
          0,          8,          4,          0, &
         10,        -22,        -12,         -5, &
         -3,          0,          0,          2, &
        -24,         12,          0,          0, &
          5,         -6,          0,          0, &
          3,          0,          0,         -2, &
          4,          3,          1,         -2, &
          0,         29,         15,          0, &
         -5,         -4,         -2,          2 /
data ((icpl(i,j), i=1,4), j=121,130) / &
          8,         -3,         -1,         -5, &
          0,         -3,          0,          0, &
         10,          0,          0,          0, &
          3,          0,          0,         -2, &
         -5,          0,          0,          3, &
         46,         66,         35,        -25, &
        -14,          7,          0,          0, &
          0,          3,          2,          0, &
         -5,          0,          0,          0, &
        -68,        -34,        -18,         36 /
data ((icpl(i,j), i=1,4), j=131,140) / &
          0,         14,          7,          0, &
         10,         -6,         -3,         -5, &
         -5,         -4,         -2,          3, &
         -3,          5,          2,          1, &
         76,         17,          9,        -41, &
         84,        298,        159,        -45, &
          3,          0,          0,         -1, &
         -3,          0,          0,          2, &
         -3,          0,          0,          1, &
        -82,        292,        156,         44 /
data ((icpl(i,j), i=1,4), j=141,150) / &
        -73,         17,          9,         39, &
         -9,        -16,          0,          0, &
          3,          0,         -1,         -2, &
         -3,          0,          0,          0, &
         -9,         -5,         -3,          5, &
       -439,          0,          0,          0, &
         57,        -28,        -15,        -30, &
          0,         -6,         -3,          0, &
         -4,          0,          0,          2, &
        -40,         57,         30,         21 /
data ((icpl(i,j), i=1,4), j=151,160) / &
         23,          7,          3,        -13, &
        273,         80,         43,       -146, &
       -449,        430,          0,          0, &
         -8,        -47,        -25,          4, &
          6,         47,         25,         -3, &
          0,         23,         13,          0, &
         -3,          0,          0,          2, &
          3,         -4,         -2,         -2, &
        -48,       -110,        -59,         26, &
         51,        114,         61,        -27 /
data ((icpl(i,j), i=1,4), j=161,170) / &
       -133,          0,          0,         57, &
          0,          4,          0,          0, &
        -21,         -6,         -3,         11, &
          0,         -3,         -1,          0, &
        -11,        -21,        -11,          6, &
        -18,       -436,       -233,          9, &
         35,         -7,          0,          0, &
          0,          5,          3,          0, &
         11,         -3,         -1,         -6, &
         -5,         -3,         -1,          3 /
data ((icpl(i,j), i=1,4), j=171,180) / &
        -53,         -9,         -5,         28, &
          0,          3,          2,          1, &
          4,          0,          0,         -2, &
          0,         -4,          0,          0, &
        -50,        194,        103,         27, &
        -13,         52,         28,          7, &
        -91,        248,          0,          0, &
          6,         49,         26,         -3, &
         -6,        -47,        -25,          3, &
          0,          5,          3,          0 /
data ((icpl(i,j), i=1,4), j=181,190) / &
         52,         23,         10,        -23, &
         -3,          0,          0,          1, &
          0,          5,          3,          0, &
         -4,          0,          0,          0, &
         -4,          8,          3,          2, &
         10,          0,          0,          0, &
          3,          0,          0,         -2, &
          0,          8,          4,          0, &
          0,          8,          4,          1, &
         -4,          0,          0,          0 /
data ((icpl(i,j), i=1,4), j=191,200) / &
         -4,          0,          0,          0, &
         -8,          4,          2,          4, &
          8,         -4,         -2,         -4, &
          0,         15,          7,          0, &
       -138,          0,          0,          0, &
          0,         -7,         -3,          0, &
          0,         -7,         -3,          0, &
         54,          0,          0,        -29, &
          0,         10,          4,          0, &
         -7,          0,          0,          3 /
data ((icpl(i,j), i=1,4), j=201,210) / &
        -37,         35,         19,         20, &
          0,          4,          0,          0, &
         -4,          9,          0,          0, &
          8,          0,          0,         -4, &
         -9,        -14,         -8,          5, &
         -3,         -9,         -5,          3, &
       -145,         47,          0,          0, &
        -10,         40,         21,          5, &
         11,        -49,        -26,         -7, &
      -2150,          0,          0,        932 /
data ((icpl(i,j), i=1,4), j=211,220) / &
        -12,          0,          0,          5, &
         85,          0,          0,        -37, &
          4,          0,          0,         -2, &
          3,          0,          0,         -2, &
        -86,        153,          0,          0, &
         -6,          9,          5,          3, &
          9,        -13,         -7,         -5, &
         -8,         12,          6,          4, &
        -51,          0,          0,         22, &
        -11,       -268,       -116,          5 /
data ((icpl(i,j), i=1,4), j=221,230) / &
          0,         12,          5,          0, &
          0,          7,          3,          0, &
         31,          6,          3,        -17, &
        140,         27,         14,        -75, &
         57,         11,          6,        -30, &
        -14,        -39,          0,          0, &
          0,         -6,         -2,          0, &
          4,         15,          8,         -2, &
          0,          4,          0,          0, &
         -3,          0,          0,          1 /
data ((icpl(i,j), i=1,4), j=231,240) / &
          0,         11,          5,          0, &
          9,          6,          0,          0, &
         -4,         10,          4,          2, &
          5,          3,          0,          0, &
         16,          0,          0,         -9, &
         -3,          0,          0,          0, &
          0,          3,          2,         -1, &
          7,          0,          0,         -3, &
        -25,         22,          0,          0, &
         42,        223,        119,        -22 /
data ((icpl(i,j), i=1,4), j=241,250) / &
        -27,       -143,        -77,         14, &
          9,         49,         26,         -5, &
      -1166,          0,          0,        505, &
         -5,          0,          0,          2, &
         -6,          0,          0,          3, &
         -8,          0,          1,          4, &
          0,         -4,          0,          0, &
        117,          0,          0,        -63, &
         -4,          8,          4,          2, &
          3,          0,          0,         -2 /
data ((icpl(i,j), i=1,4), j=251,260) / &
         -5,          0,          0,          2, &
          0,         31,          0,          0, &
         -5,          0,          1,          3, &
          4,          0,          0,         -2, &
         -4,          0,          0,          2, &
        -24,        -13,         -6,         10, &
          3,          0,          0,          0, &
          0,        -32,        -17,          0, &
          8,         12,          5,         -3, &
          3,          0,          0,         -1 /
data ((icpl(i,j), i=1,4), j=261,270) / &
          7,         13,          0,          0, &
         -3,         16,          0,          0, &
         50,          0,          0,        -27, &
          0,         -5,         -3,          0, &
         13,          0,          0,          0, &
          0,          5,          3,          1, &
         24,          5,          2,        -11, &
          5,        -11,         -5,         -2, &
         30,         -3,         -2,        -16, &
         18,          0,          0,         -9 /
data ((icpl(i,j), i=1,4), j=271,280) / &
          8,        614,          0,          0, &
          3,         -3,         -1,         -2, &
          6,         17,          9,         -3, &
         -3,         -9,         -5,          2, &
          0,          6,          3,         -1, &
       -127,         21,          9,         55, &
          3,          5,          0,          0, &
         -6,        -10,         -4,          3, &
          5,          0,          0,          0, &
         16,          9,          4,         -7 /
data ((icpl(i,j), i=1,4), j=281,290) / &
          3,          0,          0,         -2, &
          0,         22,          0,          0, &
          0,         19,         10,          0, &
          7,          0,          0,         -4, &
          0,         -5,         -2,          0, &
          0,          3,          1,          0, &
         -9,          3,          1,          4, &
         17,          0,          0,         -7, &
          0,         -3,         -2,         -1, &
        -20,         34,          0,          0 /
data ((icpl(i,j), i=1,4), j=291,300) / &
        -10,          0,          1,          5, &
         -4,          0,          0,          2, &
         22,        -87,          0,          0, &
         -4,          0,          0,          2, &
         -3,         -6,         -2,          1, &
        -16,         -3,         -1,          7, &
          0,         -3,         -2,          0, &
          4,          0,          0,          0, &
        -68,         39,          0,          0, &
         27,          0,          0,        -14 /
data ((icpl(i,j), i=1,4), j=301,310) / &
          0,         -4,          0,          0, &
        -25,          0,          0,          0, &
        -12,         -3,         -2,          6, &
          3,          0,          0,         -1, &
          3,         66,         29,         -1, &
        490,          0,          0,       -213, &
        -22,         93,         49,         12, &
         -7,         28,         15,          4, &
         -3,         13,          7,          2, &
        -46,         14,          0,          0 /
data ((icpl(i,j), i=1,4), j=311,320) / &
         -5,          0,          0,          0, &
          2,          1,          0,          0, &
          0,         -3,          0,          0, &
        -28,          0,          0,         15, &
          5,          0,          0,         -2, &
          0,          3,          0,          0, &
        -11,          0,          0,          5, &
          0,          3,          1,          0, &
         -3,          0,          0,          1, &
         25,        106,         57,        -13 /
data ((icpl(i,j), i=1,4), j=321,330) / &
          5,         21,         11,         -3, &
       1485,          0,          0,          0, &
         -7,        -32,        -17,          4, &
          0,          5,          3,          0, &
         -6,         -3,         -2,          3, &
         30,         -6,         -2,        -13, &
         -4,          4,          0,          0, &
        -19,          0,          0,         10, &
          0,          4,          2,         -1, &
          0,          3,          0,          0 /
data ((icpl(i,j), i=1,4), j=331,340) / &
          4,          0,          0,         -2, &
          0,         -3,         -1,          0, &
         -3,          0,          0,          0, &
          5,          3,          1,         -2, &
          0,         11,          0,          0, &
        118,          0,          0,        -52, &
          0,         -5,         -3,          0, &
        -28,         36,          0,          0, &
          5,         -5,          0,          0, &
         14,        -59,        -31,         -8 /
data ((icpl(i,j), i=1,4), j=341,350) / &
          0,          9,          5,          1, &
       -458,          0,          0,        198, &
          0,        -45,        -20,          0, &
          9,          0,          0,         -5, &
          0,         -3,          0,          0, &
          0,         -4,         -2,         -1, &
         11,          0,          0,         -6, &
          6,          0,          0,         -2, &
        -16,         23,          0,          0, &
          0,         -4,         -2,          0 /
data ((icpl(i,j), i=1,4), j=351,360) / &
         -5,          0,          0,          2, &
       -166,        269,          0,          0, &
         15,          0,          0,         -8, &
         10,          0,          0,         -4, &
        -78,         45,          0,          0, &
          0,         -5,         -2,          0, &
          7,          0,          0,         -4, &
         -5,        328,          0,          0, &
          3,          0,          0,         -2, &
          5,          0,          0,         -2 /
data ((icpl(i,j), i=1,4), j=361,370) / &
          0,          3,          1,          0, &
         -3,          0,          0,          0, &
         -3,          0,          0,          0, &
          0,         -4,         -2,          0, &
      -1223,        -26,          0,          0, &
          0,          7,          3,          0, &
          3,          0,          0,          0, &
          0,          3,          2,          0, &
         -6,         20,          0,          0, &
       -368,          0,          0,          0 /
data ((icpl(i,j), i=1,4), j=371,380) / &
        -75,          0,          0,          0, &
         11,          0,          0,         -6, &
          3,          0,          0,         -2, &
         -3,          0,          0,          1, &
        -13,        -30,          0,          0, &
         21,          3,          0,          0, &
         -3,          0,          0,          1, &
         -4,          0,          0,          2, &
          8,        -27,          0,          0, &
        -19,        -11,          0,          0 /
data ((icpl(i,j), i=1,4), j=381,390) / &
         -4,          0,          0,          2, &
          0,          5,          2,          0, &
         -6,          0,          0,          2, &
         -8,          0,          0,          0, &
         -1,          0,          0,          0, &
        -14,          0,          0,          6, &
          6,          0,          0,          0, &
        -74,          0,          0,         32, &
          0,         -3,         -1,          0, &
          4,          0,          0,         -2 /
data ((icpl(i,j), i=1,4), j=391,400) / &
          8,         11,          0,          0, &
          0,          3,          2,          0, &
       -262,          0,          0,        114, &
          0,         -4,          0,          0, &
         -7,          0,          0,          4, &
          0,        -27,        -12,          0, &
        -19,         -8,         -4,          8, &
        202,          0,          0,        -87, &
         -8,         35,         19,          5, &
          0,          4,          2,          0 /
data ((icpl(i,j), i=1,4), j=401,410) / &
         16,         -5,          0,          0, &
          5,          0,          0,         -3, &
          0,         -3,          0,          0, &
          1,          0,          0,          0, &
        -35,        -48,        -21,         15, &
         -3,         -5,         -2,          1, &
          6,          0,          0,         -3, &
          3,          0,          0,         -1, &
          0,         -5,          0,          0, &
         12,         55,         29,         -6 /
data ((icpl(i,j), i=1,4), j=411,420) / &
          0,          5,          3,          0, &
       -598,          0,          0,          0, &
         -3,        -13,         -7,          1, &
         -5,         -7,         -3,          2, &
          3,          0,          0,         -1, &
          5,         -7,          0,          0, &
          4,          0,          0,         -2, &
         16,         -6,          0,          0, &
          8,         -3,          0,          0, &
          8,        -31,        -16,         -4 /
data ((icpl(i,j), i=1,4), j=421,430) / &
          0,          3,          1,          0, &
        113,          0,          0,        -49, &
          0,        -24,        -10,          0, &
          4,          0,          0,         -2, &
         27,          0,          0,          0, &
         -3,          0,          0,          1, &
          0,         -4,         -2,          0, &
          5,          0,          0,         -2, &
          0,         -3,          0,          0, &
        -13,          0,          0,          6 /
data ((icpl(i,j), i=1,4), j=431,440) / &
          5,          0,          0,         -2, &
        -18,        -10,         -4,          8, &
         -4,        -28,          0,          0, &
         -5,          6,          3,          2, &
         -3,          0,          0,          1, &
         -5,         -9,         -4,          2, &
         17,          0,          0,         -7, &
         11,          4,          0,          0, &
          0,         -6,         -2,          0, &
         83,         15,          0,          0 /
data ((icpl(i,j), i=1,4), j=441,450) / &
         -4,          0,          0,          2, &
          0,       -114,        -49,          0, &
        117,          0,          0,        -51, &
         -5,         19,         10,          2, &
         -3,          0,          0,          0, &
         -3,          0,          0,          2, &
          0,         -3,         -1,          0, &
          3,          0,          0,          0, &
          0,         -6,         -2,          0, &
        393,          3,          0,          0 /
data ((icpl(i,j), i=1,4), j=451,460) / &
         -4,         21,         11,          2, &
         -6,          0,         -1,          3, &
         -3,          8,          4,          1, &
          8,          0,          0,          0, &
         18,        -29,        -13,         -8, &
          8,         34,         18,         -4, &
         89,          0,          0,          0, &
          3,         12,          6,         -1, &
         54,        -15,         -7,        -24, &
          0,          3,          0,          0 /
data ((icpl(i,j), i=1,4), j=461,470) / &
          3,          0,          0,         -1, &
          0,         35,          0,          0, &
       -154,        -30,        -13,         67, &
         15,          0,          0,          0, &
          0,          4,          2,          0, &
          0,          9,          0,          0, &
         80,        -71,        -31,        -35, &
          0,        -20,         -9,          0, &
         11,          5,          2,         -5, &
         61,        -96,        -42,        -27 /
data ((icpl(i,j), i=1,4), j=471,480) / &
         14,          9,          4,         -6, &
        -11,         -6,         -3,          5, &
          0,         -3,         -1,          0, &
        123,       -415,       -180,        -53, &
          0,          0,          0,        -35, &
         -5,          0,          0,          0, &
          7,        -32,        -17,         -4, &
          0,         -9,         -5,          0, &
          0,         -4,          2,          0, &
        -89,          0,          0,         38 /
data ((icpl(i,j), i=1,4), j=481,490) / &
          0,        -86,        -19,         -6, &
          0,          0,        -19,          6, &
       -123,       -416,       -180,         53, &
          0,         -3,         -1,          0, &
         12,         -6,         -3,         -5, &
        -13,          9,          4,          6, &
          0,        -15,         -7,          0, &
          3,          0,          0,         -1, &
        -62,        -97,        -42,         27, &
        -11,          5,          2,          5 /
data ((icpl(i,j), i=1,4), j=491,500) / &
          0,        -19,         -8,          0, &
         -3,          0,          0,          1, &
          0,          4,          2,          0, &
          0,          3,          0,          0, &
          0,          4,          2,          0, &
        -85,        -70,        -31,         37, &
        163,        -12,         -5,        -72, &
        -63,        -16,         -7,         28, &
        -21,        -32,        -14,          9, &
          0,         -3,         -1,          0 /
data ((icpl(i,j), i=1,4), j=501,510) / &
          3,          0,          0,         -2, &
          0,          8,          0,          0, &
          3,         10,          4,         -1, &
          3,          0,          0,         -1, &
          0,         -7,         -3,          0, &
          0,         -4,         -2,          0, &
          6,         19,          0,          0, &
          5,       -173,        -75,         -2, &
          0,         -7,         -3,          0, &
          7,        -12,         -5,         -3 /
data ((icpl(i,j), i=1,4), j=511,520) / &
         -3,          0,          0,          2, &
          3,         -4,         -2,         -1, &
         74,          0,          0,        -32, &
         -3,         12,          6,          2, &
         26,        -14,         -6,        -11, &
         19,          0,          0,         -8, &
          6,         24,         13,         -3, &
         83,          0,          0,          0, &
          0,        -10,         -5,          0, &
         11,         -3,         -1,         -5 /
data ((icpl(i,j), i=1,4), j=521,530) / &
          3,          0,          1,         -1, &
          3,          0,          0,         -1, &
         -4,          0,          0,          0, &
          5,        -23,        -12,         -3, &
       -339,          0,          0,        147, &
          0,        -10,         -5,          0, &
          5,          0,          0,          0, &
          3,          0,          0,         -1, &
          0,         -4,         -2,          0, &
         18,         -3,          0,          0 /
data ((icpl(i,j), i=1,4), j=531,540) / &
          9,        -11,         -5,         -4, &
         -8,          0,          0,          4, &
          3,          0,          0,         -1, &
          0,          9,          0,          0, &
          6,         -9,         -4,         -2, &
         -4,        -12,          0,          0, &
         67,        -91,        -39,        -29, &
         30,        -18,         -8,        -13, &
          0,          0,          0,          0, &
          0,       -114,        -50,          0 /
data ((icpl(i,j), i=1,4), j=541,550) / &
          0,          0,          0,         23, &
        517,         16,          7,       -224, &
          0,         -7,         -3,          0, &
        143,         -3,         -1,        -62, &
         29,          0,          0,        -13, &
         -4,          0,          0,          2, &
         -6,          0,          0,          3, &
          5,         12,          5,         -2, &
        -25,          0,          0,         11, &
         -3,          0,          0,          1 /
data ((icpl(i,j), i=1,4), j=551,560) / &
          0,          4,          2,          0, &
        -22,         12,          5,         10, &
         50,          0,          0,        -22, &
          0,          7,          4,          0, &
          0,          3,          1,          0, &
         -4,          4,          2,          2, &
         -5,        -11,         -5,          2, &
          0,          4,          2,          0, &
          4,         17,          9,         -2, &
         59,          0,          0,          0 /
data ((icpl(i,j), i=1,4), j=561,570) / &
          0,         -4,         -2,          0, &
         -8,          0,          0,          4, &
         -3,          0,          0,          0, &
          4,        -15,         -8,         -2, &
        370,         -8,          0,       -160, &
          0,          0,         -3,          0, &
          0,          3,          1,          0, &
         -6,          3,          1,          3, &
          0,          6,          0,          0, &
        -10,          0,          0,          4 /
data ((icpl(i,j), i=1,4), j=571,580) / &
          0,          9,          4,          0, &
          4,         17,          7,         -2, &
         34,          0,          0,        -15, &
          0,          5,          3,          0, &
         -5,          0,          0,          2, &
        -37,         -7,         -3,         16, &
          3,         13,          7,         -2, &
         40,          0,          0,          0, &
          0,         -3,         -2,          0, &
       -184,         -3,         -1,         80 /
data ((icpl(i,j), i=1,4), j=581,590) / &
         -3,          0,          0,          1, &
         -3,          0,          0,          0, &
          0,        -10,         -6,         -1, &
         31,         -6,          0,        -13, &
         -3,        -32,        -14,          1, &
         -7,          0,          0,          3, &
          0,         -8,         -4,          0, &
          3,         -4,          0,          0, &
          0,          4,          0,          0, &
          0,          3,          1,          0 /
data ((icpl(i,j), i=1,4), j=591,600) / &
         19,        -23,        -10,          2, &
          0,          0,          0,        -10, &
          0,          3,          2,          0, &
          0,          9,          5,         -1, &
         28,          0,          0,          0, &
          0,         -7,         -4,          0, &
          8,         -4,          0,         -4, &
          0,          0,         -2,          0, &
          0,          3,          0,          0, &
         -3,          0,          0,          1 /
data ((icpl(i,j), i=1,4), j=601,610) / &
         -9,          0,          1,          4, &
          3,         12,          5,         -1, &
         17,         -3,         -1,          0, &
          0,          7,          4,          0, &
         19,          0,          0,          0, &
          0,         -5,         -3,          0, &
         14,         -3,          0,         -1, &
          0,          0,         -1,          0, &
          0,          0,          0,         -5, &
          0,          5,          3,          0 /
data ((icpl(i,j), i=1,4), j=611,620) / &
         13,          0,          0,          0, &
          0,         -3,         -2,          0, &
          2,          9,          4,          3, &
          0,          0,          0,         -4, &
          8,          0,          0,          0, &
          0,          4,          2,          0, &
          6,          0,          0,         -3, &
          6,          0,          0,          0, &
          0,          3,          1,          0, &
          5,          0,          0,         -2 /
data ((icpl(i,j), i=1,4), j=621,630) / &
          3,          0,          0,         -1, &
         -3,          0,          0,          0, &
          6,          0,          0,          0, &
          7,          0,          0,          0, &
         -4,          0,          0,          0, &
          4,          0,          0,          0, &
          6,          0,          0,          0, &
          0,         -4,          0,          0, &
          0,         -4,          0,          0, &
          5,          0,          0,          0 /
data ((icpl(i,j), i=1,4), j=631,640) / &
         -3,          0,          0,          0, &
          4,          0,          0,          0, &
         -5,          0,          0,          0, &
          4,          0,          0,          0, &
          0,          3,          0,          0, &
         13,          0,          0,          0, &
         21,         11,          0,          0, &
          0,         -5,          0,          0, &
          0,         -5,         -2,          0, &
          0,          5,          3,          0 /
data ((icpl(i,j), i=1,4), j=641,650) / &
          0,         -5,          0,          0, &
         -3,          0,          0,          2, &
         20,         10,          0,          0, &
        -34,          0,          0,          0, &
        -19,          0,          0,          0, &
          3,          0,          0,         -2, &
         -3,          0,          0,          1, &
         -6,          0,          0,          3, &
         -4,          0,          0,          0, &
          3,          0,          0,          0 /
data ((icpl(i,j), i=1,4), j=651,660) / &
          3,          0,          0,          0, &
          4,          0,          0,          0, &
          3,          0,          0,         -1, &
          6,          0,          0,         -3, &
         -8,          0,          0,          3, &
          0,          3,          1,          0, &
         -3,          0,          0,          0, &
          0,         -3,         -2,          0, &
        126,        -63,        -27,        -55, &
         -5,          0,          1,          2 /
data ((icpl(i,j), i=1,4), j=661,670) / &
         -3,         28,         15,          2, &
          5,          0,          1,         -2, &
          0,          9,          4,          1, &
          0,          9,          4,         -1, &
       -126,        -63,        -27,         55, &
          3,          0,          0,         -1, &
         21,        -11,         -6,        -11, &
          0,         -4,          0,          0, &
        -21,        -11,         -6,         11, &
         -3,          0,          0,          1 /
data ((icpl(i,j), i=1,4), j=671,680) / &
          0,          3,          1,          0, &
          8,          0,          0,         -4, &
         -6,          0,          0,          3, &
         -3,          0,          0,          1, &
          3,          0,          0,         -1, &
         -3,          0,          0,          1, &
         -5,          0,          0,          2, &
         24,        -12,         -5,        -11, &
          0,          3,          1,          0, &
          0,          3,          1,          0 /
data ((icpl(i,j), i=1,4), j=681,687) / &
          0,          3,          2,          0, &
        -24,        -12,         -5,         10, &
          4,          0,         -1,         -2, &
         13,          0,          0,         -6, &
          7,          0,          0,         -3, &
          3,          0,          0,         -1, &
          3,          0,          0,         -1 /
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!  Interval between fundamental epoch J2000.0 and given date (JC).
t = ((date1-dj0) + date2) / djc
!  -------------------
!  LUNI-SOLAR NUTATION
!  -------------------
!
!  Fundamental (Delaunay) arguments from Simon et al. (1994)
!
!  Mean anomaly of the Moon.
el  = mod (485868.249036d0 + &
            t*( 1717915923.2178d0 + &
            t*(         31.8792d0 + &
            t*(          0.051635d0 + &
            t*(        - 0.00024470d0 )))), turnas ) * das2r
!  Mean anomaly of the Sun.
elp = mod (1287104.79305d0 + &
            t*(  129596581.0481d0 + &
            t*(        - 0.5532d0 + &
            t*(          0.000136d0 + &
            t*(        - 0.00001149d0 )))), turnas ) * das2r
!  Mean argument of the latitude of the Moon.
f   = mod (335779.526232d0 + &
            t*( 1739527262.8478d0 + &
            t*(       - 12.7512d0 + &
            t*(       -  0.001037d0 + &
            t*(          0.00000417d0 )))), turnas ) * das2r
!  Mean elongation of the Moon from the Sun.
d   = mod (1072260.70369d0 + &
            t*( 1602961601.2090d0 + &
            t*(        - 6.3706d0 + &
            t*(          0.006593d0 + &
            t*(        - 0.00003169d0 )))), turnas ) * das2r
!  Mean longitude of the ascending node of the Moon.
om  = mod (450160.398036d0 + &
            t*(  - 6962890.5431d0 + &
            t*(          7.4722d0 + &
            t*(          0.007702d0 + &
            t*(        - 0.00005939d0 )))), turnas ) * das2r
!  Initialize the nutation values.
dp = 0d0
de = 0d0
!  Summation of luni-solar nutation series (in reverse order).
do i = nls, 1, -1
!     Argument and functions.
   arg = mod ( dble ( nals(1,i) ) * el  + &
               dble ( nals(2,i) ) * elp + &
               dble ( nals(3,i) ) * f   + &
               dble ( nals(4,i) ) * d   + &
               dble ( nals(5,i) ) * om, d2pi )
   sarg = sin(arg)
   carg = cos(arg)
!     Term.
   dp = dp + ( cls(1,i) + cls(2,i) * t ) * sarg &
           +   cls(3,i)                  * carg
   de = de + ( cls(4,i) + cls(5,i) * t ) * carg &
           +   cls(6,i)                  * sarg
end do
!  Convert from 0.1 microarcsec units to radians.
dpsils = dp * u2r
depsls = de * u2r
!  ------------------
!  PLANETARY NUTATION
!  ------------------
!  Mean anomaly of the Moon.
al   = mod (2.35555598d0 + 8328.6914269554d0 * t, d2pi)
!  Mean anomaly of the Sun.
alsu = mod (6.24006013d0 + 628.301955d0 * t, d2pi)
!  Mean argument of the latitude of the Moon.
af   = mod (1.627905234d0 + 8433.466158131d0 * t, d2pi)
!  Mean elongation of the Moon from the Sun.
ad   = mod (5.198466741d0 + 7771.3771468121d0 * t, d2pi)
!  Mean longitude of the ascending node of the Moon.
aom  = mod (2.18243920d0 - 33.757045d0 * t, d2pi)
!  General accumulated precession in longitude.
apa  = (0.02438175d0 + 0.00000538691d0 * t) * t
!  Planetary longitudes, Mercury through Neptune (Souchay et al. 1999).
alme = mod (4.402608842d0 + 2608.7903141574d0 * t, d2pi)
alve = mod (3.176146697d0 + 1021.3285546211d0 * t, d2pi)
alea = mod (1.753470314d0 +  628.3075849991d0 * t, d2pi)
alma = mod (6.203480913d0 +  334.0612426700d0 * t, d2pi)
alju = mod (0.599546497d0 +   52.9690962641d0 * t, d2pi)
alsa = mod (0.874016757d0 +   21.3299104960d0 * t, d2pi)
alur = mod (5.481293871d0 +    7.4781598567d0 * t, d2pi)
alne = mod (5.321159000d0 +    3.8127774000d0 * t, d2pi)
!  Initialize the nutation values.
dp = 0d0
de = 0d0
!  Summation of planetary nutation series (in reverse order).
do i = npl, 1, -1
!     Argument and functions.
   arg = mod ( dble ( napl( 1,i) ) * al   + &
               dble ( napl( 2,i) ) * alsu + &
               dble ( napl( 3,i) ) * af   + &
               dble ( napl( 4,i) ) * ad   + &
               dble ( napl( 5,i) ) * aom  + &
               dble ( napl( 6,i) ) * alme + &
               dble ( napl( 7,i) ) * alve + &
               dble ( napl( 8,i) ) * alea + &
               dble ( napl( 9,i) ) * alma + &
               dble ( napl(10,i) ) * alju + &
               dble ( napl(11,i) ) * alsa + &
               dble ( napl(12,i) ) * alur + &
               dble ( napl(13,i) ) * alne + &
               dble ( napl(14,i) ) * apa, d2pi )
   sarg = sin(arg)
   carg = cos(arg)
!     Term.
   dp = dp + dble( icpl(1,i)) * sarg + dble( icpl(2,i)) * carg
   de = de + dble( icpl(3,i)) * sarg + dble( icpl(4,i)) * carg
end do
!  Convert from 0.1 microarcsec units to radians.
dpsipl = dp * u2r
depspl = de * u2r
!  -----
!  TOTAL
!  -----
!  Add planetary and luni-solar components.
dpsi = dpsipl + dpsils
deps = depspl + depsls
end subroutine nu2000a
Call graph
nod calls nu2000a
etilt calls nod
nutate calls etilt
eqec calls etilt
eceq calls etilt
geopos calls etilt, nutate, sidtim
eqxra calls etilt
sidtim calls etilt, nutate, eqxra, cioloc, ciobas
cioloc calls eqxra
celter calls nutate, sidtim, cioloc, ciobas
place calls nutate, geopos, cioloc, ciobas
ciobas calls nutate
gcrseq calls nutate, cioloc, ciobas
ciora calls nutate, cioloc, ciobas
tercel calls nutate, sidtim, cioloc, ciobas
eqecl calls eqec
places calls place
mpstar calls place
zdaz calls tercel