nu2000k – NOVAS
nu2000k Subroutine
116 statements
Source File
public subroutine nu2000k(date1, date2, dpsi, deps)
Arguments
Type Intent Optional Attributes Name
double precision :: date1
double precision :: date2
double precision :: dpsi
double precision :: deps
Calls
Called by
Contents
None
Call graph
nu2000k calls funarg
nod calls nu2000k
etilt calls nod
eqxra calls etilt
sidtim calls etilt, eqxra, nutate, ciobas, cioloc
eqec calls etilt
nutate calls etilt
eceq calls etilt
geopos calls etilt, sidtim, nutate
tercel calls sidtim, nutate, ciobas, cioloc
eqecl calls eqec
ciora calls nutate, ciobas, cioloc
ciobas calls nutate
place calls nutate, geopos, ciobas, cioloc
cioloc calls eqxra
gcrseq calls nutate, ciobas, cioloc
celter calls sidtim, nutate, ciobas, cioloc
zdaz calls tercel
places calls place
mpstar calls place