nutate – NOVAS
nutate Subroutine
36 statements
Source File
public subroutine nutate(tjd, pos1, pos2)
THIS SUBROUTINE NUTATES EQUATORIAL RECTANGULAR COORDINATES FROM THE MEAN DYNAMICAL EQUATOR AND EQUINOX OF EPOCH TO THE TRUE EQUATOR AND EQUINOX OF EPOCH. SEE EXPLANATORY SUPPLEMENT TO THE ASTRONOMICAL ALMANAC, PP. 114-115.
   TJD    = TDB JULIAN DATE OF EPOCH (IN)
   POS1   = POSITION VECTOR, GEOCENTRIC EQUATORIAL RECTANGULAR
            COORDINATES, REFERRED TO MEAN DYNAMICAL EQUATOR AND
            EQUINOX OF EPOCH (IN)
   POS2   = POSITION VECTOR, GEOCENTRIC EQUATORIAL RECTANGULAR
            COORDINATES, REFERRED TO TRUE EQUATOR AND EQUINOX
            OF EPOCH (OUT)
NOTE: IF TJD IS NEGATIVE, INVERSE NUTATION (TRUE TO MEAN) IS APPLIED.
Arguments
Type Intent Optional Attributes Name
double precision :: tjd
double precision :: pos1
double precision :: pos2
Calls
Called by
Contents
None
Call graph
nutate calls etilt
etilt calls nod, eect2000, funarg, frame, preces, getmod
nod calls getmod, nu2000a, nu2000k
eect2000 calls anmp
nu2000k calls funarg
celter calls nutate, ciobas, sidtim
place calls nutate, ciobas, geopos
ciobas calls nutate
gcrseq calls nutate, ciobas
ciora calls nutate, ciobas
geopos calls nutate, sidtim
sidtim calls nutate, ciobas
tercel calls nutate, ciobas, sidtim
places calls place
mpstar calls place
zdaz calls tercel