places – NOVAS
places Subroutine
101 statements
Source File
public subroutine places()
THE ENTRIES TO THIS SUBROUTINE PROVIDE 'FRONT ENDS' TO SUBROUTINE PLACE, TAILORED TO SPECIFIC PLACE TYPES. THEY PROVIDE COMPATIBILITY WITH PREVIOUSLY SUPPORTED CALLING SEQUENCES.
Arguments
None
Calls
Call graph
places calls applan, apstar, asplan, asstar, lpplan, lpstar, placst, place, tpplan, tpstar, vpplan, vpstar
place calls aberat, angles, astcon, ciobas, cioloc, dlight, frame, geocen, geopos, grvdef, limang, littim, nutate, preces, propmo, radvl, times, vectrs, setvec, solsys
aberat calls astcon
angles calls setvec
ciobas calls frame, nutate, preces
cioloc calls ciord, eqxra
dlight calls astcon
geocen calls astcon
geopos calls placst, astcon, frame, nutate, preces, eqinox, getdt, etilt, sidtim, terra, resume
grvdef calls astcon, dlight, geocen, solsys, id, grvd
limang calls astcon, dasin
littim calls geocen, solsys
nutate calls etilt
radvl calls astcon
vectrs calls astcon
ciord calls ciofil
eqxra calls etilt
etilt calls frame, preces, celpol, getmod, eect2000, funarg, nod
grvd calls astcon
sidtim calls ciobas, cioloc, frame, nutate, preces, times, getdt, eqxra, etilt, getmod, erot
terra calls astcon
eect2000 calls anmp
nod calls getmod, nu2000a, nu2000k
nu2000k calls funarg