preces – NOVAS
preces Subroutine
53 statements
Source File
public subroutine preces(tjd1, pos1, tjd2, pos2)
THIS SUBROUTINE PRECESSES EQUATORIAL RECTANGULAR COORDINATES FROM ONE EPOCH TO ANOTHER. THE COORDINATES ARE REFERRED TO THE MEAN DYNAMICAL EQUATOR AND EQUINOX OF THE TWO RESPECTIVE EPOCHS. SEE EXPLANATORY SUPPLEMENT TO THE ASTRONOMICAL ALMANAC, PP. 103-104, AND CAPITAINE ET AL. (2003), ASTRONOMY AND ASTROPHYSICS 412, 567-586.
 TJD1 = TDB JULIAN DATE OF FIRST EPOCH (IN)
 POS1 = POSITION VECTOR, GEOCENTRIC EQUATORIAL RECTANGULAR
        COORDINATES, REFERRED TO MEAN DYNAMICAL EQUATOR AND
        EQUINOX OF FIRST EPOCH (IN)
 TJD2 = TDB JULIAN DATE OF SECOND EPOCH (IN)
 POS2 = POSITION VECTOR, GEOCENTRIC EQUATORIAL RECTANGULAR
        COORDINATES, REFERRED TO MEAN DYNAMICAL EQUATOR AND
        EQUINOX OF SECOND EPOCH (OUT)
NOTE: EITHER TJD1 OR TJD2 MUST BE 2451545.0 (J2000.0) TDB.
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: tjd1
real(kind=wp), dimension(3) :: pos1
real(kind=wp) :: tjd2
real(kind=wp), dimension(3) :: pos2
Called by
Call graph
catran calls preces
celter calls preces, ciobas, sidtim, nutate, cioloc
ciobas calls preces, nutate
ciora calls preces, ciobas, nutate, cioloc
etilt calls preces
gcrseq calls preces, ciobas, nutate, cioloc
geopos calls preces, etilt, sidtim, nutate
mpstar calls preces, place
place calls preces, ciobas, geopos, nutate, cioloc
sidtim calls preces, ciobas, etilt, eqxra, nutate, cioloc
solsys calls preces
tercel calls preces, ciobas, sidtim, nutate, cioloc
eceq calls etilt
eqec calls etilt
eqxra calls etilt
gethip calls catran
nutate calls etilt
places calls place
zdaz calls tercel
cioloc calls eqxra
eqecl calls eqec