radvl – NOVAS
radvl Subroutine
57 statements
Source File
public subroutine radvl(pos, vel, velobs, star, dist, rv)
THIS SUBROUTINE PREDICTS THE RADIAL VELOCITY OF THE OBSERVED OBJECT AS IT WOULD BE MEASURED BY SPECTROSCOPIC MEANS. RADIAL VELOCITY IS HERE DEFINED AS THE RADIAL VELOCITY MEASURE (Z) TIMES THE SPEED OF LIGHT. FOR A SOLAR SYSTEM BODY, IT APPLIES TO A FICTITIOUS EMITTER AT THE CENTER OF THE OBSERVED OBJECT, ASSUMED MASSLESS (NO GRAVITATIONAL RED SHIFT), AND DOES NOT IN GENERAL APPLY TO REFLECTED LIGHT. FOR STARS, IT INCLUDES ALL EFFECTS, SUCH AS GRAVITATIONAL RED SHIFT, CONTAINED IN THE CATALOG BARYCENTRIC RADIAL VELOCITY MEASURE, A SCALAR DERIVED FROM SPECTROSCOPY. NEARBY STARS WITH A KNOWN KINEMATIC VELOCITY VECTOR (OBTAINED INDEPENDENTLY OF SPECTROSCOPY) CAN BE TREATED LIKE SOLAR SYSTEM OBJECTS. SEE LINDEGREN & DRAVINS (2003), ASTRONOMY & ASTROPHYSICS 401, 1185-1201.
 POS    = GEOMETRIC POSITION VECTOR OF OBJECT WITH RESPECT TO
          OBSERVER, CORRECTED FOR LIGHT-TIME, IN AU (IN)
 VEL    = VELOCITY VECTOR OF OBJECT WITH RESPECT TO SOLAR
          SYSTEM BARYCENTER, COMPONENTS IN AU/DAY (IN)
 VELOBS = VELOCITY VECTOR OF OBSERVER WITH RESPECT TO SOLAR
          SYSTEM BARYCENTER, COMPONENTS IN AU/DAY (IN)
 STAR   = 3-ELEMENT ARRAY OF CATALOG DATA FOR A STAR, TO BE
          NON-ZERO IF OBSERVED OBJECT IS A STAR FOR WHICH THE
          CATALOG RADIAL VELOCITY IS CONSISTENT WITH
          THE IAU DEFINITION OF BARYCENTRIC RADIAL VELOCITY
          MEASURE (OTHERWISE ALL ELEMENTS SHOULD BE SET TO
          0.D0 EXACTLY) (IN)
          STAR(1) = CATALOG RA IN HOURS
          STAR(2) = CATALOG DEC IN DEGREES
          STAR(3) = Z*C, THE CATALOG BARYCENTRIC RADIAL
                    VELOCITY MEASURE TIMES THE SPEED OF LIGHT,
                    IN KILOMETERS/SECOND
          ALL THREE DATA ELEMENTS MUST APPLY TO THE SAME
          EPOCH (USUALLY J2000.0 = JD 2451545.0 TT)
 DIST   = 3-ELEMENT ARRAY OF DISTANCES IN AU (IN)
          DIST(1) = DISTANCE OF OBSERVER FROM THE GEOCENTER
          DIST(2) = DISTANCE OF OBSERVER FROM THE SUN
          DIST(3) = DISTANCE OF OBJECT FROM THE SUN
 RV     = THE OBSERVED RADIAL VELOCITY MEASURE TIMES
          THE SPEED OF LIGHT, IN KILOMETERS/SECOND (OUT)
NOTE 1: ALL THE INPUT ARGUMENTS ARE BCRS QUANTITIES, EXPRESSED WITH RESPECT TO THE ICRS AXES. VEL AND VELOBS ARE KINEMATIC VELOCITIES -- DERIVED FROM GEOMETRY OR DYNAMICS, NOT SPECTROSCOPY.
NOTE 2: IF ANY ELEMENT OF ARRAY STAR IS NON-ZERO, THE ALGORITHM USED WILL BE CONSISTENT WITH THE IAU DEFINITION OF STELLAR RADIAL VELOCITY, SPECIFICALLY, THE BARYCENTRIC RADIAL VELOCITY MEASURE, WHICH IS DERIVED FROM SPECTROSCOPY. IN THAT CASE, THE VECTOR VEL CAN BE VERY APPROXIMATE -- OR, FOR DISTANT STARS OR GALAXIES, ZERO -- AS IT WILL BE USED ONLY FOR A SMALL GEOMETRIC CORRECTION THAT IS PROPORTIONAL TO PROPER MOTION.
NOTE 3: ANY OF THE DISTANCES IN ARRAY DIST CAN BE SET TO ZERO (0.D0) IF THE CORRESPONDING GENERAL RELATIVISTIC GRAVITATIONAL POTENTIAL TERM IS NOT TO BE EVALUATED. THESE TERMS GENERALLY ARE IMPORTANT ONLY AT THE METER/SECOND LEVEL. IF THE FIRST TWO DISTANCES ARE BOTH ZERO, AN AVERAGE VALUE WILL BE USED FOR THE RELATIVISTIC TERM FOR THE OBSERVER, APPROPRIATE FOR AN OBSERVER ON THE SURFACE OF THE EARTH. THE THIRD DISTANCE, IF GIVEN, IS USED ONLY FOR SOLAR SYSTEM OBJECTS.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), dimension(3) :: pos
real(kind=wp), dimension(3) :: vel
real(kind=wp), dimension(3) :: velobs
real(kind=wp), dimension(3) :: star
real(kind=wp), dimension(3) :: dist
real(kind=wp) :: rv
Calls
Called by
Call graph
radvl calls astcon
place calls radvl
mpstar calls place
places calls place