sidtim – NOVAS
sidtim Subroutine
44 statements
Source File
public subroutine sidtim(tjdh, tjdl, k, gst)
THIS SUBROUTINE COMPUTES THE GREENWICH SIDEREAL TIME (EITHER MEAN OR APPARENT) AT JULIAN DATE TJDH + TJDL.
   TJDH   = UT1 JULIAN DATE, HIGH-ORDER PART (IN)
   TJDL   = UT1 JULIAN DATE, LOW-ORDER PART (IN)
            THE JULIAN DATE MAY BE SPLIT AT ANY POINT, BUT
            FOR HIGHEST PRECISION, SET TJDH TO BE THE INTEGRAL
            PART OF THE JULIAN DATE, AND SET TJDL TO BE THE
            FRACTIONAL PART
   K      = TIME SELECTION CODE (IN)
            SET K=0 FOR GREENWICH MEAN SIDEREAL TIME
            SET K=1 FOR GREENWICH APPARENT SIDEREAL TIME
   GST    = GREENWICH (MEAN OR APPARENT) SIDEREAL TIME
            IN HOURS (OUT)
NOTE: SEE ALSO SUBROUTINE SETDT TO SET THE VALUE OF DELTA-T (DELTA-T = TT - UT1) TO BE USED HERE.
Arguments
Type Intent Optional Attributes Name
double precision :: tjdh
double precision :: tjdl
integer :: k
double precision :: gst
Calls
Called by
Contents
None
Call graph
sidtim calls ciobas, eqxra, getmod, times, frame, nutate, getdt, erot, cioloc, preces, etilt
ciobas calls frame, nutate, preces
eqxra calls etilt
nutate calls etilt
cioloc calls eqxra, ciord
etilt calls getmod, frame, preces, eect2000, funarg, nod
eect2000 calls anmp
nod calls getmod, nu2000k, nu2000a
nu2000k calls funarg
tercel calls sidtim
celter calls sidtim
geopos calls sidtim
place calls geopos
zdaz calls tercel
mpstar calls place
places calls place