terra – NOVAS
terra Subroutine
34 statements
Source File
public subroutine terra(glon, glat, ht, st, pos, vel)
THIS SUBROUTINE COMPUTES THE POSITION AND VELOCITY VECTORS OF A TERRESTRIAL OBSERVER WITH RESPECT TO THE GEOCENTER.
 GLON   = LONGITUDE OF OBSERVER WITH RESPECT TO REFERENCE
          MERIDIAN (EAST +) IN DEGREES (IN)
 GLAT   = GEODETIC LATITUDE (NORTH +) OF OBSERVER
          IN DEGREES (IN)
 HT     = HEIGHT OF OBSERVER IN METERS (IN)
 ST     = LOCAL APPARENT SIDEREAL TIME AT REFERENCE MERIDIAN
          IN HOURS (IN)
 POS    = POSITION VECTOR OF OBSERVER WITH RESPECT TO
          GEOCENTER, EQUATORIAL RECTANGULAR COORDINATES,
          REFERRED TO TRUE EQUATOR AND EQUINOX OF DATE,
          COMPONENTS IN AU (OUT)
 VEL    = VELOCITY VECTOR OF OBSERVER WITH RESPECT TO
          GEOCENTER, EQUATORIAL RECTANGULAR COORDINATES,
          REFERRED TO TRUE EQUATOR AND EQUINOX OF DATE,
          COMPONENTS IN AU/DAY (OUT)
NOTE 1: IF REFERENCE MERIDIAN IS GREENWICH AND ST=0.D0, POS IS EFFECTIVELY REFERRED TO EQUATOR AND GREENWICH.
NOTE 2: THIS SUBROUTINE IGNORES POLAR MOTION, UNLESS THE OBSERVER'S LONGITUDE AND LATITUDE HAVE BEEN CORRECTED FOR IT, AND VARIATION IN THE LENGTH OF DAY (ANGULAR VELOCITY OF EARTH). NEGLECT OF POLAR MOTION MAY YIELD 15 METERS ERROR IN POSITION AND OF ORDER 1 MILLIMETER/SEC ERROR IN VELOCITY. NEGLECT OF VARIATIONS IN LENGTH OF DAY RESULTS IN EVEN SMALLER VELOCITY ERRORS.
NOTE 3: THE TRUE EQUATOR AND EQUINOX OF DATE DO NOT FORM AN INERTIAL SYSTEM. THEREFORE, WITH RESPECT TO AN INERTIAL SYSTEM, THE SMALL VELOCITY COMPONENT, OF ORDER 0.1 MILLIMETER/SEC, DUE TO THE PRECESSION AND NUTATION OF THE EARTH'S AXIS, IS NOT ACCOUNTED FOR HERE.
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: glon
real(kind=wp) :: glat
real(kind=wp) :: ht
real(kind=wp) :: st
real(kind=wp), dimension(3) :: pos
real(kind=wp), dimension(3) :: vel
Calls
Called by
Call graph
terra calls astcon
geopos calls terra
place calls geopos
mpstar calls place
places calls place