times – NOVAS
times Subroutine
7 statements
Source File
public subroutine times(tdbjd, ttjd, secdif)
THIS SUBROUTINE COMPUTES THE TERRESTRIAL TIME (TT) JULIAN DATE CORRESPONDING TO A BARYCENTRIC DYNAMICAL TIME (TDB) JULIAN DATE. THE EXPRESSION USED IN THIS VERSION IS A TRUNCATED FORM OF A LONGER AND MORE PRECISE SERIES GIVEN BY FAIRHEAD & BRETAGNON (1990) A&A 229, 240. THE RESULT IS GOOD TO ABOUT 10 MICROSECONDS.
   TDBJD  = TDB JULIAN DATE (IN)
   TTJD   = TT JULIAN DATE (OUT)
   SECDIF = DIFFERENCE TDBJD-TTJD, IN SECONDS (OUT)
Arguments
Type Intent Optional Attributes Name
double precision :: tdbjd
double precision :: ttjd
double precision :: secdif
Called by
Contents
None
Call graph
eqec calls times
celter calls times, sidtim
place calls times, geopos
eceq calls times
gcrseq calls times
ciora calls times
sidtim calls times
tercel calls times, sidtim
mpstar calls place
geopos calls sidtim
places calls place
zdaz calls tercel
eqecl calls eqec