wobble – NOVAS
wobble Subroutine
33 statements
Source File
public subroutine wobble(tjd, xp, yp, pos1, pos2)
THIS SUBROUTINE CORRECTS A VECTOR IN THE ITRS (A ROTATING EARTH- FIXED SYSTEM) FOR POLAR MOTION, AND ALSO CORRECTS THE LONGITUDE ORIGIN (BY A TINY AMOUNT) TO THE TERRESTRIAL INTERMEDIATE ORIGIN (TIO). THE ITRS VECTOR IS THEREBY TRANSFORMED TO THE TERRESTRIAL INTERMEDIATE SYSTEM, BASED ON THE TRUE (ROTATIONAL) EQUATOR AND THE TERRESTRIAL INTERMEDIATE ORIGIN (TIO). SINCE THE TRUE EQUATOR IS THE PLANE ORTHOGONAL TO THE DIRECTION OF THE CELESTIAL INTERMEDIATE POLE (CIP), THE COMPONENTS OF THE OUTPUT VECTOR ARE REFERRED TO Z AND X AXES TOWARD THE CIP AND TIO, RESPECTIVELY.
 TJD    = TT OR UT1 JULIAN DATE (IN)
 XP     = CONVENTIONALLY-DEFINED X COORDINATE OF CELESTIAL
          INTERMEDIATE POLE WITH RESPECT TO ITRS POLE, IN
          ARCSECONDS (IN)
 YP     = CONVENTIONALLY-DEFINED Y COORDINATE OF CELESTIAL
          INTERMEDIATE POLE WITH RESPECT TO ITRS POLE, IN
          ARCSECONDS (IN)
 POS1   = POSITION VECTOR, GEOCENTRIC EQUATORIAL RECTANGULAR
          COORDINATES, REFERRED TO ITRS AXES (IN)
 POS2   = POSITION VECTOR, GEOCENTRIC EQUATORIAL RECTANGULAR
          COORDINATES, REFERRED TO TRUE EQUATOR AND TIO (OUT)
NOTE 1: IF TJD IS NEGATIVE, THE INVERSE TRANSFORMATION (TERRESTRIAL INTERMEDIATE SYSTEM TO ITRS) IS APPLIED.
NOTE 2: INPUT PARAMETERS XP, YP WERE X, Y IN NOVAS F3.0. THE NAMES WERE CHANGED FOR CONSISTANCY THROUGHOUT NOVAS AND WITH IERS CONVENTIONS.
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: tjd
real(kind=wp) :: xp
real(kind=wp) :: yp
real(kind=wp), dimension(3) :: pos1
real(kind=wp), dimension(3) :: pos2
Called by
Call graph
celter calls wobble
tercel calls wobble
zdaz calls tercel