zdaz – NOVAS
zdaz Subroutine
67 statements
Source File
public subroutine zdaz(ujd, xp, yp, glon, glat, ht, ra, dec, irefr, zd, az, rar, decr)
THIS SUBROUTINE TRANSFORMS TOPOCENTRIC RIGHT ASCENSION AND DECLINATION TO ZENITH DISTANCE AND AZIMUTH. THIS ROUTINE USES A METHOD THAT PROPERLY ACCOUNTS FOR POLAR MOTION, WHICH IS SIGNIFICANT AT THE SUB-ARCSECOND LEVEL. THIS SUBROUTINE CAN ALSO ADJUST COORDINATES FOR ATMOSPHERIC REFRACTION.
   UJD    = UT1 JULIAN DATE (IN)
   XP     = CONVENTIONALLY-DEFINED X COORDINATE OF CELESTIAL
            INTERMEDIATE POLE WITH RESPECT TO ITRS POLE, IN
            ARCSECONDS (IN)
   YP     = CONVENTIONALLY-DEFINED Y COORDINATE OF CELESTIAL
            INTERMEDIATE POLE WITH RESPECT TO ITRS POLE, IN
            ARCSECONDS (IN)
   GLON   = GEODETIC (ITRS) LONGITUDE (EAST +) OF OBSERVER
            IN DEGREES (IN)
   GLAT   = GEODETIC (ITRS) LATITUDE (NORTH +) OF OBSERVER
            IN DEGREES (IN)
   HT     = HEIGHT OF OBSERVER IN METERS (IN)
   RA     = TOPOCENTRIC RIGHT ASCENSION OF OBJECT OF INTEREST,
            IN HOURS, REFERRED TO TRUE EQUATOR AND EQUINOX
            OF DATE (IN)
   DEC    = TOPOCENTRIC DECLINATION OF OBJECT OF INTEREST,
            IN DEGREES, REFERRED TO TRUE EQUATOR OF DATE (IN)
   IREFR  = ATMOSPHERIC REFRACTION OPTION (IN)
            SET IREFR=0 FOR NO REFRACTION
            SET IREFR=1 TO INCLUDE REFRACTION
   ZD     = TOPOCENTRIC ZENITH DISTANCE IN DEGREES,
            AFFECTED BY REFRACTION IF IREFR=1 (OUT)
   AZ     = TOPOCENTRIC AZIMUTH (MEASURED EAST FROM NORTH)
            IN DEGREES (OUT)
   RAR    = TOPOCENTRIC RIGHT ASCENSION OF OBJECT OF INTEREST,
            IN HOURS, REFERRED TO TRUE EQUATOR AND EQUINOX
            OF DATE, AFFECTED BY REFRACTION IF IREFR=1 (OUT)
   DECR   = TOPOCENTRIC DECLINATION OF OBJECT OF INTEREST,
            IN DEGREES, REFERRED TO TRUE EQUATOR OF DATE,
            AFFECTED BY REFRACTION IF IREFR=1 (OUT)
NOTE 1: XP AND YP CAN BE SET TO ZERO IF SUB-ARCSECOND ACCURACY IS NOT NEEDED. HT IS USED ONLY FOR REFRACTION, IF IREFR=1. RA AND DEC CAN BE OBTAINED FROM TPSTAR, TPPLAN, OR PLACE.
NOTE 2: THE DIRECTONS ZD=0 (ZENITH) AND AZ=0 (NORTH) ARE HERE CONSIDERED FIXED IN THE TERRESTRIAL SYSTEM. SPECIFICALLY, THE ZENITH IS ALONG THE GEODETIC NORMAL, AND NORTH IS TOWARD THE ITRS POLE.
NOTE 3: IF IREFR=0, THEN RAR=RA AND DECR=DEC.
NOTE 4: INPUT PARAMETERS XP, YP WERE X, Y IN NOVAS F3.0. THE NAMES WERE CHANGED FOR CONSISTANCY THROUGHOUT NOVAS AND WITH IERS CONVENTIONS.
Arguments
Type Intent Optional Attributes Name
double precision :: ujd
double precision :: xp
double precision :: yp
double precision :: glon
double precision :: glat
double precision :: ht
double precision :: ra
double precision :: dec
integer :: irefr
double precision :: zd
double precision :: az
double precision :: rar
double precision :: decr
Calls
Contents
None
Call graph
zdaz calls eqinox, resume, refrac, tercel
tercel calls erot, wobble, times, getdt, sidtim, preces, ciobas, getmod, setvec, nutate, spin, cioloc, frame
sidtim calls erot, times, getdt, preces, ciobas, getmod, nutate, cioloc, frame, etilt, eqxra
ciobas calls preces, nutate, frame
nutate calls etilt
cioloc calls eqxra, ciord
etilt calls preces, getmod, frame, funarg, eect2000, nod
eqxra calls etilt
eect2000 calls anmp
nod calls getmod, nu2000a, nu2000k
nu2000k calls funarg